### ISSUE TITLE
Running `bundle exec rake webpacker:install` gives error:  /usr/local/bundle/gems/webpacker-3.0.1/lib/tasks/installers.rake:2: syntax error, unexpected ':', expecting =>   "Angular": :angular,             ^

### ISSUE THREAD

**Issue by bodunadebiyi** [rails/webpacker#1064]
I get this error when I run webpacker:install

```
SyntaxError: /usr/local/bundle/gems/webpacker-3.0.1/lib/tasks/installers.rake:2: syntax error, unexpected ':', expecting =>
  "Angular": :angular,
            ^
/usr/local/bundle/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.0/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/usr/local/bundle/gems/railties-4.2.0/lib/rails/engine.rb:658:in `each'
/usr/local/bundle/gems/railties-4.2.0/lib/rails/engine.rb:658:in `run_tasks_blocks'
/usr/local/bundle/gems/railties-4.2.0/lib/rails/application.rb:437:in `block in run_tasks_blocks'
/usr/local/bundle/gems/railties-4.2.0/lib/rails/engine/railties.rb:13:in `each'
/usr/local/bundle/gems/railties-4.2.0/lib/rails/engine/railties.rb:13:in `each'
/usr/local/bundle/gems/railties-4.2.0/lib/rails/application.rb:437:in `run_tasks_blocks'
/usr/local/bundle/gems/railties-4.2.0/lib/rails/engine.rb:453:in `load_tasks'
/app/Rakefile:10:in `<top (required)>'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `load'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `kernel_load'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/cli.rb:424:in `exec'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/cli.rb:18:in `start'
/usr/local/bundle/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-1.16.0/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
(See full trace by running task with --trace)
```

**Comment by gauravtiwari** [comment]
What version of ruby are you using? Please upgrade: https://github.com/rails/webpacker#prerequisites
