### ISSUE TITLE
Upgrading from Webpacker 1 to Webpacker 3

### ISSUE THREAD

**Issue by yoonwaiyan** [rails/webpacker#1092]
I'm upgrading my Rails app that uses webpacker since version 1 to webpacker 3 to get the latest and more proper config, but seems like there are a lot of breaking changes and they're not properly documented. I've regenerate the config files for webpacker 3 and I haven't remove the old config as the upgrading isn't complete for now. The binstubs has been replaced as well, but doesn't fix the problem I have. I restart my `webpack-dev-server` but the problem persists. This is my error:

```
$ ./bin/webpack-dev-server
 10% building modules 4/4 modules 0 active
Project is running at http://localhost:3035/
webpack output is served from /packs/
Content not from webpack is served from /Users/yoonwaiyan/Documents/workspace/my-project/public/packs
404s will fallback to /index.html
 10% building modules 7/13 modules 6 active ...ce/my-project/node_modules/url/url.js(node:70055) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
 78% advanced chunk optimization/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/dist/index.js:188
            chunk.sortModules();
                  ^

TypeError: chunk.sortModules is not a function
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/dist/index.js:188:19
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1055:9)
    at eachOf (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3158:5)
    at Compilation.<anonymous> (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/dist/index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/tapable/lib/Tapable.js:142:13)
    at Compilation.seal (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/Compilation.js:575:8)
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/Compiler.js:488:16
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/tapable/lib/Tapable.js:225:11
[1]    70054 segmentation fault  yarn dev:wds
```

I haven't start changing my configuration to meet my previous configuration though, anything I've missed out or it's because `lodash` is not compatible to the later versions of some package? Below is my `package.json` (I can give `yarn.lock` if it's needed - not included for now as it's very long). The Rails version for this project is 5.0.2(constantly upgraded since Rails 3) with Ruby 2.4.2, if that helps.

```
{
  "scripts": {
    "start": "yarn dev:puma",
    "dev:puma": "some special command to start rails server",
    "dev:start": "some special command to start rails server",
    "dev:wds": "./bin/webpack-dev-server",
    "jobs": "delayed job task",
    "prod:build": "cross-env NODE_ENV=production ./bin/webpack -p --progress",
    "test": "jest --coverage"
  },
  "jest": {
    "verbose": true,
    "roots": [
      "<rootDir>/app/javascript/"
    ]
  },
  "dependencies": {
    "@rails/webpacker": "^3.1.1",
    "antd": "^2.9.0",
    "autoprefixer": "^6.7.7",
    "babel-polyfill": "^6.23.0",
    "clipboard": "^1.6.1",
    "coffee-loader": "^0.7.3",
    "coffee-script": "^1.12.4",
    "coffeescript": "1.12.7",
    "compression-webpack-plugin": "^0.3.2",
    "css-loader": "^0.28.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.11.1",
    "glob": "^7.1.1",
    "htmlparser2": "^3.9.2",
    "i18next": "^9.0.0",
    "i18next-browser-languagedetector": "^2.0.0",
    "immutable": "^3.8.1",
    "isomorphic-fetch": "^2.2.1",
    "js-cookie": "^2.1.4",
    "js-yaml": "^3.8.2",
    "lodash": "^4.17.4",
    "merge": "^1.2.0",
    "moment": "^2.19.2",
    "nanoid": "^0.2.0",
    "node-sass": "^4.5.2",
    "numeral": "^2.0.6",
    "path-complete-extname": "^0.1.0",
    "postcss-loader": "^1.3.3",
    "postcss-smart-import": "^0.6.10",
    "precss": "^1.4.0",
    "prop-types": "^15.5.10",
    "query-string": "^5.0.0",
    "rails-erb-loader": "^4.0.0",
    "react": "^15.4.2",
    "react-countup": "^3.0.2",
    "react-dom": "^15.4.2",
    "react-fa": "^4.1.2",
    "react-helmet": "^5.0.3",
    "react-hot-loader": "3.0.0-beta.7",
    "react-i18next": "^6.0.2",
    "react-intl": "^2.4.0",
    "react-markdown": "^2.5.0",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "sass-loader": "^6.0.3",
    "string-hash": "^1.1.3",
    "style-loader": "^0.16.1",
    "webpack": "^2.3.3",
    "webpack-manifest-plugin": "^1.1.0",
    "webpack-merge": "^4.1.0"
  },
  "devDependencies": {
    "babel-core": "^6.24.0",
    "babel-eslint": "^7.2.1",
    "babel-loader": "^6.4.1",
    "babel-plugin-import": "^1.1.1",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-0": "^6.24.1",
    "cross-env": "^4.0.0",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-plugin-compat": "^1.0.2",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-react": "^6.10.3",
    "fetch-mock": "^5.9.4",
    "flow-bin": "^0.52.0",
    "jest": "^19.0.2",
    "less": "^2.7.2",
    "less-loader": "^4.0.3",
    "lint-staged": "^5.0.0",
    "prettier": "1.8.2",
    "raw-loader": "^0.5.1",
    "webpack-bundle-analyzer": "^2.4.0",
    "webpack-dev-server": "^2.9.7",
    "xml-loader": "^1.2.1"
  }
}
```

**Comment by gauravtiwari** [comment]
Thanks for report but looks like it's using old version of extract text plugin. Since webpacker 3.x abstracts dependencies into a npm module, you would need to remove all deps from your package.json: https://github.com/rails/webpacker/blob/master/package.json#L14 (these ones can go)

**Comment by yoonwaiyan** [comment]
Removing the dependencies as seen doesn't work too. Here's the newest error in my terminal:

```
ERROR in ./app/javascript/packs/index.jsx
Module build failed: SyntaxError: Unexpected token (17:4)

  15 |   const App = require('components/App').default;
  16 |   ReactDOM.render(
> 17 |     <AppContainer>
     |     ^
  18 |       <I18nextProvider i18n={i18n}>
  19 |         <App />
  20 |       </I18nextProvider>

Error
    at transpile (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/babel-loader/lib/index.js:61:13)
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/babel-loader/lib/fs-cache.js:79:18
    at ReadFileContext.callback (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/babel-loader/lib/fs-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/index.jsx
webpack: Failed to compile.
```

My current package.json: 

```
{
  "scripts": {
    "start": "yarn dev:puma",
    "dev:puma": "bundle exec rvmsudo rails s puma -b 'ssl://0.0.0.0:443?key=ssl.key&cert=ssl.crt'",
    "dev:start": "bundle exec rvmsudo thin start -p 443 --ssl --ssl-key-file ssl.key --ssl-cert-file ssl.crt",
    "dev:wds": "./bin/webpack-dev-server",
    "jobs": "bundle exec rake jobs:work",
    "prod:build": "cross-env NODE_ENV=production ./bin/webpack -p --progress",
    "test": "jest --coverage"
  },
  "jest": {
    "verbose": true,
    "roots": [
      "<rootDir>/app/javascript/"
    ]
  },
  "dependencies": {
    "@rails/webpacker": "^3.1.1",
    "antd": "^2.9.0",
    "autoprefixer": "^6.7.7",
    "clipboard": "^1.6.1",
    "coffee-script": "^1.12.4",
    "coffeescript": "1.12.7",
    "htmlparser2": "^3.9.2",
    "i18next": "^9.0.0",
    "i18next-browser-languagedetector": "^2.0.0",
    "immutable": "^3.8.1",
    "isomorphic-fetch": "^2.2.1",
    "js-cookie": "^2.1.4",
    "lodash": "^4.17.4",
    "merge": "^1.2.0",
    "moment": "^2.19.2",
    "nanoid": "^0.2.0",
    "numeral": "^2.0.6",
    "postcss-smart-import": "^0.6.10",
    "precss": "^1.4.0",
    "prop-types": "^15.5.10",
    "query-string": "^5.0.0",
    "react": "^15.4.2",
    "react-countup": "^3.0.2",
    "react-dom": "^15.4.2",
    "react-fa": "^4.1.2",
    "react-helmet": "^5.0.3",
    "react-hot-loader": "3.0.0-beta.7",
    "react-i18next": "^6.0.2",
    "react-intl": "^2.4.0",
    "react-markdown": "^2.5.0",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "string-hash": "^1.1.3",
    "webpack-merge": "^4.1.0"
  },
  "devDependencies": {
    "babel-core": "^6.24.0",
    "babel-eslint": "^7.2.1",
    "babel-loader": "^6.4.1",
    "babel-plugin-import": "^1.1.1",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-0": "^6.24.1",
    "cross-env": "^4.0.0",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-plugin-compat": "^1.0.2",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-react": "^6.10.3",
    "fetch-mock": "^5.9.4",
    "flow-bin": "^0.52.0",
    "jest": "^19.0.2",
    "less": "^2.7.2",
    "less-loader": "^4.0.3",
    "lint-staged": "^5.0.0",
    "prettier": "1.8.2",
    "raw-loader": "^0.5.1",
    "webpack-bundle-analyzer": "^2.4.0",
    "webpack-dev-server": "^2.9.7",
    "xml-loader": "^1.2.1"
  }
}
```

If it's hard to see which deps I've removed, this is the diff:
```diff
diff --git a/package.json b/package.json
index f6a0fd4a..158b6d15 100644
--- a/package.json
+++ b/package.json
@@ -18,36 +18,24 @@
     "@rails/webpacker": "^3.1.1",
     "antd": "^2.9.0",
     "autoprefixer": "^6.7.7",
-    "babel-polyfill": "^6.23.0",
     "clipboard": "^1.6.1",
-    "coffee-loader": "^0.7.3",
     "coffee-script": "^1.12.4",
     "coffeescript": "1.12.7",
-    "compression-webpack-plugin": "^0.3.2",
-    "css-loader": "^0.28.0",
-    "extract-text-webpack-plugin": "^2.1.0",
-    "file-loader": "^0.11.1",
-    "glob": "^7.1.1",
     "htmlparser2": "^3.9.2",
     "i18next": "^9.0.0",
     "i18next-browser-languagedetector": "^2.0.0",
     "immutable": "^3.8.1",
     "isomorphic-fetch": "^2.2.1",
     "js-cookie": "^2.1.4",
-    "js-yaml": "^3.8.2",
     "lodash": "^4.17.4",
     "merge": "^1.2.0",
     "moment": "^2.19.2",
     "nanoid": "^0.2.0",
-    "node-sass": "^4.5.2",
     "numeral": "^2.0.6",
-    "path-complete-extname": "^0.1.0",
-    "postcss-loader": "^1.3.3",
     "postcss-smart-import": "^0.6.10",
     "precss": "^1.4.0",
     "prop-types": "^15.5.10",
     "query-string": "^5.0.0",
-    "rails-erb-loader": "^4.0.0",
     "react": "^15.4.2",
     "react-countup": "^3.0.2",
     "react-dom": "^15.4.2",
@@ -59,11 +47,7 @@
     "react-markdown": "^2.5.0",
     "react-router": "^4.0.0",
     "react-router-dom": "^4.0.0",
-    "sass-loader": "^6.0.3",
     "string-hash": "^1.1.3",
-    "style-loader": "^0.16.1",
-    "webpack": "^2.3.3",
-    "webpack-manifest-plugin": "^1.1.0",
     "webpack-merge": "^4.1.0"
   },
   "devDependencies": {
```

Removing my dev dependencies wasn't a good idea as it yields error that babel-loader is not found. Any idea?

**Comment by gauravtiwari** [comment]
Can you do `yarn add @rails/webpacker babel-preset-react` please? Looks like babel isn't recognizing JSX.

**Comment by yoonwaiyan** [comment]
@gauravtiwari unfortunately `babel-preset-react` is already installed and it was upgraded from `6.23.0` to `6.24.1`. The error persists but this time it comes from other files, for example:

```
ERROR in ./app/javascript/components/App.jsx
Module build failed: SyntaxError: Unexpected token (33:2)

  31 |
  32 | const loadDashboard = props => () => (
> 33 |   <Bundle load={() => import('./Dashboard')}>
     |   ^
  34 |     {Dashboard => (Dashboard ? <Dashboard {...props} /> : <Loading />)}
  35 |   </Bundle>
  36 | );

Error
    at transpile (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/babel-loader/lib/index.js:61:13)
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/babel-loader/lib/fs-cache.js:79:18
    at ReadFileContext.callback (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/babel-loader/lib/fs-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)
 @ ./app/javascript/packs/index.jsx 29:12-37
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/index.jsx
```

**Comment by gauravtiwari** [comment]
@yoonwaiyan Pretty sure it's related to some config being wrong in your app. Could you please reinstall webpacker?

```
bundle exec rails webpacker:install
bundle exec rails:webpacker:install:react
```

**Comment by gauravtiwari** [comment]
Just released 3.2.0, please upgrade - see Changelog for more details.

**Comment by yoonwaiyan** [comment]
I've been redoing the upgrade from my working version to use webpacker 3.2 and followed your commands but it doesn't help. I've tried only removing extract text plugin and the error is back to the OP again. 

It's not so helpful to close this issue without any real help and leaving me confused to mention I have config problem(at least telling me what kind of configuration maybe?) and it's still remain unresolved. The only config I did was changing assets to be hosted on https and some enhancement such as ignoring unused locales which original config from webpacker gem are pretty much remain untouched. Kinda not expecting this from community that maintain rails projects.

**Comment by gauravtiwari** [comment]
@yoonwaiyan Happy to help with your upgrade

**Comment by gauravtiwari** [comment]
It's hard to understand the actual problem you are having. Have you followed this guide from Changelog? https://github.com/rails/webpacker/blob/master/CHANGELOG.md#300---2017-08-30

Most of the configs now lives under webpacker npm module so you don't need them in your app. Please could you post how does your `config/webpack` folder looks like?

**Comment by gauravtiwari** [comment]
How about if you remove `yarn.lock` and re-install? How does your babelrc looks like?

```
rm -rf yarn.lock
yarn install
```

**Comment by yoonwaiyan** [comment]
Thank you very much. 

Tried remove yarn.lock and `yarn install`, still the same error in OP.

```
webpack output is served from https://localhost:8080/
Content not from webpack is served from /Users/yoonwaiyan/Documents/workspace/my-project/public/packs
404s will fallback to /index.html
 10% building modules 7/15 modules 8 active .../webpack-dev-server/client/overlay.js(node:2574) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
 78% advanced chunk optimization/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/dist/index.js:188
            chunk.sortModules();
                  ^

TypeError: chunk.sortModules is not a function
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/dist/index.js:188:19
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1055:9)
    at eachOf (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3158:5)
    at Compilation.<anonymous> (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/@rails/webpacker/node_modules/extract-text-webpack-plugin/dist/index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/tapable/lib/Tapable.js:206:13)
    at Compilation.seal (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/Compilation.js:579:8)
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/Compiler.js:493:16
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/tapable/lib/Tapable.js:289:11
```

And this is my current .babelrc:
```
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": "> 1%",
          "uglify": true
        },
        "useBuiltIns": true
      }
    ],
    "react"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ]
}

```
while git diff my previous .babelrc
```diff
diff --git a/.babelrc b/.babelrc
index 75e4c04e..2bd0fd3b 100644
--- a/.babelrc
+++ b/.babelrc
@@ -1,26 +1,13 @@
 {
   "presets": [
-    [
-      "env",
-      {
-        "modules": false,
-        "targets": {
-          "browsers": "> 1%",
-          "uglify": true
-        },
-        "useBuiltIns": true
-      }
-    ],
+    ["env", { "modules": false }],
+    "es2015",
     "react"
   ],
   "plugins": [
-    "syntax-dynamic-import",
     "transform-object-rest-spread",
     [
-      "transform-class-properties",
-      {
-        "spec": true
-      }
+      "import", { "libraryName": "antd" }
     ]
   ]
 }
```

This is my current `config/webpack` folder:
<img width="312" alt="screen shot 2017-12-20 at 5 54 41 pm" src="https://user-images.githubusercontent.com/3081772/34201552-cfd670c4-e5af-11e7-8f57-70fed543a6d9.png">

**Comment by gauravtiwari** [comment]
Right I see and what's in `development.js`? Could you please paste screenshot? Just checking if this file is upgraded. Also, have you removed all deps that webpacker already has: https://github.com/rails/webpacker/blob/master/package.json#L14

**Comment by yoonwaiyan** [comment]
Ok, I've removed the packages by following the earlier diff and removed yarn.lock to reinstall the deps. While having one project-related error there is one repeating error here:

```
ERROR in chunk index [entry]
[name]-[chunkhash].js
Cannot use [chunkhash] for chunk in '[name]-[chunkhash].js' (use [hash] instead)
Error: Cannot use [chunkhash] for chunk in '[name]-[chunkhash].js' (use [hash] instead)
    at MainTemplate.replacePathVariables (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/TemplatedPathPlugin.js:64:9)
    at MainTemplate.applyPluginsWaterfall (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/tapable/lib/Tapable.js:92:24)
    at Compilation.getPath (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/Compilation.js:1424:28)
    at Compilation.createChunkAssets (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/Compilation.js:1406:17)
    at sealPart2 (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/Compilation.js:655:10)
    at next (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/ProgressPlugin.js:111:6)
    at next (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/tapable/lib/Tapable.js:204:14)
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/extract-text-webpack-plugin/dist/index.js:244:13
    at /Users/yoonwaiyan/Documents/workspace/my-project/node_modules/async/dist/async.js:473:16

ERROR in chunk navigation [entry]
[name]-[chunkhash].js
Cannot use [chunkhash] for chunk in '[name]-[chunkhash].js' (use [hash] instead)
Error: Cannot use [chunkhash] for chunk in '[name]-[chunkhash].js' (use [hash] instead)
    at MainTemplate.replacePathVariables (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/TemplatedPathPlugin.js:64:9)
    at MainTemplate.applyPluginsWaterfall (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/tapable/lib/Tapable.js:92:24)
    at Compilation.getPath (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/Compilation.js:1424:28)
    at Compilation.createChunkAssets (/Users/yoonwaiyan/Documents/workspace/my-project/node_modules/webpack/lib/Compilation.js:1406:17)
```

This is my current `development.js`:
<img width="920" alt="screen shot 2017-12-20 at 6 08 19 pm" src="https://user-images.githubusercontent.com/3081772/34202166-eac24e2e-e5b1-11e7-82b8-0ed1ba6d57ad.png">

**Comment by gauravtiwari** [comment]
Have you updated binstubs? Looks like it's almost there: 

```
bundle binstubs webpacker --force
```

Also, remove `development.server.js, yml and configuration.js files`

**Comment by yoonwaiyan** [comment]
Thanks! It's finally compiling, but now error comes from Rails instead:

```
Webpacker::Manifest::MissingEntryError - Webpacker can't find index.css in /Users/yoonwaiyan/Documents/workspace/my-project/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "0-c0325c7bb67a625b03b9.chunk.js": "/packs/0-c0325c7bb67a625b03b9.chunk.js",
  "0-c0325c7bb67a625b03b9.chunk.js.map": "/packs/0-c0325c7bb67a625b03b9.chunk.js.map",
  "1-1b65245f5daf9ae7a5aa.chunk.js": "/packs/1-1b65245f5daf9ae7a5aa.chunk.js",
  "1-1b65245f5daf9ae7a5aa.chunk.js.map": "/packs/1-1b65245f5daf9ae7a5aa.chunk.js.map",
  "2-3bcfbafcc67d1b6de5e3.chunk.js": "/packs/2-3bcfbafcc67d1b6de5e3.chunk.js",
  "2-3bcfbafcc67d1b6de5e3.chunk.js.map": "/packs/2-3bcfbafcc67d1b6de5e3.chunk.js.map",
  "_/_/node_modules/font-awesome/fonts/fontawesome-webfont.eot": "/packs/_/_/node_modules/font-awesome/fonts/fontawesome-webfont-674f50d287a8c48dc19ba404d20fe713.eot",
  "_/_/node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0": "/packs/_/_/node_modules/font-awesome/fonts/fontawesome-webfont-912ec66d7572ff821749319396470bde.svg",
  "_/_/node_modules/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0": "/packs/_/_/node_modules/font-awesome/fonts/fontawesome-webfont-b06871f281fee6b241d60582ae9369b9.ttf",
  "_/_/node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0": "/packs/_/_/node_modules/font-awesome/fonts/fontawesome-webfont-af7ae505a9eed503f8b8e6982036873e.woff2",
  "_/_/node_modules/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0": "/packs/_/_/node_modules/font-awesome/fonts/fontawesome-webfont-fee66e712a8a08eef5805a46892932ad.woff",
  "application.js": "/packs/application-2b952e32725ed4a29d35.js",
  "application.js.map": "/packs/application-2b952e32725ed4a29d35.js.map",
  "footer.js": "/packs/footer-6ed16ea5c1e2f31728a1.js",
  "footer.js.map": "/packs/footer-6ed16ea5c1e2f31728a1.js.map",
  "hello_react.js": "/packs/hello_react-4d2c98ead708c0f00791.js",
  "hello_react.js.map": "/packs/hello_react-4d2c98ead708c0f00791.js.map",
  "images/C2QB_white_btn_lg_default.png": "/packs/images/C2QB_white_btn_lg_default-2ca54bd399cec4ec19525de679402971.png",
  "images/C2QB_white_btn_lg_hover.png": "/packs/images/C2QB_white_btn_lg_hover-eccd4d02b0eca7d9898abe6a0cc10ef4.png",
  "index.js": "/packs/index-ee1966eac9284cd26eb1.js",
  "index.js.map": "/packs/index-ee1966eac9284cd26eb1.js.map",
  "navigation.js": "/packs/navigation-712f05718f6009b87f2a.js",
  "navigation.js.map": "/packs/navigation-712f05718f6009b87f2a.js.map",
  "stylesheets/index.less": "/packs/stylesheets/index-663cb6e3977f7560a53c03be6d187d38.less"
}
```

I have one `index.less` to be used in my template:
```
<div id="app"></div>
<%= javascript_pack_tag 'index' %>
<%= stylesheet_pack_tag 'index' %>

``` 
noting that `paths.yml` already include .less files

**Comment by gauravtiwari** [comment]
Are you using less loader?

**Comment by gauravtiwari** [comment]
How does your environment.js looks like?

**Comment by yoonwaiyan** [comment]
i have one `less-loader` in dev deps, should I remove it?

this is my environment.js:
<img width="867" alt="screen shot 2017-12-20 at 8 04 42 pm" src="https://user-images.githubusercontent.com/3081772/34206330-12269394-e5c1-11e7-988d-c6f16860b749.png">

**Comment by gauravtiwari** [comment]
Then you would need to add less loader to environment to process less files: 

```js
// require less loader from loaders dir
const coffee =  require('./loaders/less')
environment.loaders.append('less', less)

//.. require other custom loaders
```

See changelog: https://github.com/rails/webpacker/blob/master/CHANGELOG.md#breaking-changes

**Comment by yoonwaiyan** [comment]
Now I have problem compiling again, due the the path configuration was in the removed configuration.js. 

```
$ ./bin/webpack-dev-server
module.js:544
    throw err;
    ^

Error: Cannot find module '../configuration.js'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yoonwaiyan/Documents/workspace/my-project/config/webpack/loaders/less.js:2:24)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I saw the paths.yml having an output configuration but not sure if it's accessible in my loaders/less because quite some places are using the configuration file to access the `publicPath` :  

```js
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const { publicPath } = require('../configuration.js');
const { join, resolve } = require('path');

const configPath = resolve('config', 'webpack');

const theme = {
  '@icon-url': `'${publicPath}iconfont'`
};

module.exports = {
  test: /\.(less)$/i,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      'css-loader',
      {
        loader: 'postcss-loader',
        options: {
          config: join(configPath, 'postcss.config.js')
        }
      },
      {
        loader: 'less-loader',
        options: {
          modifyVars: theme
        }
      }
    ]
  })
};

```

**Comment by yoonwaiyan** [comment]
For your information the publicPath inside my configuration.js was
```
const publicPath = env.NODE_ENV !== 'production' && devServer.enabled ?
  `https://${devServer.host}:${devServer.port}/` : `/${paths.entry}/`
```

**Comment by gauravtiwari** [comment]
@yoonwaiyan Were you able to upgrade webpacker to version 3?

**Comment by yoonwaiyan** [comment]
@gauravtiwari I'm still waiting for your response actually.

**Comment by gauravtiwari** [comment]
@yoonwaiyan If you are using 3.0+ or latest 3.2.0 then configuration.js needs to be deleted and all configuration for dev server is under `config/webpacker.yml`

Here is information on which files needs to be deleted: https://github.com/rails/webpacker/blob/master/CHANGELOG.md#breaking-changes-1

**Comment by canted** [comment]
I was having this issue after upgrading from 1.0 to 3.2, but I was able to fix it with
`yarn remove webpack webpack-merge`
