### ISSUE TITLE
Passing options to postcss-custom-properties

### ISSUE THREAD

**Issue by sidot3291** [rails/webpacker#1141]
I'm having a hard time figuring out how to pass options to postcss-custom-properties.

I've tried both of the following:

```
plugins:
  postcss-smart-import: {}
  postcss-cssnext: {}
  postcss-custom-properties: {
    preserve: true,
    warnings: false
  }
```

```
plugins:
  postcss-smart-import: {}
  postcss-cssnext: {
    customProperties: {
      preserve: true,
      warnings: false
    }
  }
```

Neither are having an impact on the warnings when I run webpack-dev-server (or that my css isn't loading properly):
```
    WARNING in ./node_modules/css-loader?{"minimize":false,"sourceMap":true,"importLoaders":2}!./node_modules/postcss-loader/lib?{"sourceMap":true,"config":{"path":"/ROOT/.postcssrc.yml"}}!./node_modules/material-components-web/dist/material-components-web.css
    (Emitted value instead of an instance of Error) postcss-custom-properties: /ROOT/node_modules/material-components-web/dist/material-components-web.css:9325:5: Custom property ignored: not scoped to the top-level :root element (.mdc-text-field--box.mdc-ripple-upgraded { ... --mdc-ripple-fg-opacity: ... })
    NonErrorEmittedError: (Emitted value instead of an instance of Error) postcss-custom-properties: /ROOT/node_modules/material-components-web/dist/material-components-web.css:9325:5: Custom property ignored: not scoped to the top-level :root element (.mdc-text-field--box.mdc-ripple-upgraded { ... --mdc-ripple-fg-opacity: ... })
        at Object.emitWarning (/ROOT/node_modules/webpack/lib/NormalModule.js:117:16)
        at result.warnings.forEach (/ROOT/node_modules/postcss-loader/lib/index.js:149:49)
        at Array.forEach (native)
        at postcss.process.then (/ROOT/node_modules/postcss-loader/lib/index.js:149:27)
        at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by sidot3291** [comment]
I tend to have more success after I post an issue.  It's this:
```
plugins:
  postcss-smart-import: {}
  postcss-cssnext: {
    features: {
      customProperties: {
        preserve: "computed",
        warnings: false
      }
    }
```
  }

**Comment by MaikelGG** [comment]
I tried the above solution with postcss-cssnext as well as the postcss-css-variables plugin, but they didn't work. It does work together with webpack-dev-server, but when it compiles it doesn't output both options. The plugin that does work is postcss-custom-properties. I didn't use any options. This works well in case you want to print both the variable as well as the value for IE11. Maybe this can help somebody having the same issue.

postcssrc.yml:
```
plugins:
  postcss-import: {}
  postcss-custom-properties: {}
```
