### ISSUE TITLE
Getting an SSL error when trying to use Webpacker in development

### ISSUE THREAD

**Issue by chintanparikh** [rails/webpacker#1152]
When I request this URL via HTTP, it works fine:
http://chintanparikh.ngrok.io/packs/preview_container-e45f00115f7a6f3fb321.js

However, when I try with the HTTPS version:
https://chintanparikh.ngrok.io/packs/preview_container-e45f00115f7a6f3fb321.js

I get the following error:

```
2017-12-30 18:34:09 -0600: Rack app error handling request { GET /packs/preview_container-e45f00115f7a6f3fb321.js }
#<OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A>
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:948:in `connect'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:882:in `start'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rack-proxy-0.6.3/lib/rack/http_streaming_response.rb:71:in `session'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rack-proxy-0.6.3/lib/rack/http_streaming_response.rb:60:in `response'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rack-proxy-0.6.3/lib/rack/http_streaming_response.rb:29:in `headers'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rack-proxy-0.6.3/lib/rack/proxy.rb:120:in `perform_request'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/webpacker-3.2.0/lib/webpacker/dev_server_proxy.rb:16:in `perform_request'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rack-proxy-0.6.3/lib/rack/proxy.rb:57:in `call'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:522:in `call'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
/Users/chintanparikh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

I'm running:
`rails s`
`./bin/webpack-dev-server`
`ngrok http -subdomain=chintanparikh 3000`

Here's my webpacker.yml
```
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: true
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```

Any idea what's going on? Happy to provide more info, just not sure what else would be useful to diagnose

**Comment by chintanparikh** [comment]
Whoops, nevermind. I just had to restart webpack-dev-server
