### ISSUE TITLE
Webpacker::Compiler does not work on windows

### ISSUE THREAD

**Issue by cshupp1** [rails/webpacker#1175]
Setup:
```
    webpacker (3.2.0)
    rails (5.1.4)
    JRuby 9.1.15.0
```
On windows 10 when attempting to do a build the default impl fails, consider:

```
I, [2018-01-12T13:41:43.835000 #21728]  INFO -- : Removed C:/work/VSO/vso/public/assets
Webpacker is installed ? ?
Using C:/work/VSO/vso/config/webpacker.yml file for setting up webpack paths
Removed webpack output path directory C:/work/VSO/vso/public/packs
I, [2018-01-12T13:41:45.474000 #21728]  INFO -- : Writing C:/work/VSO/vso/public/assets/application-160ac749943c79975be00382121c915dd3a12143813d6704412d90f4c5dd6e1b.js
I, [2018-01-12T13:41:45.507000 #21728]  INFO -- : Writing C:/work/VSO/vso/public/assets/application-160ac749943c79975be00382121c915dd3a12143813d6704412d90f4c5dd6e1b.js.gz
I, [2018-01-12T13:41:45.563000 #21728]  INFO -- : Writing C:/work/VSO/vso/public/assets/application-f0d704deea029cf000697e2c0181ec173a1b474645466ed843eb5ee7bb215794.css
I, [2018-01-12T13:41:45.565000 #21728]  INFO -- : Writing C:/work/VSO/vso/public/assets/application-f0d704deea029cf000697e2c0181ec173a1b474645466ed843eb5ee7bb215794.css.gz
I, [2018-01-12T13:41:48.846000 #21728]  INFO -- : Writing C:/work/VSO/vso/public/assets/express/lib/application-9232ebdb20ad39572e70fb9e29810e63dbb63b58f5f18617c7c2bc8bd28321b5.js
I, [2018-01-12T13:41:48.848000 #21728]  INFO -- : Writing C:/work/VSO/vso/public/assets/express/lib/application-9232ebdb20ad39572e70fb9e29810e63dbb63b58f5f18617c7c2bc8bd28321b5.js.gz
Compiling?
rake aborted!
IOError: Cannot run program "bundle" (in directory "C:\work\VSO\vso"): CreateProcess error=2, The system cannot find the file specified
C:/work/VSO/gem_home/gems/webpacker-3.2.0/lib/webpacker/compiler.rb:56:in `run_webpack'
C:/work/VSO/gem_home/gems/webpacker-3.2.0/lib/webpacker/compiler.rb:22:in `compile'
C:/work/VSO/gem_home/gems/webpacker-3.2.0/lib/webpacker/commands.rb:19:in `compile'
C:/work/VSO/gem_home/gems/webpacker-3.2.0/lib/webpacker.rb:18:in `compile'
C:/work/VSO/gem_home/gems/webpacker-3.2.0/lib/tasks/webpacker/compile.rake:25:in `block in (root)'
C:/work/VSO/gem_home/gems/webpacker-3.2.0/lib/tasks/webpacker/compile.rake:6:in `ensure_log_goes_to_stdout'
C:/work/VSO/gem_home/gems/webpacker-3.2.0/lib/tasks/webpacker/compile.rake:24:in `block in (root)'
C:/work/VSO/gem_home/gems/webpacker-3.2.0/lib/tasks/webpacker/compile.rake:17:in `block in enhance_assets_precompile'
C:/work/VSO/vso/lib/tasks/devops.rake:68:in `block in (root)'
C:/work/VSO/vso/lib/tasks/devops.rake:54:in `block in (root)'
C:/work/VSO/gem_home/gems/rake-12.3.0/exe/rake:27:in `<main>'
C:\work\VSO\gem_home\bin\rake:23:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)
```

Note:
**IOError: Cannot run program "bundle" (in directory "C:\work\VSO\vso"): CreateProcess error=2, The system cannot find the file specified**
in the output above.

Workaround (placed in wrapper rake task which sets up the environment):
```
if WINDOWS
  class Webpacker::Compiler
    include FileUtils
    def run_webpack
      logger.info "Compiling…"
      command = "bundle exec webpack"
      logger.info "Invoking special windows version of webpack, calling:"
      logger.info command
      sh command
      logger.info "Compiled all packs in #{config.public_output_path}"
    end
  end
end
```
Yields:
```
Webpacker is installed ? ?
Using C:/work/VSO/vso/config/webpacker.yml file for setting up webpack paths
Removed webpack output path directory C:/work/VSO/vso/public/packs
I, [2018-01-12T13:40:01.225000 #24980]  INFO -- : Writing C:/work/VSO/vso/public/assets/application-160ac749943c79975be00382121c915dd3a12143813d6704412d90f4c5dd6e1b.js
I, [2018-01-12T13:40:01.274000 #24980]  INFO -- : Writing C:/work/VSO/vso/public/assets/application-160ac749943c79975be00382121c915dd3a12143813d6704412d90f4c5dd6e1b.js.gz
I, [2018-01-12T13:40:01.329000 #24980]  INFO -- : Writing C:/work/VSO/vso/public/assets/application-f0d704deea029cf000697e2c0181ec173a1b474645466ed843eb5ee7bb215794.css
I, [2018-01-12T13:40:01.333000 #24980]  INFO -- : Writing C:/work/VSO/vso/public/assets/application-f0d704deea029cf000697e2c0181ec173a1b474645466ed843eb5ee7bb215794.css.gz
I, [2018-01-12T13:40:05.533000 #24980]  INFO -- : Writing C:/work/VSO/vso/public/assets/express/lib/application-9232ebdb20ad39572e70fb9e29810e63dbb63b58f5f18617c7c2bc8bd28321b5.js
I, [2018-01-12T13:40:05.536000 #24980]  INFO -- : Writing C:/work/VSO/vso/public/assets/express/lib/application-9232ebdb20ad39572e70fb9e29810e63dbb63b58f5f18617c7c2bc8bd28321b5.js.gz
Compiling?
Invoking special windows version of webpack, calling:
bundle exec webpack
bundle exec webpack
Hash: e5fc93b17902bd15378e
Version: webpack 3.10.0
Time: 3138ms
                                        Asset       Size  Chunks             Chunk Names
    hello\hello_react-e797bf99ffea0a103867.js     101 kB       0  [emitted]  hello\hello_react
          application-15ff0ee0ea115b16c0c1.js  590 bytes       1  [emitted]  application
hello\hello_react-e797bf99ffea0a103867.js.map     130 kB       0  [emitted]  hello\hello_react
      application-15ff0ee0ea115b16c0c1.js.map     1.2 kB       1  [emitted]  application
                                manifest.json  310 bytes          [emitted]
       application-15ff0ee0ea115b16c0c1.js.gz  370 bytes          [emitted]
                             manifest.json.gz  142 bytes          [emitted]
 hello/hello_react-e797bf99ffea0a103867.js.gz    32.1 kB          [emitted]
   [4] ./app/javascript/packs/application.js 515 bytes {1} [built]
   [5] ./app/javascript/packs/hello/hello_react.jsx 753 bytes {0} [built]
    + 19 hidden modules
Compiled all packs in C:/work/VSO/vso/public/packs
"build the context file"
"context is /vso"
"build the version file"
"version is unversioned"
rm -f ./target//vso.war
Creating ./target//vso.war
```

**Comment by gauravtiwari** [comment]
@cshupp1 Is this still an issue for you?

**Comment by cshupp1** [comment]
I will try with 3.2.1 Monday.

**Comment by cshupp1** [comment]
@gauravtiwari  yes the same issue occurs with 3.2.1.

I need my monkey patch to succeed:
```
if WINDOWS
  class Webpacker::Compiler
    include FileUtils
    def run_webpack
      logger.info "Compiling…"
      command = "bundle exec webpack"
      logger.info "Invoking special windows version of webpack, calling:"
      logger.info command
      sh command
      logger.info "Compiled all packs in #{config.public_output_path}"
    end
  end
end
```

**Comment by cshupp1** [comment]
I just wrote up:

https://github.com/jruby/jruby/issues/5018
