### ISSUE TITLE
Webpacker looking for `webpack` binary in the ruby library directory when deploying to Elasticbeanstalk

### ISSUE THREAD

**Issue by ctrlaltdylan** [rails/webpacker#1206]
I have added both yarn and node v6 to the Elasticbeanstalk instance through `.ebextensions` commands. However, the `bundle exec rails assets:precompile` step is failing during EBS deployment:

```
  Webpacker is installed 🎉 🍰
  Using /var/app/ondeck/config/webpacker.yml file for setting up webpack paths
  Compiling…
  Compilation failed:
  bundler: failed to load command: webpack (/opt/rubies/ruby-2.3.6/bin/webpack)

  Errno::ENOENT: No such file or directory - /var/app/ondeck/node_modules/.bin/webpack
    /opt/rubies/ruby-2.3.6/lib/ruby/gems/2.3.0/gems/webpacker-3.2.1/lib/webpacker/webpack_runner.rb:11:in `exec'
    /opt/rubies/ruby-2.3.6/lib/ruby/gems/2.3.0/gems/webpacker-3.2.1/lib/webpacker/webpack_runner.rb:11:in `block in run'
    /opt/rubies/ruby-2.3.6/lib/ruby/gems/2.3.0/gems/webpacker-3.2.1/lib/webpacker/webpack_runner.rb:10:in `chdir'
    /opt/rubies/ruby-2.3.6/lib/ruby/gems/2.3.0/gems/webpacker-3.2.1/lib/webpacker/webpack_runner.rb:10:in `run'
    /opt/rubies/ruby-2.3.6/lib/ruby/gems/2.3.0/gems/webpacker-3.2.1/lib/webpacker/runner.rb:6:in `run'
    /opt/rubies/ruby-2.3.6/lib/ruby/gems/2.3.0/gems/webpacker-3.2.1/exe/webpack:8:in `<top (required)>'
    /opt/rubies/ruby-2.3.6/bin/webpack:23:in `load'
    /opt/rubies/ruby-2.3.6/bin/webpack:23:in `<top (required)>'
   (Executor::NonZeroExitStatus)


[2018-01-22T20:59:58.066Z] INFO  [18010] - [Application update app-b070-180122_155220@61/AppDeployStage0/AppDeployPreHook/11_asset_compilation.sh] : Activity failed.
[2018-01-22T20:59:58.066Z] INFO  [18010] - [Application update app-b070-180122_155220@61/AppDeployStage0/AppDeployPreHook] : Activity failed.
[2018-01-22T20:59:58.066Z] INFO  [18010] - [Application update app-b070-180122_155220@61/AppDeployStage0] : Activity failed.
```

Why is rails looking for webpack in the `/opt/rubies` instead of at the application root?

**Comment by ctrlaltdylan** [comment]
Realizing that maybe I read the error message wrong, I believe it's actually looking in the `node_modules/.bin` directory instead which may be fixed by adding webpack as a packages.json dependency. Un momento while I try 🕐

**Comment by ctrlaltdylan** [comment]
Yup that was it.
