### ISSUE TITLE
Downgrade to @rails/webpacker 3.0.2 not working

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [rails/webpacker#1243]
I tried upgrading my webpacker gem and the npm package, but as mentioned in https://github.com/rails/webpacker/issues/1178 this issue it doesn't work.

I just removed my `node_module` and did `yarn`, but now my server won't start.

Here is the output:

```
aks:shareito$ bin/webpack-dev-server 
...
Bundle complete! 23 Gemfile dependencies, 128 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
/home/aks/projects/shareito/config/webpack/loaders/vue.js:1
(function (exports, require, module, __filename, __dirname) { const { dev_server: devServer } = require('@rails/webpacker').config
                                                                      ^

TypeError: Cannot destructure property `dev_server` of 'undefined' or 'null'.
    at Object.<anonymous> (/home/aks/projects/shareito/config/webpack/loaders/vue.js:1:124)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/aks/projects/shareito/config/webpack/environment.js:2:14)
    at Module._compile (module.js:635:30)
```

**Comment by ankitsinghaniyaz** [comment]
`bundle exec rails webpacker:install:vue` touches some file, which will only work with the latest @rails/webpacker version.
