### ISSUE TITLE
Error "Cannot read property '_init' of undefined" on running rails assets:precompile after upgrading to 3.2.1

### ISSUE THREAD

**Issue by Loremaster** [rails/webpacker#1259]
Hey!

We have app with a bit of vue. Currently we use `3.0.2` and it works great. Today I tried to upgrade webpacker to `3.2.1`. I updated gem, and run 

```
$ yarn upgrade @rails/webpacker --latest
$ bundle exec rails webpacker:install:vue
```

However with this new version compiling assets fails (which means I can't deploy to the server on heroku):

```
$ rake assets:precompile
/Projects/Email_platform/lib/liquid/concerns/text.rb:4: warning: already initialized constant Liquid::Concerns::Text::NO_SELECTED_TEXT_MSG
/Projects/Email_platform/lib/liquid/concerns/text.rb:4: warning: previous definition of NO_SELECTED_TEXT_MSG was here
yarn install v1.3.2
warning package.json: No license field
warning No license field
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning " > vue-loader@14.1.1" has unmet peer dependency "css-loader@*".
warning " > mocha-webpack@1.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0".
warning " > webpack-dev-server@2.11.1" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
[5/5] 📃  Building fresh packages...
✨  Done in 28.49s.
Webpacker is installed 🎉 🍰
Using /Projects/Email_platform/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:
Hash: 10dc73570a24c1955534
Version: webpack 3.10.0
Time: 5499ms
                                               Asset       Size  Chunks                    Chunk Names
                 application-10dc73570a24c1955534.js     802 kB       0  [emitted]  [big]  application
    application-11292d2108daafd17885884224f6ce24.css  313 bytes       0  [emitted]         application
             application-10dc73570a24c1955534.js.map     953 kB       0  [emitted]         application
application-11292d2108daafd17885884224f6ce24.css.map  351 bytes       0  [emitted]         application
                                       manifest.json  310 bytes          [emitted]         
[./app/javascript/packs/application.js] ./app/javascript/packs/application.js 1.29 kB {0} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    + 48 hidden modules

ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./app/javascript/components/emails/new/personalisation_box.vue
Module build failed: TypeError: Cannot read property '_init' of undefined (While processing preset: "/Projects/Email_platform/node_modules/vue/dist/vue.runtime.common.js")
    at Vue$3 (/Projects/Email_platform/node_modules/vue/dist/vue.runtime.common.js:4657:8)
    at /Projects/Email_platform/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Projects/Email_platform/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Projects/Email_platform/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Projects/Email_platform/node_modules/babel-loader/lib/index.js:175:20)
 @ ./app/javascript/components/emails/new/personalisation_box.vue 7:0-128 8:0-141
 @ ./app/javascript/packs/application.js

ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./app/javascript/components/emails/index/emails_list/emails_list.vue
Module build failed: TypeError: Cannot read property '_init' of undefined (While processing preset: "/Projects/Email_platform/node_modules/vue/dist/vue.runtime.common.js")
    at Vue$3 (/Projects/Email_platform/node_modules/vue/dist/vue.runtime.common.js:4657:8)
    at /Projects/Email_platform/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Projects/Email_platform/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Projects/Email_platform/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Projects/Email_platform/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Projects/Email_platform/node_modules/babel-loader/lib/index.js:175:20)
 @ ./app/javascript/components/emails/index/emails_list/emails_list.vue 7:0-123 8:0-136
 @ ./app/javascript/packs/application.js
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?sourceMap!node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-c36fda3a","scoped":false,"sourceMap":true}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!app/javascript/components/emails/new/personalisation_box.vue:
       2 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?sourceMap!node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-e66e5b0a","scoped":true,"sourceMap":true}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!app/javascript/components/emails/index/emails_list/emails_list.vue:
       2 modules

[Vue warn]: Vue is a constructor and should be called with the `new` keyword
[Vue warn]: Vue is a constructor and should be called with the `new` keyword
```

**config/wepbacker.yml**
```ruby
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  dev_server:
    host: localhost
    port: 3035
    hmr: true
    https: false

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
```

**.babelrc**
```js
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": "> 1%",
          "uglify": true
        },
        "useBuiltIns": true
      }
    ],
    "vue"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ],
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs"
      ]
    }
  }
}
```

Is there a workaround to fix this issue?

**Comment by gauravtiwari** [comment]
@Loremaster Is it possible you have upgraded other vue related deps as well while upgrading webpacker?

**Comment by Loremaster** [comment]
@gauravtiwari didn't have time to do that yet unfortunately. However I was able to upgrade to `3.2.0` without any issues.

**Comment by gauravtiwari** [comment]
Please could you try 3.3.0
