### ISSUE TITLE
Project name with dot throws ENOENT

### ISSUE THREAD

**Issue by joaumg** [rails/webpacker#1269]
Create a project with a dot in it's name: `rails new foo.bar --api --webpack=vue`
Navigate to foo.bar: `cd foo.bar`
Try to run: `./bin/webpack-dev-server`
The following exception will be raised:

```
/home/joaumg/.rvm/gems/ruby-2.4.1/gems/webpacker-3.2.2/lib/webpacker/dev_server_runner.rb:47:in `exec': No such file or directory - /home/joaumg/Code/foo.bar/node_modules/.bin/webpack-dev-server (Errno::ENOENT)
        from /home/joaumg/.rvm/gems/ruby-2.4.1/gems/webpacker-3.2.2/lib/webpacker/dev_server_runner.rb:47:in `block in execute_cmd'
        from /home/joaumg/.rvm/gems/ruby-2.4.1/gems/webpacker-3.2.2/lib/webpacker/dev_server_runner.rb:46:in `chdir'
        from /home/joaumg/.rvm/gems/ruby-2.4.1/gems/webpacker-3.2.2/lib/webpacker/dev_server_runner.rb:46:in `execute_cmd'
        from /home/joaumg/.rvm/gems/ruby-2.4.1/gems/webpacker-3.2.2/lib/webpacker/dev_server_runner.rb:11:in `run'
        from /home/joaumg/.rvm/gems/ruby-2.4.1/gems/webpacker-3.2.2/lib/webpacker/runner.rb:6:in `run'
        from /home/joaumg/.rvm/gems/ruby-2.4.1/gems/webpacker-3.2.2/exe/webpack-dev-server:8:in `<top (required)>'
        from ./bin/webpack-dev-server:21:in `load'
        from ./bin/webpack-dev-server:21:in `<main>'`
```

https://github.com/rails/webpacker/blob/master/lib/webpacker/dev_server_runner.rb#L47

**Comment by ytbryan** [comment]
Webpacker is designed to work with Rails' view. 

If you wish to use only Rails API as the backend, I think it's best to use vue-cli to generate the front-end.

**Comment by joaumg** [comment]
So shouldn't the rails console throw an error when using `api` and `webpack` ?
