### ISSUE TITLE
delete defaultConfig.extensions: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by doits** [rails/webpacker#1272]
I've a custom env called `staging`. Therefore my webpacker.yml has this entry:

```yml
...

production: &production
  ...

staging:
  <<: *production
```

And I have this symlink:

```
config/webpack/staging.js --> config/webpack/production.js
```

Before 3.2.2, everything was fine on staging. Now I get this on compile:

```
Webpacker is installed 🎉 🍰
Using /var/www/events/demo-a_staging/releases/20180214180938/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:

/var/www/events/demo-a_staging/shared/node_modules/@rails/webpacker/package/config.js:15
  delete defaultConfig.extensions
  ^

TypeError: Cannot convert undefined or null to object
    at Object.<anonymous> (/var/www/events/demo-a_staging/shared/node_modules/@rails/webpacker/package/config.js:15:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/events/demo-a_staging/shared/node_modules/@rails/webpacker/package/rules/babel.js:2:24)
    at Module._compile (module.js:643:30)
```

On development everything works.

Looks like something broke custom envs? `defaultConfig` is `null`?

**Comment by doits** [comment]
oops, just saw #1265, you're already working on it 👍

**Comment by gauravtiwari** [comment]
Please use 3.3.0

**Comment by doits** [comment]
This is still happening for me in 3.3.0

**Comment by Systho** [comment]
related to #1274
