### ISSUE TITLE
On Rails 4.2 webpacker erb extension raises an error

### ISSUE THREAD

**Issue by mdesantis** [rails/webpacker#1382]
Hello,

I tried with a new Rails 4.2.10 webapp (Ruby 2.3.6, webpacker 3.4.1). This is the error (running `bin/webpack`):

```
> bin/webpack
Running via Spring preloader in process 2848
(erb):1:in `<main>': undefined method `javascript_pack_tag' for main:Object (NoMethodError)
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /home/user/Sviluppo/rails-4.2.7.1/rails_demo/node_modules/rails-erb-loader/erb_transformer.rb:19:in `<top (required)>'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	from /home/user/Sviluppo/rails-4.2.7.1/rails_demo/bin/rails:9:in `<top (required)>'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/user/.asdf/installs/ruby/2.3.6/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'
Hash: 1eba15b70b7908847abd
Version: webpack 3.11.0
Time: 792ms
                                  Asset       Size  Chunks             Chunk Names
      hello_erb-ae913103489b1909d8ac.js    3.19 kB       0  [emitted]  hello_erb
    application-6d6fda76e45f26772dbc.js    3.26 kB       1  [emitted]  application
  hello_erb-ae913103489b1909d8ac.js.map    2.49 kB       0  [emitted]  hello_erb
application-6d6fda76e45f26772dbc.js.map    3.19 kB       1  [emitted]  application
                          manifest.json  274 bytes          [emitted]  
   [0] ./app/javascript/packs/application.js 515 bytes {1} [built]
   [1] ./app/javascript/packs/hello_erb.js.erb 425 bytes {0} [built] [failed] [1 error]

ERROR in ./app/javascript/packs/hello_erb.js.erb
Module build failed: Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/home/user/Sviluppo/rails-4.2.7.1/rails_demo/node_modules/rails-erb-loader/index.js:108:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

I have a reproducing script (it uses `asdf` in order to set Ruby version, feel free to change it):

```bash
#!/bin/bash

set -e

mkdir rails-4-2
cd rails-4-2
which asdf >/dev/null 2>&1 && asdf local ruby 2.3.6 || true
echo "gem 'rails', '~> 4.2.0'" >> Gemfile
bundle install
rails new demo
cd demo
echo "gem 'webpacker', '3.4.1'" >> Gemfile
bundle install
bundle exec rake webpacker:install
bundle exec rake webpacker:install:erb
bin/webpack
```

**Comment by gauravtiwari** [comment]
@mdesantis I commented it out earlier but seems like it sneaked back in. Could you please comment out `<%% javascript_pack_tag >` in comment at the top (with two %%) in `hello_erb.js.erb` file?

**Comment by mdesantis** [comment]
Hi @gauravtiwari , it worked, the issue disappeared transforming the `<%= javascript_pack_tag 'hello_erb' %>` in the comment into `<%#= javascript_pack_tag 'hello_erb' %>`. And the reason seems even obvious to me now. Perhaps `hello_erb.js.erb` template should be modified?

**Comment by gauravtiwari** [comment]
Great 👍 yep this was fixed earlier but seems like it got changed later. Could you please make a PR with the fix and I will merge?

**Comment by mdesantis** [comment]
What if I modify the comment into this?

```javascript
// Run this example by adding <%%= javascript_pack_tag 'hello_erb' %> to the head of your layout file,
// like app/views/layouts/application.html.erb. Please take care of removing the extra `%` from `<%%=`:
// we can't write the correct ERB tags here, they would get interpreted.
```

Sounds good? Can you please check if it is a correct sentence? My english is bad :)

**Comment by gauravtiwari** [comment]
@mdesantis Looks about right. If you make a PR we can tweak it there 👍 thank you

**Comment by VRRmax** [comment]
I don't understand why you use **<%%=** instead of **<%#=** which is the standard way for ERB commenting.
**<%%=** looks like a typo.

**Comment by mdesantis** [comment]
@VRRmax if I remember correctly, the reason is that otherwise that line gets interpreted by the generator which would raise an error on Webpacker install

**Comment by thebravoman** [comment]
Just want to let you know the error still exists as of today for a different case

(erb):7:in `<main>': undefined method `javascript_pack_tag' for main:Object (NoMethodError

For those moving from application.js to application.js.erb note that you have this in the application.js.erb

```
/* eslint no-console:0 */
// This file is automatically compiled by Webpack, along with any other files
// present in this directory. You're encouraged to place your actual application logic in
// a relevant structure within app/javascript and only use these pack files to reference
// that code so it'll be compiled.
//
// To reference this file, add <%= javascript_pack_tag 'application' %> to the appropriate
// layout file, like app/views/layouts/application.html.erb
```

and it should be changed to this

```
/* eslint no-console:0 */
// This file is automatically compiled by Webpack, along with any other files
// present in this directory. You're encouraged to place your actual application logic in
// a relevant structure within app/javascript and only use these pack files to reference
// that code so it'll be compiled.
//
// To reference this file, add <%%= javascript_pack_tag 'application' %> to the appropriate
// layout file, like app/views/layouts/application.html.erb

```
