### ISSUE TITLE
Adding webpacker from master, errors when starting  webpack-dev-server due to missing yarn package

### ISSUE THREAD

**Issue by vipulnsward** [rails/webpacker#1483]
```shell
➜  wheel git:(webpacker-impl) ./bin/webpack-dev-server
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
module.js:545
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sward/bigbinary/wheel/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

See https://github.com/bigbinary/wheel/pull/183, where it can be reproduced.

**Comment by cd-rum** [comment]
Umm: `yarn add webpack-cli`? Can confirm that fixes it for me.

**Comment by vipulnsward** [comment]
@cd-rum sure it fixes that. Issue is that we should be taking care of it by default while adding webpack to package.
