### ISSUE TITLE
webpacker:binstubs problem with node 10.0.0

### ISSUE THREAD

**Issue by Jehops** [rails/webpacker#1493]
For a FreeBSD OS package, `RAILS_ENV=production rails --trace webpacker:binstubs; RAILS_ENV=production rails --trace assets:precompile` worked with node version 9.x, however with node 10.0.0 it fails with the output below.  Am I doing something wrong?

```
# OTP_SECRET=x SECRET_KEY_BASE=x RAILS_ENV=production rails --trace webpacker:binstubs
===========================================
 DEPRECATION: The cocaine gem is deprecated. Please upgrade to terrapin. See https://github.com/thoughtbot/terrapin/ for further instructions.
===========================================
** Invoke webpacker:binstubs (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
** Invoke webpacker:check_yarn (first_time)
** Execute webpacker:check_yarn
** Execute webpacker:binstubs
===========================================
 DEPRECATION: The cocaine gem is deprecated. Please upgrade to terrapin. See https://github.com/thoughtbot/terrapin/ for further instructions.
===========================================
Copying binstubs
       exist  bin
   identical  bin/webpack
   identical  bin/webpack-dev-server
# HOME=/wrkdirs/usr/ports/net-im/mastodon/work/mastodon_node-2.4.0 OTP_SECRET=x SECRET_KEY_BASE=x RAILS_ENV=production rails --trace assets:precompile
===========================================
 DEPRECATION: The cocaine gem is deprecated. Please upgrade to terrapin. See https://github.com/thoughtbot/terrapin/ for further instructions.
===========================================
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke yarn:install (first_time)
** Execute yarn:install
yarn install v1.6.0
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
** Execute assets:precompile
** Invoke webpacker:compile (first_time)
** Invoke webpacker:verify_install (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
** Invoke webpacker:check_yarn (first_time)
** Execute webpacker:check_yarn
** Invoke webpacker:check_binstubs (first_time)
** Execute webpacker:check_binstubs
** Execute webpacker:verify_install
Webpacker is installed 🎉 🍰
Using /wrkdirs/usr/ports/net-im/mastodon/work/mastodon-2.4.0rc1/config/webpacker.yml file for setting up webpack paths
** Invoke environment
** Execute webpacker:compile
Compiling…
Compilation failed:
/usr/local/lib/ruby/gems/2.4/gems/webpacker-3.5.3/lib/webpacker/webpack_runner.rb:11:in `exec': No such file or directory - /wrkdirs/usr/ports/net-im/mastodon/work/mastodon-2.4.0rc1/node_modules/.bin/webpack (Errno::ENOENT)
        from /usr/local/lib/ruby/gems/2.4/gems/webpacker-3.5.3/lib/webpacker/webpack_runner.rb:11:in `block in run'
        from /usr/local/lib/ruby/gems/2.4/gems/webpacker-3.5.3/lib/webpacker/webpack_runner.rb:10:in `chdir'
        from /usr/local/lib/ruby/gems/2.4/gems/webpacker-3.5.3/lib/webpacker/webpack_runner.rb:10:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/webpacker-3.5.3/lib/webpacker/runner.rb:6:in `run'
        from ./bin/webpack:15:in `<main>'
```

**Comment by mmlindeboom** [comment]
Same issue

**Comment by guillaumebriday** [comment]
Are you using node 10.0.0 ? 

You need at least [node 10.7.0](https://github.com/rails/webpacker/blob/master/package.json#L11).

Hope this help
