### ISSUE TITLE
UnicodeEncodeError: 'ascii'

### ISSUE THREAD

**Issue by HolyWalley** [rails/webpacker#1498]
On my staging server, I do 
`RUN RAILS_ENV=$RAILS_ENV bundle exec rails assets:precompile`

then I have this:
`....
I, [2018-05-13T11:05:34.225461 #7]  INFO -- : Writing /backend/public/assets/express/lib/application-54796e57a28490936f1735f4c0b5ca55dae380430175927dfd3b9bae93edbc53.js
I, [2018-05-13T11:05:34.225751 #7]  INFO -- : Writing /backend/public/assets/express/lib/application-54796e57a28490936f1735f4c0b5ca55dae380430175927dfd3b9bae93edbc53.js.gz
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/local/lib/python3.5/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python3.5/dist-packages/compose/cli/main.py", line 249, in build
    build_args=build_args)
  File "/usr/local/lib/python3.5/dist-packages/compose/project.py", line 343, in build
    service.build(no_cache, pull, force_rm, build_args)
  File "/usr/local/lib/python3.5/dist-packages/compose/service.py", line 922, in build
    all_events = stream_output(build_output, sys.stdout)
  File "/usr/local/lib/python3.5/dist-packages/compose/progress_stream.py", line 23, in stream_output
    print_output_event(event, stream, is_terminal)
  File "/usr/local/lib/python3.5/dist-packages/compose/progress_stream.py", line 90, in print_output_event
    stream.write("%s%s" % (event['stream'], terminator))
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f389' in position 23: ordinal not in range(128)
`

my staging.js
`const environment = require('./environment')

module.exports = environment.toWebpackConfig()`

from my staging.rb

`config.assets.js_compressor = Uglifier.new(harmony: true)`

**Comment by gauravtiwari** [comment]
Please use the latest RC, and feel free to open a new issue with more details if this is still an issue.
