### ISSUE TITLE
Module build errors when loading scss component from a file in Angular

### ISSUE THREAD

**Issue by aronbohl** [rails/webpacker#1519]
I'm sorry if this is the wrong place to file an issue but I'm new to Angular and Webpacker and I'm not sure where else to look. I'm just trying to set up a basic project from scratch using Rails 5.2, Angular 5+ and Webpacker using the following guide as it seems like the most complete documentation on how to accomplish this.
https://github.com/amitai10/rails-angular-webpacker

The problem is that I believe it's slightly out of date. Some steps are now unnecessary and others have had changes to syntax. I've been able to get everything updated through loading HTML from a file but I can't for the life of me seem to get SCSS loading from a component file (see the section titled "Using a different file for style"). I've added a module declaration and installed the recommended loaders but I get the following error when trying to compile.

```
ERROR in ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./node_modules/to-string-loader/src/to-string.js!./node_modules/css-loader!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js!./app/javascript/hello_angular/app/app.component.scss
Module build failed: 
h1 {
^
      Invalid CSS after "": expected 1 selector or at-rule, was "var result = requir"
      in /home/aron/Desktop/modern_parts/app/javascript/hello_angular/app/app.component.scss (line 1, column 1)
Error: 
h1 {
^
      Invalid CSS after "": expected 1 selector or at-rule, was "var result = requir"
      in /home/aron/Desktop/modern_parts/app/javascript/hello_angular/app/app.component.scss (line 1, column 1)
    at options.error (/home/aron/Desktop/modern_parts/node_modules/node-sass/lib/index.js:291:26)
 @ ./app/javascript/hello_angular/app/app.component.scss 2:14-434
 @ ./app/javascript/hello_angular/app/app.component.ts
 @ ./app/javascript/hello_angular/app/app.module.ts
 @ ./app/javascript/hello_angular/index.ts
 @ ./app/javascript/packs/hello_angular.js
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/hello_angular.js

ERROR in ./app/javascript/hello_angular/app/app.component.scss
Module build failed: ModuleBuildError: Module build failed: 
h1 {
^
      Invalid CSS after "": expected 1 selector or at-rule, was "var result = requir"
      in /home/aron/Desktop/modern_parts/app/javascript/hello_angular/app/app.component.scss (line 1, column 1)
    at runLoaders (/home/aron/Desktop/modern_parts/node_modules/webpack/lib/NormalModule.js:195:19)
    at /home/aron/Desktop/modern_parts/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/aron/Desktop/modern_parts/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/aron/Desktop/modern_parts/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/aron/Desktop/modern_parts/node_modules/sass-loader/lib/loader.js:76:13)
    at Object.done [as callback] (/home/aron/Desktop/modern_parts/node_modules/neo-async/async.js:7974:18)
    at options.error (/home/aron/Desktop/modern_parts/node_modules/node-sass/lib/index.js:294:32)
 @ ./app/javascript/hello_angular/app/app.component.scss
 @ ./app/javascript/hello_angular/app/app.component.ts
 @ ./app/javascript/hello_angular/app/app.module.ts
 @ ./app/javascript/hello_angular/index.ts
 @ ./app/javascript/packs/hello_angular.js
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/hello_angular.js
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--2-2!node_modules/postcss-loader/lib/index.js??ref--2-3!node_modules/sass-loader/lib/loader.js??ref--2-4!node_modules/to-string-loader/src/to-string.js!node_modules/css-loader/index.js!node_modules/resolve-url-loader/index.js!node_modules/sass-loader/lib/loader.js!app/javascript/hello_angular/app/app.component.scss:
       [0] ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./node_modules/to-string-loader/src/to-string.js!./node_modules/css-loader!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js!./app/javascript/hello_angular/app/app.component.scss 254 bytes {0} [built] [failed] [1 error]
    
    ERROR in ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./node_modules/to-string-loader/src/to-string.js!./node_modules/css-loader!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js!./app/javascript/hello_angular/app/app.component.scss
    Module build failed: 
    h1 {
    ^
          Invalid CSS after "": expected 1 selector or at-rule, was "var result = requir"
          in /home/aron/Desktop/modern_parts/app/javascript/hello_angular/app/app.component.scss (line 1, column 1)
    Error: 
    h1 {
    ^
          Invalid CSS after "": expected 1 selector or at-rule, was "var result = requir"
          in /home/aron/Desktop/modern_parts/app/javascript/hello_angular/app/app.component.scss (line 1, column 1)
        at options.error (/home/aron/Desktop/modern_parts/node_modules/node-sass/lib/index.js:291:26)

```

I'm wondering if there are any official, up-to-date docs on getting this running. I've been struggling with this for a while now and would be eternally grateful if someone could point me in the right direction. I'm happy to provide more info if needed. Thanks

**Comment by abratashov** [comment]
The same issue. So, i'm using pure Rails SCSS with the component approach:
```
hello-angular {
  h1 {
    color: red;
  }
}
```

**Comment by ace90** [comment]
I have the same issue here. Did you solve this error?

**Comment by abratashov** [comment]
I added CSS code (that mentioned above) to "app/assets/stylesheets/hello-angular.css" and Rails loads it.

**Comment by doutatsu** [comment]
Same issue here

**Comment by cranderveldt** [comment]
For anyone still looking for an answer to this, my issue ended up being an unrelated config in my environment.js. I figured this out by setting up a fresh repo for angular + webpacker + component styles. Here's the repo for comparison if you're still seeing issues with this: https://github.com/cranderveldt/webpacker-angular-component-styles

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
