### ISSUE TITLE
Module build failed, Unknown plugin "@babel/plugin-syntax-dynamic-import" after webpacker:install:vue

### ISSUE THREAD

**Issue by lbrito1** [rails/webpacker#1565]
I'm in the process of migrating from asset pipeline in a Rails 5.1.4 project. I'm using webpacker on master:

```
more Gemfile.lock | grep webpacker
  remote: https://github.com/rails/webpacker.git
    webpacker (4.0.0.pre.pre.2)
  webpacker!
```

I've ran `bundle exec rails webpacker:install:vue`, output seems fine:

```
root@b2cc4aa438e1:/opt/rails# bundle exec rails webpacker:install:vue
Webpacker is installed 🎉 🍰
Using /opt/rails/config/webpacker.yml file for setting up webpack paths
/opt/rails/config/environments/development.rb:140: warning: already initialized constant REDIS_HOST_SIDEKIQ
/opt/rails/config/application.rb:115: warning: previous definition of REDIS_HOST_SIDEKIQ was here
Copying vue loader to config/webpack/loaders
   identical  config/webpack/loaders/vue.js
Adding vue loader plugin to config/webpack/environment.js
      insert  config/webpack/environment.js
      insert  config/webpack/environment.js
Adding vue loader to config/webpack/environment.js
      insert  config/webpack/environment.js
      insert  config/webpack/environment.js
Updating webpack paths to include .vue file extension
      insert  config/webpacker.yml
Copying the example entry file to /opt/rails/app/javascript/packs
   identical  app/javascript/packs/hello_vue.js
Copying Vue app file to /opt/rails/app/javascript/packs
   identical  app/javascript/app.vue
Installing all Vue dependencies
         run  yarn add vue vue-loader@next vue-template-compiler from "."
yarn add v1.7.0
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
Couldn't find any versions for "vue-loader" that matches "next"
? Please choose a version of "vue-loader" from this list: 15.2.4
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning "@rails/webpacker > webpack-assets-manifest@3.0.1" has unmet peer dependency "webpack-sources@^1.0".
warning " > webpack-dev-server@3.1.4" has unmet peer dependency "webpack@^4.0.0-beta.1".
warning "webpack-dev-server > webpack-dev-middleware@3.1.3" has unmet peer dependency "webpack@^4.0.0".
warning " > vue-loader@15.2.4" has unmet peer dependency "css-loader@*".
[4/4] Building fresh packages...

success Saved 3 new dependencies.
info Direct dependencies
├─ vue-loader@15.2.4
├─ vue-template-compiler@2.5.16
└─ vue@2.5.16
info All dependencies
├─ vue-loader@15.2.4
├─ vue-template-compiler@2.5.16
└─ vue@2.5.16
warning No license field
Done in 6.43s.
Webpacker now supports Vue.js 🎉
```

I tried adding `javascript_pack_tag 'hello_vue'` on layout.html as instructed in `hello_vue.js`. This is the output I get in the js console:

```
Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "@babel/plugin-syntax-dynamic-import" specified in "/opt/rails/.babelrc" at 0, attempted to resolve relative to "/opt/rails"
    at :3000/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
    at Array.map (<anonymous>)
    at Function.normalisePlugins (:3000/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158)
    at OptionManager.mergeOptions (:3000/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234)
    at OptionManager.init (:3000/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368)
    at File.initOptions (:3000/opt/rails/node_modules/babel-core/lib/transformation/file/index.js:212)
    at new File (:3000/opt/rails/node_modules/babel-core/lib/transformation/file/index.js:135)
    at Pipeline.transform (:3000/opt/rails/node_modules/babel-core/lib/transformation/pipeline.js:46)
    at transpile (:3000/opt/rails/node_modules/babel-loader/lib/index.js:50)
    at :3000/opt/rails/node_modules/babel-loader/lib/fs-cache.js:118
    at ReadFileContext.callback (:3000/opt/rails/node_modules/babel-loader/lib/fs-cache.js:31)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (:3000/fs.js:420)
    at :3000/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
    at Array.map (<anonymous>)
    at Function.normalisePlugins (:3000/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158)
    at OptionManager.mergeOptions (:3000/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234)
    at OptionManager.init (:3000/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368)
    at File.initOptions (:3000/opt/rails/node_modules/babel-core/lib/transformation/file/index.js:212)
    at new File (:3000/opt/rails/node_modules/babel-core/lib/transformation/file/index.js:135)
    at Pipeline.transform (:3000/opt/rails/node_modules/babel-core/lib/transformation/pipeline.js:46)
    at transpile (:3000/opt/rails/node_modules/babel-loader/lib/index.js:50)
    at :3000/opt/rails/node_modules/babel-loader/lib/fs-cache.js:118
    at ReadFileContext.callback (:3000/opt/rails/node_modules/babel-loader/lib/fs-cache.js:31)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (:3000/fs.js:420)
    at Object../app/javascript/packs/hello_vue.js (bootstrap:83)
    at __webpack_require__ (bootstrap:19)
    at ./app/javascript/packs/hello_vue.js (bootstrap:83)
    at bootstrap:83
```

I also get the same error when running `webpacker:compile`:

```
root@b2cc4aa438e1:/opt/rails# bundle exec rails webpacker:compile
Webpacker is installed 🎉 🍰
Using /opt/rails/config/webpacker.yml file for setting up webpack paths
/opt/rails/config/environments/development.rb:140: warning: already initialized constant REDIS_HOST_SIDEKIQ
/opt/rails/config/application.rb:115: warning: previous definition of REDIS_HOST_SIDEKIQ was here
Compiling…
Compilation failed:

Hash: 02f92e4f8226954802ff
Version: webpack 4.12.0
Time: 539ms
Built at: 2018-06-11 02:52:51
 4 assets
[0] ./app/javascript/packs/hello_vue.js 1.33 KiB {0} [built] [failed] [1 error]
[1] ./app/javascript/packs/application.js 1.33 KiB {1} [built] [failed] [1 error]

ERROR in ./app/javascript/packs/application.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "@babel/plugin-syntax-dynamic-import" specified in "/opt/rails/.babelrc" at 0, attempted to resolve relative to "/opt/rails"
    at /opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/opt/rails/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/opt/rails/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/opt/rails/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/opt/rails/node_modules/babel-loader/lib/index.js:50:20)
    at /opt/rails/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/opt/rails/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

ERROR in ./app/javascript/packs/hello_vue.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "@babel/plugin-syntax-dynamic-import" specified in "/opt/rails/.babelrc" at 0, attempted to resolve relative to "/opt/rails"
    at /opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/opt/rails/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/opt/rails/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/opt/rails/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/opt/rails/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/opt/rails/node_modules/babel-loader/lib/index.js:50:20)
    at /opt/rails/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/opt/rails/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

Is there some additional step I should take after running webpacker:install:vue?

**Comment by gauravtiwari** [comment]
Have you installed webpacker from the git repo? `yarn add https://github.com/rails/webpacker.git`

**Comment by lbrito1** [comment]
Excellent! After running `yarn add https://github.com/rails/webpacker/tarball/master` (for some reason the usual .git raised an `Could not resolve host: github.com` error in yarn), I can now run the Vue hello world without error.

@gauravtiwari  Is this maybe a step that should be somewhere on the readme, or was it only necessary because I updated the gem?
