### ISSUE TITLE
Issues with resolve-url-loader

### ISSUE THREAD

**Issue by kevinjbayer** [rails/webpacker#1570]
I'm attempting to integrate Tailwind via Webpacker. It seems to be compiling ok, but I'm getting the following warnings upon webpack building:

```
09:02:28 webpack.1   | WARNING in ./node_modules/css-loader??ref--4-2!./node_modules/postcss-loader/lib??ref--4-3!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js??ref--4-5!./app/javascript/css/application.css
09:02:28 webpack.1   | (Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
09:02:28 webpack.1   |   /Users/kevin/dev/wtc/app/javascript/css/application.css:28:11: missing '}'
09:02:28 webpack.1   |   at error (/Users/kevin/dev/wtc/node_modules/css/lib/parse/index.js:62:15)
09:02:28 webpack.1   |  @ ./app/javascript/css/application.css 4:14-264
09:02:28 webpack.1   |  @ ./app/javascript/packs/application.js
09:02:28 webpack.1   |  @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./app/javascript/packs/application.js
```

```
09:02:28 webpack.1   |     WARNING in ./node_modules/css-loader??ref--4-2!./node_modules/postcss-loader/lib??ref--4-3!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js??ref--4-5!./app/javascript/css/application.css
09:02:28 webpack.1   |     (Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
09:02:28 webpack.1   |       /Users/kevin/dev/wtc/app/javascript/css/application.css:28:11: missing '}'
09:02:28 webpack.1   |       at error (/Users/kevin/dev/wtc/node_modules/css/lib/parse/index.js:62:15)
```

There were some solutions to this issue for other webpack builds [here](https://github.com/tailwindcss/tailwindcss/issues/48#issuecomment-348286341). Maybe this is just something with my setup and I realize Webpacker can't support a config for every library, but is there a way to add an option to resolve-url-loader without forking the project?

Did a quick try of upgrading to webpacker 4 and issue was still present.

Tagging @excid3 per his request to follow the issue.

**Comment by kevinjbayer** [comment]
I did a clean app with Rails 5.2 and compared the files. I'm guessing my webpacker files were just older. To at least temporarily resolve the issue, I was able to comment out 'resolve-url-loader' in /config/webpack/loaders/sass.js.
