### ISSUE TITLE
assets:precompile Uglifier::SyntaxError

### ISSUE THREAD

**Issue by markspolakovs** [rails/webpacker#1590]
Upon running `RAILS_ENV=production rake assets:precompile`, I get this:

```
C:\Code\vlt\home>rake assets:precompile
{"error"=>{"message"=>"Unexpected character '#'", "filename"=>"null", "line"=>18017, "col"=>0, "pos"=>541881}}
rake aborted!
Uglifier::Error: Unexpected character '#'
C:/Users/Marks/scoop/persist/ruby/gems/gems/uglifier-4.1.12/lib/uglifier.rb:235:in `parse_result'
C:/Users/Marks/scoop/persist/ruby/gems/gems/uglifier-4.1.12/lib/uglifier.rb:216:in `run_uglifyjs'
C:/Users/Marks/scoop/persist/ruby/gems/gems/uglifier-4.1.12/lib/uglifier.rb:168:in `compile'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/compressing.rb:65:in `block in js_compressor='
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/legacy_proc_processor.rb:31:in `call'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
C:/Users/Marks/scoop/persist/ruby/gems/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
C:/Users/Marks/scoop/apps/ruby/current/gems/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

When inserting `puts result` before line 234 in `uglifier.rb`, I get this:

`{"error"=>{"message"=>"Unexpected character '#'", "filename"=>"null", "line"=>18017, "col"=>0, "pos"=>541881}}`, however inspecting the source (with a `puts source`) doesn't give anywhere near 18,000 lines.

Bundler and yarn files are in this gist: https://gist.github.com/markspolakovs/3e3d6b2a54fe9cca83a4dac2a4cb9db0

**Comment by gauravtiwari** [comment]
@markspolakovs Webpacker already does uglification. What happens if you disable uglification from `production.rb`?

**Comment by markspolakovs** [comment]
Yeah, that does appear to fix it. Should I report this as a Uglifier bug then?
