### ISSUE TITLE
yarn node_modules not in project directory -> can't find @rails/webpacker module

### ISSUE THREAD

**Issue by Piioo** [rails/webpacker#1606]
Hello,

we have in our project a .yarnrc file with `--modules-folder` which defines the node_modules folder outside of the project.
Most of the problems with other packages installed goes away with defining the `NODE_PATH` to the node_modules folder outside of the project.

@rails/webpacker don't work with this solution.

When we run `bundle exec rails assets:precompile` we got

````
Webpacker is installed 🎉 🍰
Using /builds/proofler/proofler/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '@rails/webpacker'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/builds/proofler/proofler/config/webpack/environment.js:1:87)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
````

How may we defined the correct location of node_modules for webpacker?

**Comment by jfahrer** [comment]
@Piioo Did you ever figure out how to define the location of node_modules with webpacker?

**Comment by Piioo** [comment]
You have to set the node_modules path in:
NODE_PATH
.yarnrc

**Comment by josephsiefers** [comment]
Looks like there's a problem with webpacker's use of `yarn bin`:
https://github.com/rails/webpacker/blob/5b481bd710211b6a517da72f30cc3ec76fb35519/lib/webpacker/runner.rb#L13

`yarn bin` is not respecting the .yarnrc setting for --modules-folder ?
https://github.com/yarnpkg/yarn/issues/6918

**Comment by josephsiefers** [comment]
Update: yarnpkg/yarn#6918 is now fixed so this should work now I think.
