### ISSUE TITLE
problems deplying to Heroku

### ISSUE THREAD

**Issue by erniux** [rails/webpacker#1631]
Hello, After implement Webpacker on Ruby on Rails, my deploy to heroku is throughing this error:

```
remote:        Bundle complete! 23 Gemfile dependencies, 78 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (3.05s)
remote:        Cleaning up the bundler cache.
remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Removing cocoon (1.2.11)
remote:        Removing aws-sdk-core (3.22.1)
remote:        Removing mini_magick (4.8.0)
remote:        Removing jmespath (1.4.0)
remote:        Removing carrierwave (1.2.3)
remote:        Removing mime-types-data (3.2016.0521)
remote:        Removing aws-sdk-s3 (1.16.0)
remote:        Removing aws-sdk-kms (1.6.0)
remote:        Removing carrierwave-aws (1.3.0)
remote:        Removing aws-eventstream (1.0.1)
remote:        Removing dotenv-rails (2.5.0)
remote:        Removing aws-partitions (1.95.0)
remote:        Removing mime-types (3.1)
remote:        Removing dotenv (2.5.0)
remote:        Removing aws-sigv4 (1.0.3)
remote:        The latest bundler is 1.16.3, but you are currently running 1.15.2.
remote:        To update, run `gem install bundler`
remote: -----> Installing node-v8.10.0-linux-x64
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        NoMethodError: undefined method `webpacker' for #<Rails::Application::Configuration:0x00000002b08608>
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/railtie/configuration.rb:97:in `method_missing
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/config/environments/production.rb:3:in `block in <main>'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/railtie.rb:216:in `instance_eval'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/railtie.rb:216:in `configure'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/config/environments/production.rb:1:in `<main>'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/engine.rb:602:in `block (2 levels) in <class:Engine>'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/engine.rb:601:in `each'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/engine.rb:601:in `block in <class:Engine>'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `each'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/config/environment.rb:5:in `<main>'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/application.rb:337:in `require_environment!'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/railties-5.2.0/lib/rails/application.rb:520:in `block in run_tasks_blocks'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
remote:        /tmp/build_476e55d8d91f426b35c44efa35626be9/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to aframex-cotiza.
remote: 
To https://git.heroku.com/aframex-cotiza.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/aframex-cotiza.git'
```

**Comment by gauravtiwari** [comment]
@erniux Do you have `webpacker` included in your gemfile? Also, make sure it's available in all environments.

**Comment by erniux** [comment]
thanks @gauravtiwari I had, but now i Uninstall it doing this: 

remove .bin/webpackor run bundle exec rake rails:update:bin
remove config/webpacker.yml
remove config/webpack
remove app/javascripts
remove config.webpacker.check_yarn_integrity = false from config/{development, test, production}.rb
verify that you don't have webpacker in your gemfile and run bundle  install or bundle clean
imho

turned off machine and turned on again, erased the app existing on heroku and even it is sending me the same error message.

**Comment by ace-subido** [comment]
What are the buildpacks for the dyno it's being launched on?

**Comment by twnaing** [comment]
Make sure your application config does not using webpacker. In my case, there was a config for webpacker in `config\environments\production.rb`

    config.webpacker.check_yarn_integrity = false

I had to comment out and all are fine now.
