### ISSUE TITLE
bin/webpack broken since last commit

### ISSUE THREAD

**Issue by n-rodriguez** [rails/webpacker#1688]
Hi there!

It seems that the `bin/webpack` command is broken since last commit :

```sh
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ bin/webpack
Traceback (most recent call last):
	7: from bin/webpack:17:in `<main>'
	6: from bin/webpack:17:in `chdir'
	5: from bin/webpack:18:in `block in <main>'
	4: from /home/nicolas/.rvm/gems/ruby-2.5.1/bundler/gems/webpacker-1142702edafd/lib/webpacker/runner.rb:6:in `run'
	3: from /home/nicolas/.rvm/gems/ruby-2.5.1/bundler/gems/webpacker-1142702edafd/lib/webpacker/webpack_runner.rb:12:in `run'
	2: from /home/nicolas/.rvm/gems/ruby-2.5.1/bundler/gems/webpacker-1142702edafd/lib/webpacker/webpack_runner.rb:12:in `chdir'
	1: from /home/nicolas/.rvm/gems/ruby-2.5.1/bundler/gems/webpacker-1142702edafd/lib/webpacker/webpack_runner.rb:13:in `block in run'
/home/nicolas/.rvm/gems/ruby-2.5.1/bundler/gems/webpacker-1142702edafd/lib/webpacker/webpack_runner.rb:13:in `exec': No such file or directory - /home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/.bin (Errno::ENOENT)
/webpack
```

After some debugging it seems that there is a trailing `\n`somewhere in the Webpack command :

```sh
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ bin/webpack
---
- |-
  /home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/.bin
  /webpack
- "--config"
- "/home/nicolas/PROJECTS/CONCERTO/concerto/config/webpack/development.js"
Traceback (most recent call last):
	7: from bin/webpack:17:in `<main>'
	6: from bin/webpack:17:in `chdir'
	5: from bin/webpack:18:in `block in <main>'
	4: from /home/nicolas/.rvm/gems/ruby-2.5.1/bundler/gems/webpacker-1142702edafd/lib/webpacker/runner.rb:6:in `run'
	3: from /home/nicolas/.rvm/gems/ruby-2.5.1/bundler/gems/webpacker-1142702edafd/lib/webpacker/webpack_runner.rb:12:in `run'
	2: from /home/nicolas/.rvm/gems/ruby-2.5.1/bundler/gems/webpacker-1142702edafd/lib/webpacker/webpack_runner.rb:12:in `chdir'
	1: from /home/nicolas/.rvm/gems/ruby-2.5.1/bundler/gems/webpacker-1142702edafd/lib/webpacker/webpack_runner.rb:13:in `block in run'
/home/nicolas/.rvm/gems/ruby-2.5.1/bundler/gems/webpacker-1142702edafd/lib/webpacker/webpack_runner.rb:13:in `exec': No such file or directory - /home/nicolas/PROJECTS/CONCERTO/concerto/node_modules/.bin (Errno::ENOENT)
/webpack
```

Thank you!

**Comment by n-rodriguez** [comment]
The culprit : https://github.com/rails/webpacker/commit/1142702edafde67e2b8947cfeaa32e0a66ec8965#diff-3cabd9705445f8bfd7d430d71b59068bR13
