### ISSUE TITLE
Rails webpacker throwing error - "Module build failed: Error: ENOENT: no such file or directory, open '/Users/aruprakshit/elm-apps/elm-rails-todo/elm.json'"

### ISSUE THREAD

**Issue by aruprakshit** [rails/webpacker#1792]
I just created a new Rails app. When I try to start webpack dev server, I get the error as you see below.

```sh
elm-rails-todo$ bin/webpack-dev-server
(node:21015) ExperimentalWarning: The fs.promises API is experimental
Project is running at http://localhost:3035/
webpack output is served from /packs/
Content not from webpack is served from /Users/aruprakshit/elm-apps/elm-rails-todo/public/packs
404s will fallback to /index.html
Hash: abb07302955e58fa0f32
Version: webpack 3.12.0
Time: 765ms
                                  Asset       Size  Chunks                    Chunk Names
          todos-cad1383367fe4b838ed4.js     332 kB       0  [emitted]  [big]  todos
    application-bb5afb7f15ffa7af0cd0.js     331 kB       1  [emitted]  [big]  application
      todos-cad1383367fe4b838ed4.js.map     383 kB       0  [emitted]         todos
application-bb5afb7f15ffa7af0cd0.js.map     383 kB       1  [emitted]         application
                          manifest.json  258 bytes          [emitted]
   [2] (webpack)-dev-server/client?http://localhost:3035 7.93 kB {0} {1} [built]
   [3] ./node_modules/url/url.js 23.3 kB {0} {1} [built]
   [4] ./node_modules/node-libs-browser/node_modules/punycode/punycode.js 14.7 kB {0} {1} [built]
  [10] ./node_modules/strip-ansi/index.js 161 bytes {0} {1} [built]
  [12] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {0} {1} [built]
  [13] (webpack)-dev-server/client/socket.js 1.08 kB {0} {1} [built]
  [14] ./node_modules/sockjs-client/dist/sockjs.js 181 kB {0} {1} [built]
  [15] (webpack)-dev-server/client/overlay.js 3.67 kB {0} {1} [built]
  [20] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} {1} [built]
  [22] (webpack)/hot/emitter.js 77 bytes {0} {1} [built]
  [24] multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/application.js 40 bytes {1} [built]
  [25] ./app/javascript/packs/application.js 515 bytes {1} [built]
  [26] multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/todos.js 40 bytes {0} [built]
  [27] ./app/javascript/packs/todos.js 367 bytes {0} [built]
  [28] ./app/javascript/Main.elm 464 bytes {0} [built] [failed] [1 error]
    + 14 hidden modules

ERROR in ./app/javascript/Main.elm
Module build failed: Error: ENOENT: no such file or directory, open '/Users/aruprakshit/elm-apps/elm-rails-todo/elm.json'
    at Object.fs.openSync (fs.js:559:3)
    at Object.fs.readFileSync (fs.js:465:33)
    at filesToWatch (/Users/aruprakshit/elm-apps/elm-rails-todo/node_modules/elm-webpack-loader/index.js:80:21)
    at Object.module.exports (/Users/aruprakshit/elm-apps/elm-rails-todo/node_modules/elm-webpack-loader/index.js:131:18)
 @ ./app/javascript/packs/todos.js 5:0-26
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/todos.js
webpack: Failed to compile.
```

I am on MacOS, and I am using:

-----
elm-rails-todo (master)$ rails -vMy
Rails 5.2.1
elm-rails-todo (master)$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
elm-rails-todo (master)$
-----

My code is present on github as [elm-rails-todo](https://github.com/aruprakshit/elm-rails-todo) .

**Comment by aruprakshit** [comment]
Just tried to create a brand new app again with the command as `rails new elm-rails-todo -d postgresql --webpack=elm`, and got this error.

```sh
         run  yarn run elm package install -- --yes from "."
yarn run v1.6.0
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ /Users/aruprakshit/elm-apps/elm-rails-todo/node_modules/.bin/elm package install --yes
There is no package command.

Run `elm` with no arguments to get more hints.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Updating webpack paths to include .elm file extension
      insert  config/webpacker.yml
Updating Elm source location
        gsub  elm-package.json
rails aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/aruprakshit/elm-apps/elm-rails-todo/elm-package.json
```

It seems webpacker has a bug with Elm integration.

**Comment by gauravtiwari** [comment]
Feel free to make a PR or try Webpacker 4 RC.

**Comment by rossta** [comment]
Closing due to inactivity but feel free to reopen if you have more info.
