### ISSUE TITLE
Heroku compilation error: Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by r1ckhenry** [rails/webpacker#1793]
I've currently got a rails app that is deployed on heroku. I am getting an error during webpacker compiling which I don't get locally. Error:

```
remote:        ERROR in ./app/javascript/packs/application.jsx
remote:        Module build failed: Error: Couldn't find preset "es2015" relative to directory "/tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a"
remote:            at /tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
remote:            at Array.map (<anonymous>)
remote:            at OptionManager.resolvePresets (/tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
remote:            at OptionManager.mergePresets (/tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
remote:            at OptionManager.mergeOptions (/tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
remote:            at OptionManager.init (/tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
remote:            at File.initOptions (/tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a/node_modules/babel-core/lib/transformation/file/index.js:212:65)
remote:            at new File (/tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a/node_modules/babel-core/lib/transformation/file/index.js:135:24)
remote:            at Pipeline.transform (/tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
remote:            at transpile (/tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a/node_modules/babel-loader/lib/index.js:50:20)
remote:            at /tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a/node_modules/babel-loader/lib/fs-cache.js:118:18
remote:            at ReadFileContext.callback (/tmp/build_f441edfc6f77f6b8dc7bef6a0868c55a/node_modules/babel-loader/lib/fs-cache.js:31:21)
remote:            at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

The correct babel preset is in dev-dependencies in package.json and is referenced in babelrc:

```
{
  "presets": [
    [
      "es2015",
      {
        "modules": false,
        "targets": {
          "browsers": ["last 2 versions", "> 1%"],
          "uglify": true
        },
        "useBuiltIns": true
      }
    ],
    "react"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ],
  "env": {
    "test": {
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  }
}
```

Any thoughts?

**Comment by r1ckhenry** [comment]
The fix for this was due to dependencies in package json. I think Webpacker 3 doesn't depend on presets in devDependencies but rather deps. Therefore, moving them from devDeps to deps worked for me. Maybe someone could confirm that is best course of action?
