### ISSUE TITLE
Error supporting Elm 0.19 webpacker somehow injecting 0.18 even though 0.19 is installed.

### ISSUE THREAD

**Issue by koctya** [rails/webpacker#1795]
WEbpacker is throwing errors for 0.19, even though it is installed;
I'm still getting this error in ver 3.5.5 even though the comments in 
https://github.com/rails/webpacker/issues/1668 stated the 3.5.x stable was patched for 0.19.
```
ERROR in ./app/javascript/packs/Api/Union.elm
Module build failed: Error: Compiled JS from the Elm compiler is not valid. You must use the Elm 0.19 compiler.
    at inject (/Users/kurtlandrus/code/mcs/cost_model/node_modules/elm-hot/src/inject.js:35:15)
    at Object.module.exports (/Users/kurtlandrus/code/mcs/cost_model/node_modules/elm-hot-webpack-loader/src/index.js:4:12)
```
I only have version 0.19 installed;
```✗ elm --version
0.19.0
✗ bundle list webpacker
/Users/kurtlandrus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/webpacker-3.5.5
```
my env;
```
✗ rails about
About your application's environment
Rails version             5.2.1
Ruby version              2.3.1-p112 (x86_64-darwin15)
RubyGems version          2.5.1
Rack version              2.0.5
JavaScript Runtime        Node.js (V8)
Middleware                Webpacker::DevServerProxy, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, RequestStore::Middleware, ActionDispatch::RemoteIp, Sprockets::Rails::QuietAssets, Rails::Rack::Logger, ActionDispatch::ShowExceptions, WebConsole::Middleware, ActionDispatch::DebugExceptions, BetterErrors::Middleware, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActiveRecord::Migration::CheckPending, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper, Warden::Manager
Environment               development
Database adapter          mysql2
```

**Comment by koctya** [comment]
```
✗ rails webpacker:info
Ruby: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
Rails: 5.2.1
Webpacker: 3.5.5
Node: v11.0.0
Yarn: 1.12.1

@rails/webpacker: 
cost_model@ /Users/kurtlandrus/code/mcs/cost_model
└── (empty)

Is bin/webpack present?: true
Is bin/webpack-dev-server present?: true
Is bin/yarn present?: true
```

**Comment by vnhnhm** [comment]
Is there a solution for this? ping @koctya

**Comment by ponchik** [comment]
I've ended up working with elm without webpack(er). New beta 0.19.1 compiles blazing fast!

**Comment by guillaumebriday** [comment]
I think this issue is not relevant anymore I guess

Can this issue be closed ?
