### ISSUE TITLE
Error with installation: "No LOCATION value given. Please set LOCATION either as path to a file or a URL"

### ISSUE THREAD

**Issue by echan00** [rails/webpacker#1796]
`bundle exec rails webpacker:install`

```
RAILS_ENV=development environment is not defined in config/webpacker.yml, falling back to production environment
rails aborted!
No LOCATION value given. Please set LOCATION either as path to a file or a URL
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/tasks/framework.rake:8:in `block (2 levels) in <top (required)>'
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
/Users/erikchan/Workspace/nda-ai/translatefx/bin/rails:9:in `require'
/Users/erikchan/Workspace/nda-ai/translatefx/bin/rails:9:in `<top (required)>'
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/Users/erikchan/.rvm/gems/ruby-2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/erikchan/Workspace/nda-ai/translatefx/bin/spring:15:in `require'
/Users/erikchan/Workspace/nda-ai/translatefx/bin/spring:15:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'
Tasks: TOP => app:template
(See full trace by running task with --trace)
```

No entirely sure what is the issue here. I tried adding a config/webpacker.yml but still no luck.
I'm using Rails 5.1.6

**Comment by gauravtiwari** [comment]
@echan00 Please try restarting or disabling spring altogether. Seems to work fine for me.
