### ISSUE TITLE
Cannot define multiple 'included' blocks for a Concern

### ISSUE THREAD

**Issue by josemigallas** [rails/webpacker#1920]
### ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern

I'm trying to upgrade my webpacker following the [steps in Readme](https://github.com/rails/webpacker#upgrading) but when I run `webpack:binstubs` I see this error.

I found similar issues but couldn't get rid of my own:
- https://github.com/Shopify/bootsnap/issues/75
- https://stackoverflow.com/a/24486561/5466997

The branch where this happens: https://github.com/3scale/porta/tree/feature/update_and_cleanup_babel

<details><summary><b>Full Stacktrace</b></summary>

```bash
$ bundle exec rake webpacker:binstubs --trace
** Invoke webpacker:binstubs (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
** Invoke webpacker:check_yarn (first_time)
** Execute webpacker:check_yarn
** Execute webpacker:binstubs
Running via Spring preloader in process 62570
rake aborted!
ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/concern.rb:126:in `included'
/Users/jgallaso/Projects/3scale/porta/lib/system/database.rb:133:in `<module:Definitions>'
/Users/jgallaso/Projects/3scale/porta/lib/system/database.rb:130:in `<module:Database>'
/Users/jgallaso/Projects/3scale/porta/lib/system/database.rb:6:in `<module:System>'
/Users/jgallaso/Projects/3scale/porta/lib/system/database.rb:5:in `<main>'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/Users/jgallaso/Projects/3scale/porta/lib/tasks/db/procedures.rake:3:in `<main>'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/railties-4.2.9/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/railties-4.2.9/lib/rails/engine.rb:658:in `each'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/railties-4.2.9/lib/rails/engine.rb:658:in `run_tasks_blocks'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/railties-4.2.9/lib/rails/application.rb:452:in `run_tasks_blocks'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/railties-4.2.9/lib/rails/engine.rb:453:in `load_tasks'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `public_send'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `method_missing'
/Users/jgallaso/Projects/3scale/porta/Rakefile:9:in `<main>'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/rake-12.3.2/exe/rake:27:in `<main>'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jgallaso/.rvm/gems/ruby-2.3.6/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
(See full trace by running task with --trace)
```

</details>

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
