### ISSUE TITLE
TypeError: Cannot read property 'minify' of undefined

### ISSUE THREAD

**Issue by pratik0809** [rails/webpacker#1925]
When I run `NODE_ENV=test ./bin/webpack` or `bundle exec rake assets:precompile`, I get a strange error: 

```
Hash: 6d7c675f8cc38150ae47
Version: webpack 4.29.0
Time: 18830ms
Built at: 02/02/2019 4:42:43 PM
 11 assets
Entrypoint application = css/application-e962ef37.css js/application-163fb1a040f40ce8c3f3.js
Entrypoint connect = js/connect-dffe95978f2b88dbc94f.js
Entrypoint dashboard = css/dashboard-6beb0ac2.css js/dashboard-38a738566d4cf0b2ae68.js
Entrypoint images = js/images-3713672acbf2473e0429.js
Entrypoint users = css/users-6beb0ac2.css js/users-552371689c0c8dedf8da.js
  [3] ./node_modules/apollo-link/lib/bundle.esm.js + 1 modules 7.74 KiB {2} {4} [built]
      |    2 modules
 [17] ./node_modules/apollo-client/index.js + 12 modules 74.2 KiB {2} {4} [built]
      |    13 modules
 [30] (webpack)/buildin/module.js 552 bytes {0} {1} {2} {4} [built]
 [47] (webpack)/buildin/harmony-module.js 631 bytes {2} {4} [built]
 [64] ./frontend/src/stylesheets/theme.js 257 bytes {2} {4} [built]
 [66] ./node_modules/apollo-boost/lib/index.js + 14 modules 68.6 KiB {2} {4} [built]
      |    15 modules
 [67] ./frontend/src/components/Table.jsx + 8 modules 112 KiB {2} {4} [built]
      |    9 modules
 [68] ./node_modules/@emotion/is-prop-valid/dist/is-prop-valid.browser.esm.js + 1 modules 4.36 KiB {2} {4} [built]
      |    2 modules
[120] ./frontend/packs/application.js 563 bytes {0} [built]
[121] ./frontend/src/stylesheets/application.scss 39 bytes {0} [built]
[122] ./frontend/packs/connect.js 4.4 KiB {1} [built]
[124] ./frontend/images/favicon.png 79 bytes {3} [built]
[203] ./frontend/packs/dashboard.jsx + 25 modules 76.8 KiB {2} [built]
      | ./frontend/packs/dashboard.jsx 938 bytes [built]
      | ./frontend/src/pages/Dashboard.jsx 4.73 KiB [built]
      |     + 24 hidden modules
[204] ./frontend/packs/users.jsx + 4 modules 25.1 KiB {4} [built]
      | ./frontend/packs/users.jsx 753 bytes [built]
      | ./frontend/src/pages/Users.jsx 6.1 KiB [built]
      |     + 3 hidden modules
[205] ./frontend/packs/images.js + 1 modules 150 bytes {3} [built]
      | ./frontend/packs/images.js 19 bytes [built]
      | ./frontend/images/index.js 116 bytes [built]
    + 311 hidden modules

ERROR in js/application-163fb1a040f40ce8c3f3.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (.../node_modules/terser-webpack-plugin/dist/minify.js:175:23)
    at module.exports (.../node_modules/terser-webpack-plugin/dist/worker.js:13:40)
    at handle (.../node_modules/worker-farm/lib/child/index.js:44:8)
    at process.<anonymous> (.../node_modules/worker-farm/lib/child/index.js:51:3)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:828:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!frontend/src/stylesheets/styles/pagination.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./frontend/src/stylesheets/styles/pagination.css 1.64 KiB {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!node_modules/react-table/react-table.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/src/index.js??ref--7-2!node_modules/sass-loader/lib/loader.js??ref--7-3!frontend/src/stylesheets/application.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./frontend/src/stylesheets/application.scss 147 KiB {0} [built]
        + 1 hidden module
```
It was working fine, then I squashed a few commits in my repo and doesn't seem to work anymore. Running the webpack-dev-server seems to work fine without errors but can't precompile.  

Rails 5.2.2 
Ruby 2.6.0
webpacker-4.0.0.rc.7
package.json: 
```
{
  "private": true,
  "dependencies": {
    "@babel/preset-react": "^7.0.0",
    "@material-ui/core": "^3.8.1",
    "@material-ui/icons": "^3.0.1",
    "@rails/webpacker": "^4.0.0-rc.7",
    "apollo-boost": "^0.1.22",
    "babel-eslint": "^10.0.1",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.21",
    "eslint-plugin-prettier": "^3.0.0",
    "graphql": "^14.0.2",
    "graphql-tag": "^2.10.0",
    "normalize.css": "^8.0.1",
    "postcss-modules": "^1.4.1",
    "prop-types": "^15.6.2",
    "rails-ujs": "^5.2.1-1",
    "react": "^16.7.0",
    "react-apollo": "^2.3.3",
    "react-dom": "^16.7.0",
    "react-router-dom": "^4.3.1",
    "react-table": "^6.8.6",
    "styled-components": "^4.1.3",
    "sweetalert2": "^8.0.1",
    "webpack-cli": "^3.1.2",
    "webpack-merge": "^4.1.4"
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "eslint": "^5.10.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.3.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.11.1",
    "jest": "^23.6.0",
    "jest-dom": "^3.0.0",
    "prettier": "^1.15.3",
    "react-test-renderer": "^16.7.0",
    "react-testing-library": "^5.4.1",
    "regenerator-runtime": "^0.13.1",
    "webpack-dev-server": "^3.1.10"
  },
  "scripts": {
    "test": "jest"
  }
}
```

Anyone seen an error like this?

**Comment by pratik0809** [comment]
Found a similar issue: https://github.com/vuejs/vue-cli/issues/3407

The commented answer fixed this for me! https://github.com/vuejs/vue-cli/issues/3407#issuecomment-459985313

There seems to be bug in terser 3.16 which was just released earlier today.
