### ISSUE TITLE
Json parsing is not happening in webpacker

### ISSUE THREAD

**Issue by kshtzkr** [rails/webpacker#1935]
```
`02 rake aborted!
      02 JSON::ParserError: An empty string is not a valid JSON string.
      02 /opt/gotasker_dev/shared/bundle/ruby/2.5.0/bundler/gems/webpacker-96223d1721e9/lib/tasks/webpacker/compile.rake:10:in `parse'
      02 /opt/gotasker_dev/shared/bundle/ruby/2.5.0/bundler/gems/webpacker-96223d1721e9/lib/tasks/webpacker/compile.rake:10:in `block (2 levels) in <top (required)>'
      02 /opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `load'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `<main>'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `eval'
      02 /home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `<main>'
      02 Tasks: TOP => webpacker:compile
      02 (See full trace by running task with --trace)
#<Thread:0x0000000002e380d0@/home/kshitiz/.rvm/gems/ruby-2.5.1@gotasker/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /home/kshitiz/.rvm/gems/ruby-2.5.1@gotasker/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/home/kshitiz/.rvm/gems/ruby-2.5.1@gotasker/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as deploy@gotasker-dev.rls-intra.com: bundle exit status: 1 (SSHKit::Runner::ExecuteError)
bundle stdout: Didn't find any digests file at /opt/gotasker_dev/releases/20190207140747/public/packs/digests.json. You must first compile the packs via rails webpacker:compile
bundle stderr: /opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::PDF
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of PDF was here
(node:15185) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Killed
rake aborted!
JSON::ParserError: An empty string is not a valid JSON string.
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/bundler/gems/webpacker-96223d1721e9/lib/tasks/webpacker/compile.rake:10:in `parse'
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/bundler/gems/webpacker-96223d1721e9/lib/tasks/webpacker/compile.rake:10:in `block (2 levels) in <top (required)>'
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `<main>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `eval'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@gotasker-dev.rls-intra.com: bundle exit status: 1
bundle stdout: Didn't find any digests file at /opt/gotasker_dev/releases/20190207140747/public/packs/digests.json. You must first compile the packs via rails webpacker:compile
bundle stderr: /opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::PDF
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of PDF was here
(node:15185) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Killed
rake aborted!
JSON::ParserError: An empty string is not a valid JSON string.
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/bundler/gems/webpacker-96223d1721e9/lib/tasks/webpacker/compile.rake:10:in `parse'
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/bundler/gems/webpacker-96223d1721e9/lib/tasks/webpacker/compile.rake:10:in `block (2 levels) in <top (required)>'
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `<main>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `eval'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)


Caused by:
SSHKit::Command::Failed: bundle exit status: 1
bundle stdout: Didn't find any digests file at /opt/gotasker_dev/releases/20190207140747/public/packs/digests.json. You must first compile the packs via rails webpacker:compile
bundle stderr: /opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::PDF
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of PDF was here
(node:15185) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Killed
rake aborted!
JSON::ParserError: An empty string is not a valid JSON string.
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/bundler/gems/webpacker-96223d1721e9/lib/tasks/webpacker/compile.rake:10:in `parse'
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/bundler/gems/webpacker-96223d1721e9/lib/tasks/webpacker/compile.rake:10:in `block (2 levels) in <top (required)>'
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `<main>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `eval'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)

Tasks: TOP => deploy:compile_assets => deploy:run_webpacker
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@gotasker-dev.rls-intra.com: bundle exit status: 1
bundle stdout: Didn't find any digests file at /opt/gotasker_dev/releases/20190207140747/public/packs/digests.json. You must first compile the packs via rails webpacker:compile
bundle stderr: /opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::PDF
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of PDF was here
(node:15185) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Killed
rake aborted!
JSON::ParserError: An empty string is not a valid JSON string.
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/bundler/gems/webpacker-96223d1721e9/lib/tasks/webpacker/compile.rake:10:in `parse'
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/bundler/gems/webpacker-96223d1721e9/lib/tasks/webpacker/compile.rake:10:in `block (2 levels) in <top (required)>'
/opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `load'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `<main>'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `eval'
/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


/opt/gotasker_dev/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `load'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/bundle:23:in `<main>'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `eval'

/home/deploy/.rvm/gems/ruby-2.5.1@gotasker/bin/ruby_executable_hooks:15:in `<main>'

 DEBUG [bde4d46d] 	Tasks: TOP => webpacker:compile

 DEBUG [bde4d46d] 	(See full trace by running task with --trace)
`

```

Unable to use the capistrano for the deployment due to this.

**Comment by jpickwell** [comment]
You're using a version of Webpacker from 2017-03-16 (between v1.0.0 and v1.1.0). Try upgrading Webpacker. Latest stable version is v3.5.5, and I personally am using v4.0.0.rc.7 (gem only).

**Comment by jpickwell** [comment]
Looking further at your issue, I would recommend trying to run `bin/webpack` locally to see what errors you're getting since the issue is that `bin/webpack --json` is returning nothing (empty string), thus the `JSON::ParserError: An empty string is not a valid JSON string.` error message.

**Comment by kshtzkr** [comment]
@jpickwell  I tried it locallly but it worked fine on the local env but when I am trying it on server then It's not working no error recieved in local machine

**Comment by jpickwell** [comment]
Well, I stand by my suggestion to upgrade to the latest version of Webpacker that's compatible with Rails 4.2.10.

**Comment by kshtzkr** [comment]
hey @jpickwell  I found the issue why this actually happening It was due to my instance memory was getting fully packed no memory on the server to run the all this process. so, everytime it get failed.

Just clearing the memory of the server worked for me
