### ISSUE TITLE
failed compilation

### ISSUE THREAD

**Issue by teamco** [rails/webpacker#1942]
Failed run rails application:
- Webpacker @latest
- Rails @latest

```
.rvm/gems/ruby-2.6.0/gems/json-1.8.6/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/json-1.8.6/lib/json/common.rb:155:in `new'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/webpacker-4.0.0.rc.7/lib/webpacker/manifest.rb:84:in `load'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/webpacker-4.0.0.rc.7/lib/webpacker/manifest.rb:18:in `refresh'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/webpacker-4.0.0.rc.7/lib/webpacker/commands.rb:14:in `bootstrap'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/webpacker-4.0.0.rc.7/lib/webpacker.rb:27:in `bootstrap'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/webpacker-4.0.0.rc.7/lib/webpacker/railtie.rb:84:in `block in <class:Engine>'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
14:36:36 web.1       | 	from .rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
14:36:36 web.1       | 	from .rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
14:36:36 web.1       | 	from .rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
14:36:36 web.1       | 	from .rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
14:36:36 web.1       | 	from .rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
14:36:36 web.1       | 	from .rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
14:36:36 web.1       | 	from .rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
14:36:36 web.1       | 	from .rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
14:36:36 web.1       | 	from .rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
14:36:36 web.1       | 	from RubymineProjects/***/config/environment.rb:5:in `<top (required)>'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
14:36:36 web.1       | 	from config.ru:3:in `block in <main>'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
14:36:36 web.1       | 	from config.ru:in `new'
14:36:36 web.1       | 	from config.ru:in `<main>'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:27:in `app'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:51:in `start'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `tap'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `perform'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
14:36:36 web.1       | 	from .rvm/gems/ruby-2.6.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<top (required)>'
14:36:36 web.1       | 	from bin/rails:4:in `require'
14:36:36 web.1       | 	from bin/rails:4:in `<main>'
14:36:36 web.1       | Exiting
14:36:37 web.1       | exited with code 1
14:36:37 system      | sending SIGTERM to all processes
14:36:42 system      | sending SIGKILL to all processes
```

**Comment by guillaumebriday** [comment]
Do you still have this issue ?

Or can this issue be closed ?
