### ISSUE TITLE
Is it possible to start with 4.0.0 fresh right now without having to manually upgrade to v4?

### ISSUE THREAD

**Issue by lassiter** [rails/webpacker#1977]
I added `gem 'webpacker', '>= 4.0.x'` to my gemfile and ran:
```
$ bundle install
$ bin/rails webpacker:install
$ bin/rails webpacker:install:react
```

I was hoping to start fresh with a 4.0.0 release candidate but haven't found a CLI flag to use in the issues or docs. I'm building a new app and wanted to use Webpacker 4. I'm currently getting this error when I render `<%= javascript_pack_tag 'hello_react' %>`. 

```
Started GET "/home/index" for 127.0.0.1 at 2019-03-03 18:49:17 -0600
Processing by HomeController#index as HTML
  Rendering home/index.html.erb within layouts/application
[Webpacker] Compiling…
[Webpacker] Compilation failed:

Hash: aab04d875a653755daab
Version: webpack 4.29.6
Time: 486ms
Built at: 03/03/2019 6:49:20 PM
                                     Asset       Size       Chunks             Chunk Names
    js/application-91c9d0216efd638eb7b6.js   6.81 KiB  application  [emitted]  application
js/application-91c9d0216efd638eb7b6.js.map   3.53 KiB  application  [emitted]  application
    js/hello_react-83746c4448ebf5ee0c58.js   6.71 KiB  hello_react  [emitted]  hello_react
js/hello_react-83746c4448ebf5ee0c58.js.map   3.53 KiB  hello_react  [emitted]  hello_react
                             manifest.json  703 bytes               [emitted]  
Entrypoint application = js/application-91c9d0216efd638eb7b6.js js/application-91c9d0216efd638eb7b6.js.map
Entrypoint hello_react = js/hello_react-83746c4448ebf5ee0c58.js js/hello_react-83746c4448ebf5ee0c58.js.map
[./app/javascript/packs/application.js] 2.92 KiB {application} [built] [failed] [1 error]
[./app/javascript/packs/hello_react.jsx] 2.81 KiB {hello_react} [built] [failed] [1 error]

ERROR in ./app/javascript/packs/application.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-plugin-transform-object-rest-spread' from '/Users/lassitergregg/Code/Guild/guildhall'
    at Function.module.exports [as sync] (/Users/lassitergregg/Code/Guild/guildhall/node_modules/resolve/lib/sync.js:58:15)
    at resolveStandardizedName (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)
    at mergeChainOpts (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:5:194)
    at /Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:5:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:5:97)
    at Object._loader (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:220:18)
    at Object.loader (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:56:18)
    at Object.<anonymous> (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:51:12)

ERROR in ./app/javascript/packs/hello_react.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-plugin-transform-object-rest-spread' from '/Users/lassitergregg/Code/Guild/guildhall'
    at Function.module.exports [as sync] (/Users/lassitergregg/Code/Guild/guildhall/node_modules/resolve/lib/sync.js:58:15)
    at resolveStandardizedName (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)
    at mergeChainOpts (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/Users/lassitergregg/Code/Guild/guildhall/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:5:194)
    at /Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:5:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:5:97)
    at Object.loader (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:56:18)
    at Object.<anonymous> (/Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-loader/lib/index.js:51:12)

  Rendered home/index.html.erb within layouts/application (2433.4ms)
Completed 200 OK in 3902ms (Views: 3871.8ms | ActiveRecord: 0.0ms)
```

I tried adding each babel package via yarn but am just getting errors like:

```
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/lassitergregg/Code/Guild/guildhall/node_modules/babel-preset-react/lib/index.js
```

Also, to be more helpful for any testing later:
_package.json_
```
{
  "name": "guildhall",
  "private": true,
  "dependencies": {
    "@babel/preset-react": "^7.0.0",
    "@rails/webpacker": "^4.0.0-rc.8",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "prop-types": "^15.7.2",
    "react": "^16.8.3",
    "react-dom": "^16.8.3"
  },
  "devDependencies": {
    "webpack-dev-server": "^3.2.1"
  }
}

```
_Gemfile_
```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.2'
# Use PostgreSQL as the database for Active Record
gem 'pg', '~> 1.1', '>= 1.1.4'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use devise as flexible authentication solution for Rails with Warden.
gem 'devise'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '>= 4.0.x'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'pry' anywhere in the code to stop execution and get a debugger console
  gem 'pry-byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'faker'
  gem 'dotenv-rails', '~> 2.4.0'
  gem 'factory_bot_rails', '~> 4.0'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'rspec-rails', '~> 3.8'
  gem 'shoulda-matchers', '~> 4.0.x'
  gem 'database_cleaner'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

```

**Comment by lassiter** [comment]
`/Users/lassitergregg/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `webpacker' for #<Rails::Application::Configuration:0x00007fc737f5d0d8> (NoMethodError)`

This is my latest problem which I'm not sure how to approach right now. I was successful, then setup Jest, and now `config.webpacker`'s method is missing which is very confusing.

**Comment by connorshea** [comment]
The release of 4.0 stable may have fixed this issue, or you may need to use the Rails 6 beta to get this to work.

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
