### ISSUE TITLE
rails webpacker:install:react blocks on windows 10

### ISSUE THREAD

**Issue by bgmat** [rails/webpacker#2022]
I tried to start a new Rails app with React like this:
`rails new <APP NAME> --webpack=react -d postgresql -T`

It blocks at the webpacker:install:react step, without any error message:
Running the below command with trace, shows this:
```
rails --trace webpacker:install:react
** Invoke webpacker:install:react (first_time)
** Invoke webpacker:verify_install (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
** Invoke webpacker:check_yarn (first_time)
** Execute webpacker:check_yarn
** Invoke webpacker:check_binstubs (first_time)
** Execute webpacker:check_binstubs
** Execute webpacker:verify_install
** Execute webpacker:install:react
```

I'm running on Windows 10. 
After interrupting the above command I run this:
```
rails webpacker:info
Ruby: ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
Rails: 5.2.2.1
Webpacker: 4.0.2
Node: v8.11.3
Yarn: 1.10.1

@rails/webpacker:
test2@ C:\Apps\test\test2
`-- @rails/webpacker@4.0.2

Is bin/webpack present?: true
Is bin/webpack-dev-server present?: true
Is bin/yarn present?: true
```

Any idea what could be wrong?

**Comment by gauravtiwari** [comment]
@bgmat Are you able to run other installers fine? `webpacker:vue` etc.

**Comment by bgmat** [comment]
No, vue installer doesn't work either. Same behavior - freezes.
```
rails --trace webpacker:install:vue
** Invoke webpacker:install:vue (first_time)
** Invoke webpacker:verify_install (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
** Invoke webpacker:check_yarn (first_time)
** Execute webpacker:check_yarn
** Invoke webpacker:check_binstubs (first_time)
** Execute webpacker:check_binstubs
** Execute webpacker:verify_install
** Execute webpacker:install:vue
```

Also, I updated ruby, but it didn't make any difference:
```
webpacker:info
Ruby: ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
Rails: 5.2.2.1
Webpacker: 4.0.2
Node: v8.11.3
Yarn: 1.10.1
```

**Comment by RailsCod3rFuture** [comment]
When I run rails webpacker:install:vue, it hangs on Windows 10. wepacker:install completes the installation process. Just not the vue, angular or react installer...

```
C:\Ruby24-x64\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:/Users/Cod3r/RubymineProjects/vuetestnew/bin/rails webpacker:install:vue
warning package.json: No license field
warning No license field
```

I downgraded to rails 5.0.0, but it doesn't matter with regards to using the rake task to setup the installer.

**Comment by bgmat** [comment]
I continued to dig into this issue.
This is not related to react or vue generators. It seems to be an webpacker install isuue.
If I create a new app, like this:
`rails new test_app --webpack -d postgresql -T` 
The app generator completes successfully, but rails does not start. It behaves exactly like the `rails webpacker:install:react` command. Freezes without any error message.

After I stop it (CTRL-C) I get this call stack:

```
> rails c
Traceback (most recent call last):
        30: from bin/rails:4:in `<main>'
        29: from bin/rails:4:in `require'
        28: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
        27: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
        26: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
        25: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        24: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        23: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        22: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:95:in `perform'
        21: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        20: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/command/actions.rb:28:in `require_environment!'
        19: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
        18: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require'
        17: from C:/Bogdan/Work/ShopifyPartner/Apps/test/test_app/config/environment.rb:5:in `<top (required)>'
        16: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
        15: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
        14: from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        13: from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        12: from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        11: from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:347:in `call'
        10: from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:347:in `each'
         9: from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
         8: from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
         7: from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
         6: from C:/Ruby/Ruby25-x64/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
         5: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
         4: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
         3: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
         2: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/webpacker-4.0.2/lib/webpacker/railtie.rb:33:in `block in <class:Engine>'
         1: from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/core_ext/kernel/agnostics.rb:9:in ``'
C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/core_ext/kernel/agnostics.rb:9:in ``': Interrupt
Terminate batch job (Y/N)? y
```

If I create a new rails app, without --webpack, everything is ok.

**Comment by bgmat** [comment]
Found the issue!
I had an older version of node installed: v8.11.3
I installed node-v10.15.3-x64, then the app generator worked and rails starts.

**Comment by hyuan13** [comment]
I have spent a few hours trying to find out what's going on until I saw your post!

**Comment by sbassah** [comment]
> Found the issue!
> I had an older version of node installed: v8.11.3
> I installed node-v10.15.3-x64, then the app generator worked and rails starts.

Thanks a lot. Your suggestion fixed it
