### ISSUE TITLE
scss error

### ISSUE THREAD

**Issue by alec-c4** [rails/webpacker#2037]
Hi,
i see strange behaviour when i importing bootstrap in scss file under webpacker . 

after adding 
```
@import '~bootstrap/dist/css/bootstrap';
```

to application.scss i see following error

```
server | Started GET "/" for ::1 at 2019-03-29 21:08:50 +0300
server | Processing by HomeController#index as HTML
server | Started GET "/blob:http://localhost:5000/bootstrap.css.map" for ::1 at 2019-03-29 21:08:50 +0300
server |
server | ActionController::RoutingError (No route matches [GET] "/blob:http:/localhost:5000/bootstrap.css.map"):
server |
server | actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
server | web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
server | web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
server | web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
server | web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
server | actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
server | railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
server | railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
server | activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
server | activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
server | activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
server | railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
server | actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
server | actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
server | rack (2.0.6) lib/rack/method_override.rb:22:in `call'
server | rack (2.0.6) lib/rack/runtime.rb:22:in `call'
server | activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
server | actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
server | actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
server | rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
server | webpacker (4.0.2) lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
server | rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
server | railties (5.2.3) lib/rails/engine.rb:524:in `call'
server | puma (3.12.1) lib/puma/configuration.rb:227:in `call'
server | puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
server | puma (3.12.1) lib/puma/server.rb:474:in `process_client'
server | puma (3.12.1) lib/puma/server.rb:334:in `block in run'
server | puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
server |   Rendering home/index.html.slim within layouts/application
server |   Rendered home/index.html.slim within layouts/application (22.3ms)
server | Completed 200 OK in 56ms (Views: 52.2ms | ActiveRecord: 0.0ms)
```

what's wrong?

**Comment by jakeNiemiec** [comment]
You need `@import "~bootstrap/scss/bootstrap";`

`No route matches [GET] "/blob:http:/localhost:5000/bootstrap.css.map"` is harmless, when you have devtools open it will automaticly try and find maps for your packs.

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
