### ISSUE TITLE
"SyntaxError: Unexpected identifier" in jest after upgrade to webpacker 4

### ISSUE THREAD

**Issue by Loremaster** [rails/webpacker#2044]
Hey,

I started the upgrade following https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md

I was able to make project run locally alright. However I experience strange error in jest when try to run my tests. Any advice on that?

```
 FAIL  app/javascript/account_settings/actions/__tests__/account_unsubscribers.spec.ts
  ● Test suite failed to run

/app/javascript/compose_email/components/__mocks__/pusher-js-mock.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import pusherChannelMock from "./pusher-channel-mock";
                                                                                                    ^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

       7 | (global as any).$ = (global as any).jQuery = $;
       8 | (window as any).$ = $;
    >  9 | 
         | ^
      10 | Vue.config.productionTip = false;
      11 | Vue.config.ignoredElements = [
      12 |   "b-button",

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (app/javascript/.setup.ts:9:40)
```

I am not sure what is going on here. Any advice how to fix it?

**config/webpacker.yml**
```
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: ["app/assets"]

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .mjs
    - .tsx
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
    - .module.sass
    - .module.scss
    - .module.css

development:
  <<: *default
  compile: true

  # Verifies that correct packages and versions are installed by inspecting package.json, yarn.lock, and node_modules
  check_yarn_integrity: true

  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: true
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true
```

**package.json**
```
{
  "engines": {
    "node": "11.6.0",
    "npm": "5.6.0",
    "yarn": "1.12.3"
  },
  "dependencies": {
    "@rails/webpacker": "^4.0.2",
    "@types/ckeditor": "^4.9.5",
    "@types/jquery": "^3.3.29",
    "@types/lodash": "^4.14.119",
    "@types/node": "^10.12.18",
    "@types/pusher-js": "^4.2.0",
    "axios": "^0.18.0",
    "babel-loader": "^7.1.5",
    "babel-polyfill": "^6.26.0",
    "babel-preset-vue": "^2.0.2",
    "bootstrap-vue": "^2.0.0-rc.15",
    "coffeelint": "^2.1.0",
    "epic-spinners": "^1.0.4",
    "es6-promise": "^4.2.5",
    "immutable": "^4.0.0-rc.12",
    "jquery": "^3.3.1",
    "lodash": "^4.17.11",
    "nodelist-foreach-polyfill": "^1.2.0",
    "pusher-js": "^4.3.1",
    "qs": "^6.6.0",
    "rosie": "^2.0.1",
    "ts-loader": "^5.3.3",
    "typescript": "^3.2.2",
    "vee-validate": "^2.1.7",
    "vue": "^2.6.10",
    "vue-class-component": "^6.3.2",
    "vue-loader": "^15.7.0",
    "vue-notification": "^1.3.14",
    "vue-property-decorator": "^7.3.0",
    "vue-template-compiler": "^2.6.10",
    "vuex": "^3.0.1",
    "vuex-class": "^0.3.1"
  },
  "devDependencies": {
    "@types/jest": "^23.3.12",
    "@vue/test-utils": "^1.0.0-beta.28",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^23.6.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-prettier": "^3.5.0",
    "eslint-import-resolver-webpack": "^0.10.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jest": "^22.1.3",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-vue": "^5.1.0",
    "flush-promises": "^1.0.2",
    "identity-obj-proxy": "^3.0.0",
    "ignore-loader": "^0.1.2",
    "jest": "=23.6.0",
    "jest-serializer-vue": "^2.0.2",
    "lint-staged": "^8.1.5",
    "moxios": "^0.4.0",
    "pre-commit": "^1.2.2",
    "prettier": "^1.15.3",
    "stylelint": "^9.10.1",
    "stylelint-config-standard": "^18.2.0",
    "stylelint-scss": "^3.5.1",
    "ts-jest": "^23.10.5",
    "tslint": "^5.12.1",
    "tslint-loader": "^3.6.0",
    "vue-jest": "^3.0.2",
    "webpack-dev-server": "^3.3.0"
  },
  "scripts": {
    "test": "jest",
    "lint-staged": "$(yarn bin)/lint-staged"
  },
  "lint-staged": {
    "app/javascript/**/*.js": [
      "prettier --write",
      "eslint",
      "git add"
    ],
    "app/javascript/**/*.ts": [
      "prettier --write",
      "tslint --fix",
      "git add"
    ],
    "app/javascript/**/*.vue": [
      "prettier --write",
      "stylelint --fix",
      "tslint --fix",
      "git add"
    ],
    "app/javascript/**/*.spec.js": [
      "prettier --write",
      "eslint",
      "git add"
    ],
    "app/javascript/**/*.spec.ts": [
      "prettier --write",
      "tslint",
      "git add"
    ],
    "app/assets/stylesheets/**/*": [
      "prettier --write",
      "stylelint --fix",
      "git add"
    ],
    "app/stylesheets/**/*.scss": [
      "prettier --write",
      "stylelint --fix",
      "git add"
    ],
    "app/javascript/**/*.scss": [
      "prettier --write",
      "stylelint --fix",
      "git add"
    ],
    "app/javascript/**/*.json": [
      "prettier --write",
      "git add"
    ],
    "*.js": [
      "prettier --write",
      "eslint",
      "git add"
    ]
  },
  "pre-commit": [
    "lint-staged"
  ]
}
```

**jest.config.js**
```
const { resolve } = require("path");

module.exports = {
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  setupFiles: ["<rootDir>/app/javascript/.setup.ts"],
  moduleDirectories: ["node_modules", "<rootDir>/app/javascript", "<rootDir>/spec/javascript"],
  transform: {
    "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
    ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest",
    "^.+\\.tsx?$": "ts-jest",
  },
  testRegex: "/__tests__/.*\\.(ts|tsx|js)$",
  transformIgnorePatterns: ["node_modules/(?!bootstrap-vue|epic-spinners)"],
  snapshotSerializers: ["<rootDir>/node_modules/jest-serializer-vue"],
  testPathIgnorePatterns: ["<rootDir>/app/assets", "<rootDir>/config/webpack/test.js", "<rootDir>/vendor"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/app/javascript/$1",
    "\\.(css|less)$": "identity-obj-proxy",
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
      "<rootDir>/app/javascript/__mocks__/fileMock.js",
  },
  restoreMocks: true,
  globals: {
    "ts-jest": {
      tsConfig: "tsconfig.jest.json",
      babelConfig: true,
      diagnostics: false,
    },
    "vue-jest": {
      tsConfig: resolve("tsconfig.jest.json"),
    },
  },
};
```

**.setup.ts**
```
import "babel-polyfill"; // for async/await
import Vue from "vue";
import PusherMock from "./compose_email/components/__mocks__/pusher-js-mock";
import $ from "jquery";

(window as any).PusherVue = new PusherMock();
(global as any).$ = (global as any).jQuery = $;
(window as any).$ = $;

Vue.config.productionTip = false;
Vue.config.ignoredElements = [
  "b-button",
];
```

**babel.config.js**
```
module.exports = function(api) {
  const validEnv = ["development", "test", "production"];
  const currentEnv = api.env();
  const isDevelopmentEnv = api.env("development");
  const isProductionEnv = api.env("production");
  const isTestEnv = api.env("test");

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      "Please specify a valid `NODE_ENV` or " +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: ' +
        JSON.stringify(currentEnv) +
        ".",
    );
  }

  return {
    presets: [
      isTestEnv && [
        require("@babel/preset-env").default,
        {
          targets: {
            node: "current",
          },
        },
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        require("@babel/preset-env").default,
        {
          forceAllTransforms: true,
          useBuiltIns: "entry",
          modules: false,
          exclude: ["transform-typeof-symbol"],
        },
      ],
    ].filter(Boolean),
    plugins: [
      require("babel-plugin-macros"), 
      require("@babel/plugin-syntax-dynamic-import").default,
      isTestEnv && require("babel-plugin-dynamic-import-node"),
      require("@babel/plugin-transform-destructuring").default,
      [
        require("@babel/plugin-proposal-class-properties").default,
        {
          loose: true,
        },
      ],
      [
        require("@babel/plugin-proposal-object-rest-spread").default,
        {
          useBuiltIns: true,
        },
      ],
      [
        require("@babel/plugin-transform-runtime").default,
        {
          helpers: false,
          regenerator: true,
        },
      ],
      [
        require("@babel/plugin-transform-regenerator").default,
        {
          async: false,
        },
      ],
    ].filter(Boolean),
  };
};
```

**webpack/loaders/tslint.js**
```
module.exports = {
  test: /\.ts$/,
  enforce: "pre",
  exclude: /(node_modules)/,
  use: [
    {
      loader: "tslint-loader",
      options: {
        configFile: "tslint.json",
      },
    },
  ],
};
```

**webpack/loaders/typescript.js**
```
module.exports = {
  test: /\.(ts|tsx)?(\.erb)?$/,
  use: [
    {
      loader: "ts-loader",
      options: {
        appendTsSuffixTo: [/\.vue$/],
      },
    },
  ],
};
```

**webpack/loaders/vue.js**
```
const isProduction = process.env.NODE_ENV === "production";
const tsLoaders = isProduction ? {} : { ts: "ts-loader!tslint-loader" };

module.exports = {
  test: /\.vue(\.erb)?$/,
  use: [
    {
      loader: "vue-loader",
      options: {
        loaders: tsLoaders,
      },
    },
  ],
};
```

**webpack/loaders/environment.js**
```
const { environment } = require("@rails/webpacker");
const { VueLoaderPlugin } = require("vue-loader");
const typescript = require("./loaders/typescript");
const customConfig = require("./custom");
const vue = require("./loaders/vue");
const tslint = require("./loaders/tslint");

const isProduction = process.env.NODE_ENV === "production";

environment.config.merge(customConfig);

if (!isProduction) {
  environment.loaders.append("tslint", tslint);
}

environment.loaders.append("typescript", typescript);

environment.plugins.prepend("VueLoaderPlugin", new VueLoaderPlugin());
environment.loaders.prepend("vue", vue);
module.exports = environment;

environment.loaders.delete("nodeModules");
```

**Comment by Loremaster** [comment]
Was able to resolve my issue by upgrading other packages to make sure those support babel 7.
