### ISSUE TITLE
Raise exception when running rake assets:precompile in docker building image 

### ISSUE THREAD

**Issue by kevin-jj** [rails/webpacker#2095]
```ruby
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning " > webpack-dev-server@3.4.1" has unmet peer dependency "webpack@^4.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.0" has unmet peer dependency "webpack@^4.0.0".
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning " > webpack-dev-server@3.4.1" has unmet peer dependency "webpack@^4.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.0" has unmet peer dependency "webpack@^4.0.0".
E, [2019-05-19T02:13:31.473062 #7] ERROR -- : run() in thread failed: inotify event queue has overflowed.:\n /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:120:in `initialize'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:100:in `new'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:100:in `consume'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:292:in `read_events'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252:in `process'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229:in `block in run'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `synchronize'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `run'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'\n\ncalled from:\n /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `start'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/listener.rb:68:in `block in <class:Listener>'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `instance_eval'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `call'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:57:in `transition'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/listener.rb:91:in `start'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/evented_file_update_checker.rb:96:in `boot!'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/evented_file_update_checker.rb:67:in `initialize'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application/finisher.rb:166:in `new'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application/finisher.rb:166:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/var/www/vendor/config/environment.rb:5:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
#<Thread:0x00005628dec860d8@/usr/local/bundle/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:120:in `initialize': inotify event queue has overflowed. (INotify::QueueOverflowError)
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:100:in `new'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:100:in `consume'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:292:in `read_events'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252:in `process'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229:in `block in run'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `synchronize'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `run'
	from /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
	from /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
	from /usr/local/bundle/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
E, [2019-05-19T02:13:32.160149 #6] ERROR -- : run() in thread failed: inotify event queue has overflowed.:\n /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:120:in `initialize'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:100:in `new'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:100:in `consume'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:292:in `read_events'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252:in `process'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229:in `block in run'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `synchronize'
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `run'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'\n\ncalled from:\n /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `start'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/listener.rb:68:in `block in <class:Listener>'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `instance_eval'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `call'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:57:in `transition'
/usr/local/bundle/gems/listen-3.1.5/lib/listen/listener.rb:91:in `start'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/evented_file_update_checker.rb:96:in `boot!'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/evented_file_update_checker.rb:67:in `initialize'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application/finisher.rb:166:in `new'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application/finisher.rb:166:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/var/www/vendor/config/environment.rb:5:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
#<Thread:0x00005586fb756408@/usr/local/bundle/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:120:in `initialize': inotify event queue has overflowed. (INotify::QueueOverflowError)
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:100:in `new'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/event.rb:100:in `consume'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:292:in `read_events'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252:in `process'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229:in `block in run'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `synchronize'
	from /usr/local/bundle/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `run'
	from /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
	from /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
	from /usr/local/bundle/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
[4/4] Building fresh packages...
[4/4] Building fresh packages...
Done in 59.46s.
Done in 59.72s.
Compiling…
Compiling…
```

**Comment by kevin-jj** [comment]
However it works with running "yarn install".   @gauravtiwari

**Comment by kevin-jj** [comment]
close issue. It works when get docker reinstalled.
