### ISSUE TITLE
File to import not found or unreadable: ~@fortawesome/fontawesome-free/scss/variables.

### ISSUE THREAD

**Issue by afuno** [rails/webpacker#2100]
I have a Rails 5.2.3 application. In it, I almost completely abandoned the "rails" assets. I don't use rails stylesheets. For CSS responsible Webpacker (Vue).

I didn't touch the Webpacker settings.

I created the file: app/javascript/admin/styles/fontawesome/base.scss
Its contents are:

```scss
@import '~@fortawesome/fontawesome-free/scss/variables';

$fa-font-path: '~@fortawesome/fontawesome-free/webfonts';

@import '~@fortawesome/fontawesome-free/scss/mixins';
@import '~@fortawesome/fontawesome-free/scss/core';
@import '~@fortawesome/fontawesome-free/scss/larger';
@import '~@fortawesome/fontawesome-free/scss/fixed-width';
@import '~@fortawesome/fontawesome-free/scss/list';
@import '~@fortawesome/fontawesome-free/scss/bordered-pulled';
@import '~@fortawesome/fontawesome-free/scss/animated';
@import '~@fortawesome/fontawesome-free/scss/rotated-flipped';
@import '~@fortawesome/fontawesome-free/scss/stacked';
@import '~@fortawesome/fontawesome-free/scss/icons';
@import '~@fortawesome/fontawesome-free/scss/screen-reader';

@import '~@fortawesome/fontawesome-free/scss/fontawesome';
@import '~@fortawesome/fontawesome-free/scss/brands';
@import '~@fortawesome/fontawesome-free/scss/solid';
@import '~@fortawesome/fontawesome-free/scss/regular';
```

There are no problems when running in development environment. But if I execute this command:

```ssh
$ RAILS_ENV=production NODE_ENV=production bundle exec rails assets:precompile
```

The `@fortawesome` directory is deleted from the `node_modules` directory.

For some reason, an error isn't displayed in the console, but there is one. This error is displayed during deployment (dokku) on the server:

```
ERROR in ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/admin/styles/application.scss
Module build failed:
@import '~@fortawesome/fontawesome-free/scss/variables';
^
      File to import not found or unreadable: ~@fortawesome/fontawesome-free/scss/variables.
      in /Users/afuno/Projects/app4/app/javascript/admin/styles/fontawesome/base.scss (line 1, column 1)
 @ ./app/javascript/admin/styles/application.scss 2:14-224
 @ ./app/javascript/packs/admin.js

ERROR in ./app/javascript/admin/styles/application.scss
Module build failed: ModuleBuildError: Module build failed:
@import '~@fortawesome/fontawesome-free/scss/variables';
^
      File to import not found or unreadable: ~@fortawesome/fontawesome-free/scss/variables.
      in /Users/afuno/Projects/app4/app/javascript/admin/styles/fontawesome/base.scss (line 1, column 1)
    at runLoaders (/Users/afuno/Projects/app4/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/afuno/Projects/app4/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/afuno/Projects/app4/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/afuno/Projects/app4/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/afuno/Projects/app4/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/Users/afuno/Projects/app4/node_modules/neo-async/async.js:8067:18)
    at options.error (/Users/afuno/Projects/app4/node_modules/node-sass/lib/index.js:294:32)
 @ ./app/javascript/admin/styles/application.scss
 @ ./app/javascript/packs/admin.js
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/vue-loader/lib/style-compiler/index.js?{"optionsId":"0","vue":true,"scoped":false,"sourceMap":false}!node_modules/vue-loader/lib/selector.js?type=styles&index=0!app/javascript/public/components/test/base.vue:
       2 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--2-2!node_modules/postcss-loader/lib/index.js??ref--2-3!node_modules/sass-loader/lib/loader.js??ref--2-4!app/javascript/admin/styles/application.scss:
       [0] ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/admin/styles/application.scss 314 bytes {0} [built] [failed] [1 error]

    ERROR in ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/admin/styles/application.scss
    Module build failed:
    @import '~@fortawesome/fontawesome-free/scss/variables';
    ^
          File to import not found or unreadable: ~@fortawesome/fontawesome-free/scss/variables.
          in /Users/afuno/Projects/app4/app/javascript/admin/styles/fontawesome/base.scss (line 1, column 1)
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--2-2!node_modules/postcss-loader/lib/index.js??ref--2-3!node_modules/sass-loader/lib/loader.js??ref--2-4!app/javascript/admin/styles/application.scss:
       [0] ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/admin/styles/application.scss 651 kB {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--2-2!node_modules/postcss-loader/lib/index.js??ref--2-3!node_modules/sass-loader/lib/loader.js??ref--2-4!app/javascript/public/styles/application.scss:
       [0] ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/public/styles/application.scss 651 kB {0} [built]
        + 1 hidden module

```

Please help me fix it.

**Comment by afuno** [comment]
The problem was this:
```
"devDependencies": {
  "@fortawesome/fontawesome-free": "^5.8.1",
  "webpack-dev-server": "2.11.2"
}
```

**Comment by jakeNiemiec** [comment]
@afuno there are some know performance pain points when using FA + webpack...in case you run into them: https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking

**Comment by afuno** [comment]
@jakeNiemiec I don't have a full SPA.

**Comment by RonWalker22** [comment]
@afuno what solution did you find, if any?
