### ISSUE TITLE
Failing Webpacker Jest Specs - unclear in docs how to address

### ISSUE THREAD

**Issue by Dujota** [rails/webpacker#2154]
I have upgraded from Webpacker 3.0 to 4.x. on our 5.1.x Rails project and then added the React plugin for webpacker. 

It is all setup (after much blood, sweat, and tears) it all works. Next i configured the staging environment as suggested int he Webpacker Docs and everything works fine on dev/staging/production. 

I am using the standard webpacker.yml file that gets generated :

```
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .jsx
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Verifies that correct packages and versions are installed by inspecting package.json, yarn.lock, and node_modules
  check_yarn_integrity: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

staging:
  <<: *default

  # Staging depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true

  # Compile staging packs to a separate directory
  public_output_path: packs-staging

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true
```

Finally build our CircleCI flow and it goes through alll the jest specs, but then .... FAIL. 

I checked out the tests, and the failing jest specs are actually not mine, but part of the ` webpacker-4.0.7/package/__tests__/ ` 

I didnt do anything special, i am using the default config that is generated, so what am i missing here? 

Below is the failures: 

```
Your job ran 741 tests with 3 failures
Config should return extensions as listed in app config - Config should return extensions as listed in app config
Error: expect(received).toEqual(expected) // deep equality

- Expected
+ Received

@@ -1,6 +1,7 @@
  Array [
+   ".jsx",
    ".mjs",
    ".js",
    ".sass",
    ".scss",
    ".css",
    at Object.toEqual (/root/repo/vendor/bundle/ruby/2.5.0/gems/webpacker-4.0.7/package/__tests__/config.js:50:31)
    at Object.asyncJestTest (/root/repo/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at resolve (/root/repo/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
    at new Promise (<anonymous>)
    at mapper (/root/repo/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at promise.then (/root/repo/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
Config should return static assets extensions as listed in app config - Config should return static assets extensions as listed in app config
Error: expect(received).toEqual(expected) // deep equality

- Expected
+ Received

@@ -4,6 +4,11 @@
    ".png",
    ".gif",
    ".tiff",
    ".ico",
    ".svg",
+   ".eot",
+   ".otf",
+   ".ttf",
+   ".woff",
+   ".woff2",
  ]
    at Object.toEqual (/root/repo/vendor/bundle/ruby/2.5.0/gems/webpacker-4.0.7/package/__tests__/config.js:68:45)
    at Object.asyncJestTest (/root/repo/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at resolve (/root/repo/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
    at new Promise (<anonymous>)
    at mapper (/root/repo/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at promise.then (/root/repo/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
Environment toWebpackConfig should return default resolve.modules with additions - Environment toWebpackConfig should return default resolve.modules with additions
Error: expect(received).toEqual(expected) // deep equality

- Expected
+ Received

  Array [
    "/root/repo/app/javascript",
-   "/root/repo/app/assets",
-   "/etc/yarn",
    "node_modules",
  ]
    at Object.toEqual (/root/repo/vendor/bundle/ruby/2.5.0/gems/webpacker-4.0.7/package/environments/__tests__/base.js:59:38)
    at Object.asyncJestTest (/root/repo/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at resolve (/root/repo/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
    at new Promise (<anonymous>)
    at mapper (/root/repo/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at promise.then (/root/repo/node_modules/jest-jasmine2/build/queueRunner.js:73:41)

```

**Comment by olgaboiar** [comment]
Not fixing the problem, but a workaround which helped me to have a successful build with the same issue as you've mentioned: add those tests from `webpacker-4.0.7/package/__tests__/` to Jest's testPathIgnorePatterns. In your `package.json` :
` "jest": {
    "testPathIgnorePatterns": [
      "/root/repo/vendor/bundle/ruby/2.5.0/gems/webpacker-4.0.7/"
    ]
  }`

**Comment by Dujota** [comment]
@olgaboiar Thank you for the response. 

I ended up figuring out how to get it done without any workarounds by combing through the webpack and jest docs. 

in short the solution is to configure jest (i chose inside the package.json) to be aware of module extentsions and directories and let it know where the roots was. 
```
"jest": {
    "roots": [
      "<rootDir>/spec/components/"
    ],
    "setupFilesAfterEnv": [
      "<rootDir>/spec/components/setup_tests.js"
    ],
    "verbose": true,
    "testURL": "http://localhost:3000",
    "reporters": [
      "default",
      "jest-junit"
    ],
    "coverageDirectory": "./",
    "collectCoverageFrom": [
      "**/*.{jsx}",
      "!**/node_modules/**",
      "!**/vendor/**"
    ],
    "moduleFileExtensions": [
      "js",
      "json",
      "jsx"
    ],
    "moduleDirectories": [
      "node_modules",
      "<rootDir>/app/javascript"
    ]
  }
```
