### ISSUE TITLE
Using webpack-dev-server for tests

### ISSUE THREAD

**Issue by ghost** [rails/webpacker#2163]
Is it possible to use webpack-dev-server for tests? We have a fair bit of JavaScript, and this could shave a considerable amount of seconds off when running tests after changing the .js files.

I have invested several hours into trying to make this work without any luck.

I get an error like this, which looks like the Rails server instance fails requesting the .js file from the webpack-dev-server:

```
     1.2) Failure/Error: if @socket.closed?

          NoMethodError:
            undefined method `closed?' for nil:NilClass

          [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_terms_show_renders_the_page_454.png


          # /home/dev/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/http.rb:1535:in `begin_transport'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/rack-proxy-0.6.5/lib/net_http_hacked.rb:50:in `begin_request_hacked'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/rack-proxy-0.6.5/lib/rack/http_streaming_response.rb:60:in `response'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/rack-proxy-0.6.5/lib/rack/http_streaming_response.rb:29:in `headers'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:120:in `perform_request'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/webpacker-4.0.7/lib/webpacker/dev_server_proxy.rb:27:in `perform_request'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/rack-2.0.7/lib/rack/urlmap.rb:68:in `block in call'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `each'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `call'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/capybara-3.25.0/lib/capybara/server/middleware.rb:48:in `call'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
          # /home/dev/.rvm/gems/ruby-2.5.5/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

My `webpacker.yml` looks like this:
```
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .jsx
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Verifies that correct packages and versions are installed by inspecting package.json, yarn.lock, and node_modules
  check_yarn_integrity: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 2902
    public: localhost:2902
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  source_entry_path: packs
  public_output_path: packs

  dev_server:
    https: false
    host: localhost
    port: 2902
    public: localhost:2902
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true

staging:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true
```

**Comment by PhilCoggins** [comment]
@vitobotta Thanks for this solution! I've been considering utilizing `webpack-dev-server` for our system tests as well, and basically the only thing preventing this is the differing `public_output_path`. It makes me wonder, what is the purpose of having a separate output path by default for test environment? Presumably this was chosen as a default for _some_ reason.

In the past year since you posted this, have you encountered any issues with changing the output path to be identical to development? I'd love to hear about any gotchas that you've encountered since making this change.

**Comment by vitobotta** [comment]
Hi @PhilCoggins ! No issues at all, I am still using this approach and it works great :)

**Comment by PhilCoggins** [comment]
@vitobotta Thanks for the response. I'm shipping this for our application today.

Note I am leaving `compile: true` and instead add:

```
```

**Comment by feliperaul** [comment]
@PhilCoggins Phil, could you share your entire webpacker.yml file?

Also, I didn't quite understand how exactly you start `./webpack-dev-server`; you can't start it twice (once for development and once for the test environment), obviously, so how exactly is your setup?

**Comment by dmolesUC** [comment]
@feliperaul You can start it twice, you just need to configure different ports and output paths. Omitting unrelated settings:

```yml
development:
  dev-server:
    port: 3035
    public: localhost:3035
  public_output_path: packs

test:
  dev-server:
    port: 3135
    public: localhost:3135
  public_output_path: packs-test
```

Note: I'm not convinced this is the best way to do it, and I'm only doing it because using the same output path for dev and test wasn't working for me. (I didn't investigate in detail, but it seemed like `javascript_pack_tag` in test wasn't producing the right hashes, or was using stale hashes, or something.) But at any rate, it can be done.
