### ISSUE TITLE
Error: Cannot find module 'webpack' with ./bin/webpack-dev-server

### ISSUE THREAD

**Issue by JohnMerlino2** [rails/webpacker#2167]
I am trying to run webpack-dev-server. I am using Rails 5.2.3 and Webpacker 4.0.7. The only support ticket I found on this is here https://github.com/rails/webpacker/issues/1295. But I also tried running: yarn add webpack-cli -D 

But still I get this error:

```
$ ./bin/webpack-dev-server
module.js:515
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/viggy/projects/vigtorious/node_modules/webpack-dev-server/bin/webpack-dev-server.js:12:17)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```

**Comment by jakeNiemiec** [comment]
I am sorry, you cannot use `webpack-cli` with webpacker. They are both webpack wrappers. 

Instead, call `./bin/webpack` like you would for the cli.

**Comment by jakeNiemiec** [comment]
Try this:

- delete your `yarn.lock` file.
- delete `node_modules`
- `yarn install`
