### ISSUE TITLE
How can I make webpack compile all file in the `packs` folder

### ISSUE THREAD

**Issue by ankitrg** [rails/webpacker#226]
Currently, only the top level files are compiled and not the files inside the sub folder. How can I make the watcher look for any of the files?

**Comment by ytbryan** [comment]
> Currently, only the top level files are compiled and not the files inside the sub folder.

Can you give a reproduction?

**Comment by ytbryan** [comment]
There is a PR for it https://github.com/rails/webpacker/pull/201

**Comment by ankitrg** [comment]
Will I be able to gracefully upgrade these new changes to my webpacker once the PR is merged?

**Comment by ytbryan** [comment]
Assuming you are using webpacker 1.1+, It's just modification to shared.js. Hence you will need to rerun `rails webpacker:install` 

Alternatively, you can copy this commit (https://github.com/rails/webpacker/pull/201/files) to your shared.js and start using it.

**Comment by gauravtiwari** [comment]
If you re-run installer later it will ignore the files if they are identical so, you can just add it as @ytbryan suggested and re-run installer whenever the gem gets updated.

**Comment by ytbryan** [comment]
The PR has been merged. Please consider closing this.

**Comment by ankitrg** [comment]
I get the following error when I replace the shared.js with the changes in the pr:

```
94% asset optimizationpath.js:7              
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at ManifestPlugin.<anonymous> (/home/aks/playground/forme/node_modules/webpack-manifest-plugin/lib/plugin.js:108:29)
    at Compiler.applyPluginsAsyncSeries (/home/aks/playground/forme/node_modules/tapable/lib/Tapable.js:142:13)
    at Compiler.emitAssets (/home/aks/playground/forme/node_modules/webpack/lib/Compiler.js:303:7)
    at onCompiled (/home/aks/playground/forme/node_modules/webpack/lib/Compiler.js:54:18)
    at /home/aks/playground/forme/node_modules/webpack/lib/Compiler.js:494:13
    at next (/home/aks/playground/forme/node_modules/tapable/lib/Tapable.js:138:11)
    at Compiler.<anonymous> (/home/aks/playground/forme/node_modules/webpack/lib/CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (/home/aks/playground/forme/node_modules/tapable/lib/Tapable.js:142:13)
    at /home/aks/playground/forme/node_modules/webpack/lib/Compiler.js:491:10
    at Compilation.applyPluginsAsyncSeries (/home/aks/playground/forme/node_modules/tapable/lib/Tapable.js:131:46)
    at self.applyPluginsAsync.err (/home/aks/playground/forme/node_modules/webpack/lib/Compilation.js:645:19)
    at next (/home/aks/playground/forme/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.compilation.plugin (/home/aks/playground/forme/node_modules/webpack/lib/ProgressPlugin.js:121:6)
    at Compilation.applyPluginsAsyncSeries (/home/aks/playground/forme/node_modules/tapable/lib/Tapable.js:142:13)
```

**Comment by gauravtiwari** [comment]
@ankitrg Please close this issue, this feature is in master now. You have to re-run `bundle exec rails webpacker:install` to replace to your current shared.js
