### ISSUE TITLE
webpacker 4.x vue-loader+sass-loader not working

### ISSUE THREAD

**Issue by Meekohi** [rails/webpacker#2282]
Trying (again) to upgrade from webpacker 3.5 to webpacker 4.x, but am unable to understand why webpack chokes on SASS inside VueJS single-file-components (SFC).

Maybe someone can help me parse what is going wrong here. All configs are default afaik.

This is the first error:

```
ERROR in ./app/javascript/src/components/OrganizerEventsCard.vue?vue&type=style&index=0&id=6c57e1c0&scoped=true&lang=sass& (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-2!./node_modules/sass-loader/dist/cjs.js??ref--4-3!./node_modules/vue-loader/lib??vue-loader-options!./app/javascript/src/components/OrganizerEventsCard.vue?vue&type=style&index=0&id=6c57e1c0&scoped=true&lang=sass&)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

$mobile-breakpoint: 800px
^
      Invalid CSS after "$mobile-breakpoint": expected 1 selector or at-rule, was ": 800px"
      in /Users/meekohi/scenethink/app/javascript/src/components/OrganizerEventsCard.vue (line 123, column 1)
    at runLoaders (/Users/meekohi/scenethink/node_modules/webpack/lib/NormalModule.js:313:20)
    at /Users/meekohi/scenethink/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/meekohi/scenethink/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/meekohi/scenethink/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/Users/meekohi/scenethink/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/Users/meekohi/scenethink/node_modules/neo-async/async.js:7974:18)
    at options.error (/Users/meekohi/scenethink/node_modules/node-sass/lib/index.js:294:32)
 @ ./app/javascript/src/components/OrganizerEventsCard.vue?vue&type=style&index=0&id=6c57e1c0&scoped=true&lang=sass& 1:0-484 1:500-503 1:505-986 1:505-986
 @ ./app/javascript/src/components/OrganizerEventsCard.vue
 @ ./node_modules/babel-loader/lib??ref--8-0!./node_modules/vue-loader/lib??vue-loader-options!./app/javascript/src/components/OrganizerEvents.vue?vue&type=script&lang=js&
 @ ./app/javascript/src/components/OrganizerEvents.vue?vue&type=script&lang=js&
 @ ./app/javascript/src/components/OrganizerEvents.vue
 @ ./app/javascript/packs/application.js
```

`OrganizerEventsCard.vue:`
```vue
<template>
...
</template>
<script>
...
</script>
<style scoped lang="sass">
$card-padding: 10px
$mobile-breakpoint: 800px
$phone-breakpoint: 500px
...
</style>
```

But maybe more interesting is this error:

```
ERROR in ./app/javascript/src/components/ui/BackgroundMask.vue?vue&type=style&index=0&id=6ae5e69d&lang=sass&scoped=true& (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-2!./node_modules/sass-loader/dist/cjs.js??ref--4-3!./node_modules/vue-loader/lib??vue-loader-options!./app/javascript/src/components/ui/BackgroundMask.vue?vue&type=style&index=0&id=6ae5e69d&lang=sass&scoped=true&)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

<template>
^
      Invalid CSS after "": expected 1 selector or at-rule, was ".background-mask  /"
      in /Users/meekohi/scenethink/app/javascript/src/components/ui/BackgroundMask.vue (line 1, column 1)
    at runLoaders (/Users/meekohi/scenethink/node_modules/webpack/lib/NormalModule.js:313:20)
    at /Users/meekohi/scenethink/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/meekohi/scenethink/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/meekohi/scenethink/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/Users/meekohi/scenethink/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/Users/meekohi/scenethink/node_modules/neo-async/async.js:7974:18)
    at options.error (/Users/meekohi/scenethink/node_modules/node-sass/lib/index.js:294:32)
 @ ./app/javascript/src/components/ui/BackgroundMask.vue?vue&type=style&index=0&id=6ae5e69d&lang=sass&scoped=true& 1:0-497 1:513-516 1:518-1012 1:518-1012
 @ ./app/javascript/src/components/ui/BackgroundMask.vue
 @ ./node_modules/babel-loader/lib??ref--8-0!./node_modules/vue-loader/lib??vue-loader-options!./app/javascript/src/components/EventPage.vue?vue&type=script&lang=js&
 @ ./app/javascript/src/components/EventPage.vue?vue&type=script&lang=js&
 @ ./app/javascript/src/components/EventPage.vue
 @ ./app/javascript/packs/eventpages.js
```

This looks to me like almost like sass-loader failed to stop parsing at the `</style>` in `BackgroundMask.vue` and just kept going to the next file?

`EventPage.vue`
```
<script>
  import BackgroundMask from 'src/components/ui/BackgroundMask'
  import IconLocation from "src/components/ui/icons/IconLocation"
```

Anyway, looking for any possible advice or insight into what is happening.

```
Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
Rails: 5.2.2.1
Webpacker: 4.0.7
Node: v10.16.0
Yarn: 1.17.3

@rails/webpacker: 
scenethink@ /Users/meekohi/scenethink
└── @rails/webpacker@4.0.7 

Is bin/webpack present?: true
Is bin/webpack-dev-server present?: true
Is bin/yarn present?: true
```

**Comment by Meekohi** [comment]
`config/webpack/environment.js`
```js
const webpack = require('webpack')
const { environment } = require('@rails/webpacker')
const { VueLoaderPlugin } = require('vue-loader')
const vue = require('./loaders/vue')

environment.plugins.prepend('VueLoaderPlugin', new VueLoaderPlugin())
environment.loaders.prepend('vue', vue)

environment.plugins.append(
  'Globals', // arbitrary name
   new webpack.ProvidePlugin({
     $: 'jquery',
     _: 'underscore'
   })
);

module.exports = environment
```

`config/webpack/loaders/vue.js`
```js
const { dev_server: devServer } = require('@rails/webpacker').config

const isProduction = process.env.NODE_ENV === 'production'
const inDevServer = process.argv.find(v => v.includes('webpack-dev-server'))
const extractCSS = !(inDevServer && (devServer && devServer.hmr)) || isProduction

module.exports = {
  test: /\.vue(\.erb)?$/,
  use: [{
    loader: 'vue-loader',
    options: { extractCSS }
  }]
}
```

**Comment by somazx** [comment]
I'm in the process of upgrading from Rails v5.2 to 6. I'm running into the same issue since migrating. Suddenly SFC style components with script type="scss" aren't generating any css when the page renders in development.

Works in production however.

**Comment by somazx** [comment]
@Meekohi I found the [solution](https://stackoverflow.com/questions/56978950/stylesheet-pack-tag-not-generating-any-output-although-the-css-file-is-present/56987710#56987710) for me anyway, maybe it'll help you also.

In short change your loader/vue.js to this:

```javascript
module.exports = {
  test: /\.vue(\.erb)?$/,
  use: [
    {
      loader: "vue-loader",
      options: { extract_css: true },
    },
  ],
};
```

**Comment by guillaumebriday** [comment]
thanks @somazx

**Comment by elevatedsherlock674** [comment]
> `config/webpack/environment.js`
> 
> const webpack = require('webpack')
> const { environment } = require('@rails/webpacker')
> const { VueLoaderPlugin } = require('vue-loader')
> const vue = require('./loaders/vue')
> 
> environment.plugins.prepend('VueLoaderPlugin', new VueLoaderPlugin())
> environment.loaders.prepend('vue', vue)
> 
> environment.plugins.append(
>   'Globals', // arbitrary name
>    new webpack.ProvidePlugin({
>      $: 'jquery',
>      _: 'underscore'
>    })
> );
> 
> module.exports = environment
> `config/webpack/loaders/vue.js`
> 
> const { dev_server: devServer } = require('@rails/webpacker').config
> 
> const isProduction = process.env.NODE_ENV === 'production'
> const inDevServer = process.argv.find(v => v.includes('webpack-dev-server'))
> const extractCSS = !(inDevServer && (devServer && devServer.hmr)) || isProduction
> 
> module.exports = {
>   test: /\.vue(\.erb)?$/,
>   use: [{
>     loader: 'vue-loader',
>     options: { extractCSS }
>   }]
> }





https://eslint-plugin-vue-duane.github.io/vuLUAtsrfaW1zEhACD0qZU/
