### ISSUE TITLE
ExecJS::ProgramError: Unexpected token

### ISSUE THREAD

**Issue by AndrewRayCode** [rails/webpacker#2293]
Running `bundle exec rake assets:precompile` returns:

```
rake aborted!
ExecJS::ProgramError: Unexpected token: operator (>) (line: 165424, col: 37, pos: 6796176)

Error
    at new JS_Parse_Error (/tmp/execjs20190920-14022-swl9bbjs:3572:11870)
    at js_error (/tmp/execjs20190920-14022-swl9bbjs:3572:12089)
    at croak (/tmp/execjs20190920-14022-swl9bbjs:3572:20898)
    at token_error (/tmp/execjs20190920-14022-swl9bbjs:3572:21035)
    at unexpected (/tmp/execjs20190920-14022-swl9bbjs:3572:21123)
    at expr_atom (/tmp/execjs20190920-14022-swl9bbjs:3572:29660)
    at maybe_unary (/tmp/execjs20190920-14022-swl9bbjs:3573:143)
    at expr_ops (/tmp/execjs20190920-14022-swl9bbjs:3573:901)
    at maybe_conditional (/tmp/execjs20190920-14022-swl9bbjs:3573:993)
    at maybe_assign (/tmp/execjs20190920-14022-swl9bbjs:3573:1436)
new JS_Parse_Error ((execjs):3572:11870)
js_error ((execjs):3572:12089)
croak ((execjs):3572:20898)
token_error ((execjs):3572:21035)
unexpected ((execjs):3572:21123)
expr_atom ((execjs):3572:29660)
maybe_unary ((execjs):3573:143)
expr_ops ((execjs):3573:901)
maybe_conditional ((execjs):3573:993)
maybe_assign ((execjs):3573:1436)
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:21:in `eval'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:46:in `call'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/uglifier-3.0.0/lib/uglifier.rb:176:in `run_uglifyjs'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/uglifier-3.0.0/lib/uglifier.rb:139:in `compile'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/compressing.rb:65:in `block in js_compressor='
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/legacy_proc_processor.rb:31:in `call'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/home/circleci/project/vendor/cache/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/bundle/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/bundle/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
/usr/local/bundle/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/bundle/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/bundle/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
/usr/local/bundle/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

It's not clear which source JS is causing this compilation to fail

**Comment by jakeNiemiec** [comment]
ExecJS looks like it's trying to parse its own output. It looks to be outside the scope of what webpacker can fix. You might have better luck making an issue in the sprockets or ExecJS repos.
