### ISSUE TITLE
TypeError: no implicit conversion of Hash into String (Assets clean)

### ISSUE THREAD

**Issue by gauravtiwari** [rails/webpacker#2310]
Getting the following error on heroku when using assets:clear (on master)

```rb
 TypeError: no implicit conversion of Hash into String
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/webpacker/commands.rb:10:in `join'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/webpacker/commands.rb:10:in `block in clean'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/webpacker/commands.rb:10:in `map'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/webpacker/commands.rb:10:in `clean'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/webpacker.rb:27:in `clean'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/tasks/webpacker/clean.rake:6:in `block (2 levels) in <main>'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/bundler/gems/webpacker-d2b26d6414da/lib/tasks/webpacker/clean.rake:13:in `block in <main>'
       /tmp/build_5a23c3ef22cab61f9db5aced78944d8c/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
````

related #1410

**Comment by LuanGB** [comment]
I have added a PR to fix this issue, including some minimal testing for it.
