### ISSUE TITLE
Compilation of .vue.erb file with image_pack_path/asset_pack_path hangs

### ISSUE THREAD

**Issue by jpdimond** [rails/webpacker#2320]
I am trying to get images in my Webpacker folder into my vue components (not using sprockets at all.) I have rails-erb-loader installed and working. When I put the following in my vue.erb component, the webpack compilation hangs. I have tried a variety of paths to the image, and currently it lives in /app/webpacker/images/pause.svg
I also tried to just require Webpacker::Helper and it hangs as well. Is there something I am not doing?

_ProgressBar.vue.erb_
```Webpacker::Helper.image_pack_tag("pause.svg")```

_config/webpack/loaders/erb.js_
```
module.exports = {
  test: /\.erb$/,
  enforce: 'pre',
  exclude: /node_modules/,
  use: [{
    loader: 'rails-erb-loader',
    options: {
      runner: (/^win/.test(process.platform) ? 'ruby ' : '') + 'bin/rails runner'
    }
  }]
}
```

Here is the stacktrace when I cancel the process:
```bin/webpack
^C#<Thread:0x00007fed43f05bd0@/Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/open3.rb:287 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/open3.rb:287:in `block (2 levels) in capture3'
/Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/open3.rb:287:in `read': stream closed in another thread (IOError)
#<Thread:0x00007fed43f05a40@/Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/open3.rb:288 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/open3.rb:288:in `block (2 levels) in capture3'
/Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/open3.rb:288:in `read': stream closed in another thread (IOError)

Traceback (most recent call last):
	37: from bin/rails:4:in `<main>'
	36: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `require'
	35: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:288:in `load_dependency'
	34: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `block in require'
	33: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	32: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	31: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	30: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	29: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	28: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc2/lib/rails/commands.rb:18:in `<main>'
	27: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc2/lib/rails/command.rb:46:in `invoke'
	26: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc2/lib/rails/command/base.rb:65:in `perform'
	25: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	24: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	23: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	22: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc2/lib/rails/commands/runner/runner_command.rb:42:in `perform'
	21: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	20: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	19: from /Users/jpdimond/Development/shora-mod-prototype/node_modules/rails-erb-loader/erb_transformer.rb:19:in `<main>'
	18: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/erb.rb:901:in `result'
	17: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/erb.rb:901:in `eval'
	16: from (erb):13:in `<main>'
	15: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/webpacker-4.0.7/lib/webpacker/helper.rb:50:in `image_pack_tag'
	14: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/webpacker-4.0.7/lib/webpacker/helper.rb:146:in `resolve_path_to_image'
	13: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/webpacker-4.0.7/lib/webpacker/manifest.rb:49:in `lookup!'
	12: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/webpacker-4.0.7/lib/webpacker/manifest.rb:42:in `lookup'
	11: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/webpacker-4.0.7/lib/webpacker/manifest.rb:58:in `compile'
	10: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc2/lib/active_support/tagged_logging.rb:80:in `tagged'
	 9: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc2/lib/active_support/tagged_logging.rb:28:in `tagged'
	 8: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
	 7: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/webpacker-4.0.7/lib/webpacker/manifest.rb:58:in `block in compile'
	 6: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/webpacker-4.0.7/lib/webpacker/compiler.rb:21:in `compile'
	 5: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/webpacker-4.0.7/lib/webpacker/compiler.rb:61:in `run_webpack'
	 4: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/open3.rb:281:in `capture3'
	 3: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/open3.rb:101:in `popen3'
	 2: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/open3.rb:219:in `popen_run'
	 1: from /Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/open3.rb:298:in `block in capture3'
/Users/jpdimond/.rbenv/versions/2.6.0/lib/ruby/2.6.0/open3.rb:298:in `value': Interrupt```

**Comment by jpdimond** [comment]
I confirmed that this is not an issue with my particular project. I made a new rails project with bare bones webpacker and vue here: https://github.com/jpdimond/rails-vuejs
Looks like the image_pack_path or asset_pack_path does not work at all in vue erb files at all.

**Comment by mroliveira7** [comment]
+1 I'm having the same issue. I installed the .erb loader and now the compilation won't finish.
This question on stackoverflow points the same error: https://stackoverflow.com/questions/57942674/adding-rails-erb-loader-breaks-webpacker
