### ISSUE TITLE
Cryptic Webpacker::Manifest::MissingEntryError when webpack-dev-server is running on same port elsewhere

### ISSUE THREAD

**Issue by henrik** [rails/webpacker#2378]
Based on https://github.com/rails/webpacker/issues/1730#issuecomment-559047033.

I got a "Webpacker::Manifest::MissingEntryError" error trying to load a page, and the suggested things to try did not cover the actual problem – the port webpack-dev-server wants to use was taken.

I can see a few different ways of improving this:

* Just mention this as another thing to check in the error message
* More generally, catch this error and similar errors and report those to the user
* Make the error not happen by magically using a port that is free

Any thoughts?

**Comment by rossta** [comment]
As someone who is often jumping between multiple projects, I also get tripped up by this from time-to-time. 

I like the idea of magically using a free port. I believe this is how the managed webpack dev server with Vue CLI behaves. For Webpacker, I anticipate this would require a disruptive change given the port is currently baked into generated config and teams may have some hard-coded assumptions: https://github.com/rails/webpacker/blob/c7292e9a1e158e5fc9ec3026256cf7a42d70f549/lib/install/config/webpacker.yml#L62-L63

Perhaps a helpful error message would be a good way to start.

**Comment by viktorianer** [comment]
I spend hours on similar problem today -_-. But, @henrik describing only part of the problem, so I will add some information.

**Problem**:

1. Create a new Rails app, e.g.: `rails new sample_app`
2. You can also add `stylesheet_pack_tag` to your `app/views/layouts/application.html.erb`, to see more errors (e.g. [adding Bootstrap](https://www.timdisab.com/installing-bootstrap-4-on-rails-6/)), but it is not necessary.
3. Creating one "test" controller, views & routes (e.g. as suggested in Bootstrap tutorial)
4. Start server: `rails server`
5. Visit the route and you get a `ActionView::Template::Error`

```
Started GET "/" for ::1 at 2020-05-17 21:00:37 +0200
   (0.7ms)  SELECT sqlite_version(*)
Processing by PostController#index as HTML
  Rendering post/index.html.erb within layouts/application
  Rendered post/index.html.erb within layouts/application (Duration: 1.2ms | Allocations: 202)
Completed 500 Internal Server Error in 64ms (ActiveRecord: 0.0ms | Allocations: 21163)
  
ActionView::Template::Error (Webpacker can't find application in ../sample_app/public/packs/manifest.json. Possible causes:
```

Which is true, the `manifest.json` ist note served. But it is cryptic or simply not the real problem.

**Investigation**

OK...Now, I started to investigate.
First, startet `./bin/webpack-dev-server` to see the output. But, it is just fine!

```
./bin/webpack-dev-server
./bin/webpack-dev-serverℹ ｢wds｣: Project is running at http://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /Users/viktorianer/Documents/Projekte/aufgaben/sample_app/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: Hash: f07b95b7bb049c8d4afe
Version: webpack 4.43.0
Time: 5480ms
Built at: 05/17/2020 9:01:26 PM
                                     Asset       Size       Chunks                         Chunk Names
    js/application-604f974fbe62d13596c5.js   1.68 MiB  application  [emitted] [immutable]  application
js/application-604f974fbe62d13596c5.js.map   1.86 MiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]              
ℹ ｢wdm｣: Compiled successfully.
```

But still, nothing is working... But now I getting different error:

```
app/views/layouts/application.html.erb:10
Started GET "/" for ::1 at 2020-05-17 21:01:29 +0200
Processing by PostController#index as HTML
  Rendering post/index.html.erb within layouts/application
  Rendered post/index.html.erb within layouts/application (Duration: 0.0ms | Allocations: 5)
Completed 200 OK in 8ms (Views: 5.1ms | ActiveRecord: 0.0ms | Allocations: 5025)

2020-05-17 21:01:29 +0200: Rack app error handling request { GET /packs/js/application-604f974fbe62d13596c5.js }
#<EOFError: end of file reached>
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/net_http_hacked.rb:53:in `begin_request_hacked'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/http_streaming_response.rb:60:in `response'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/http_streaming_response.rb:29:in `headers'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:120:in `perform_request'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/dev_server_proxy.rb:21:in `perform_request'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3/lib/rails/engine.rb:527:in `call'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/configuration.rb:228:in `call'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:682:in `handle_request'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:472:in `process_client'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:328:in `block in run'
/Users/viktorianer/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

Which creates even more confusion than the error before. I also described this issue in a new created Rails app using template, but [without Spockets and without assets pipeline](https://github.com/dao42/rails-template/pull/27#issuecomment-629826199). 
 
After hours I discovered [this old issue](https://github.com/rails/webpacker/issues/772) and changed `host` from  `localhost` to `0.0.0.0` in `config/webpacker.yml`. 

Now I got the real error and the cause of this problem!

```./bin/webpack-dev-server
./bin/webpack-dev-serverAnother program is running on port 3035. Set a new port in  for dev_server
```

On my Mac I run several projects in Docker and there I do not have problems running several Webpacker in parallel. But for this case I did not use Docker. But some of projects was running in background, using this port! 

**Solution**

Stop the running Webpacker server in Docker or even locally.

@gauravtiwari Thank you for saving me more investigation hours 👍
