### ISSUE TITLE
Module import only full path to index.js

### ISSUE THREAD

**Issue by exdeniz** [rails/webpacker#2394]
Try import 
```import { createOvermind } from 'overmind'```
```
webpacker_1  | ERROR in ./app/javascript/packs/pages/stats-transfer.js 18:22-36
webpacker_1  | "export 'createOvermind' was not found in 'overmind'
webpacker_1  |     at HarmonyImportSpecifierDependency._getErrors (/app/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
webpacker_1  |     at HarmonyImportSpecifierDependency.getErrors (/app/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
webpacker_1  |     at Compilation.reportDependencyErrorsAndWarnings (/app/node_modules/webpack/lib/Compilation.js:1463:22)
webpacker_1  |     at hooks.finishModules.callAsync.err (/app/node_modules/webpack/lib/Compilation.js:1258:10)
webpacker_1  |     at AsyncSeriesHook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
webpacker_1  |     at AsyncSeriesHook.lazyCompileHook (/app/node_modules/tapable/lib/Hook.js:154:20)
webpacker_1  |     at Compilation.finish (/app/node_modules/webpack/lib/Compilation.js:1253:28)
webpacker_1  |     at hooks.make.callAsync.err (/app/node_modules/webpack/lib/Compiler.js:672:17)
webpacker_1  |     at _done (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
webpacker_1  |     at _err8 (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:116:22)
```
change to
```
import { createOvermind } from 'overmind/lib/index.js'
```
and this work.

**Comment by jakeNiemiec** [comment]
You might need to use this in order to get `import { createOvermind } from 'overmind'` to work: https://github.com/rails/webpacker/blob/54c3ca9245e9ee330f8ca63b447c202290f7b624/docs/v4-upgrade.md#excluding-node_modules-from-being-transpiled-by-babel-loader
