### ISSUE TITLE
[Question] Is it possible to change package.json + node_modules directory?

### ISSUE THREAD

**Issue by lucasmedeirosleite** [rails/webpacker#2445]
Hi!

I'm wondering if it is possible to move:
- `package.json`
- `yarn.lock`
- `node_modules`

To another folder.

E.g

```
app/
config/
  webpack/
  webpacker.yml
frontend/
  admin/
    packs/
      application.json
  node_modules/
  package.json
  yarn.lock
```

I know I can move the `source_path` easily through the `webpacker.yml`, but I'm having trouble with
the `package.json` and the `node_modules` directory

**Comment by justin808** [comment]
@lucasmedeirosleite This should probably be better documented.

Try setting the ENV value `WEBPACKER_NODE_MODULES_BIN_PATH` to the absolute path of your frontend directory. I haven't tried it. That might work.

See
* https://github.com/rails/webpacker/pull/1450
* https://github.com/rails/webpacker/blob/5b481bd710211b6a517da72f30cc3ec76fb35519/lib/webpacker/runner.rb#L13

**Comment by oshanz** [comment]
I have set the ENV variable. then got this error
 ```
$ ./bin/webpack-dev-server 
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '@rails/webpacker'
Require stack:
- /app/config/webpack/environment.js
- /app/config/webpack/development.js
- /opt/node_modules/webpack-cli/bin/utils/convert-argv.js
- /opt/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/config/webpack/environment.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/config/webpack/environment.js',
    '/app/config/webpack/development.js',
    '/opt/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/opt/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
```
