### ISSUE TITLE
Errors when trying to install ERB integration

### ISSUE THREAD

**Issue by elsurudo** [rails/webpacker#2519]
Hi,

Following the instructions [here](https://github.com/rails/webpacker/blob/master/docs/integrations.md#erb), I am trying to install the erb loader.

Unfortunately, when I run `bundle exec rails webpacker:install:erb`, I get the following:

```
Traceback (most recent call last):
	16: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	15: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
	13: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler.rb:107:in `setup'
	12: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/runtime.rb:20:in `setup'
	11: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/runtime.rb:108:in `block in definition_method'
	10: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/definition.rb:226:in `requested_specs'
	 9: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
	 8: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/definition.rb:170:in `specs'
	 7: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `materialize'
	 6: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `map!'
	 5: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/spec_set.rb:88:in `block in materialize'
	 4: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/lazy_specification.rb:76:in `__materialize__'
	 3: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/source/git.rb:167:in `specs'
	 2: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/source/path.rb:100:in `local_specs'
	 1: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/source/git.rb:200:in `load_spec_files'
/Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/source/path.rb:198:in `load_spec_files': The path `/Users/elsurudo/Development/Projects/Project/bundler/gems/memory_profiler-191a06885bc8` does not exist. (Bundler::PathError)
	16: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	15: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
	13: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler.rb:107:in `setup'
	12: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/runtime.rb:20:in `setup'
	11: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/runtime.rb:108:in `block in definition_method'
	10: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/definition.rb:226:in `requested_specs'
	 9: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
	 8: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/definition.rb:170:in `specs'
	 7: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `materialize'
	 6: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/spec_set.rb:85:in `map!'
	 5: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/spec_set.rb:88:in `block in materialize'
	 4: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/lazy_specification.rb:76:in `__materialize__'
	 3: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/source/git.rb:167:in `specs'
	 2: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/source/path.rb:100:in `local_specs'
	 1: from /Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/source/git.rb:199:in `load_spec_files'
/Users/elsurudo/.rbenv/versions/2.6.4/lib/ruby/2.6.0/bundler/source/git.rb:203:in `rescue in load_spec_files': https://github.com/SamSaffron/memory_profiler.git (at master@191a068) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/
```

My bundle is up-to-date, and yarn is installed and working. Any ideas?

**Comment by elsurudo** [comment]
I generated a new app and ran it, which worked. I copied the config over and resolved this particular error. Now I have another error :)
