### ISSUE TITLE
TypeScript emitted no output for .scss.d.ts.

### ISSUE THREAD

**Issue by akoskm** [rails/webpacker#2554]
```
ERROR in ./app/javascript/packs/components/table/test.module.scss.d.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: ENOENT: no such file or directory, open '/Users/akoskm/Projects/webapp/app/javascript/packs/components/table/test.module.scss.d.ts'

ERROR in /Users/akoskm/Projects/webapp/app/javascript/packs/components/table/table_actions.tsx
./app/javascript/packs/components/table/table_actions.tsx
[tsl] ERROR in /Users/akoskm/Projects/webapp/app/javascript/packs/components/table/table_actions.tsx(2,25)
      TS2307: Cannot find module './test.module.scss'.
```

the readme suggest the following https://github.com/rails/webpacker/blob/master/docs/css.md#import-scoped-styles-into-your-typescript-app

After I do what's suggested and run tsm:
```
% yarn watch-typings
yarn run v1.22.4
$ yarn run tsm app/javascript/packs/**/*.scss -w
$ /Users/akoskm/Projects/webapp/node_modules/.bin/tsm 'app/javascript/packs/**/*.scss' -w
Watching files...
[ADDED] app/javascript/packs/components/table/test.module.scss
[GENERATED TYPES] app/javascript/packs/components/table/test.module.scss.d.ts
```

now I have the following output from `bundle exec bin/webpack-dev-server`:
```
ERROR in ./app/javascript/packs/components/table/test.module.scss.d.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /Users/akoskm/Projects/webapp/app/javascript/packs/components/table/test.module.scss.d.ts.
    at makeSourceMapAndFinish (/Users/akoskm/Projects/webapp/node_modules/ts-loader/dist/index.js:80:15)
    at successLoader (/Users/akoskm/Projects/webapp/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/Users/akoskm/Projects/webapp/node_modules/ts-loader/dist/index.js:22:12)
```

**Comment by akoskm** [comment]
So the closest thing I could get to is to have my scss modules in `app/javascript/styles`.

When the scss module is there I don't see the `TypeScript emitted no output for` error anymore, however, this organization kind of destroys the purpose of the css-modules.

The whole point was to have a component and its style in the same folder 🤷‍♀️ .

**Comment by guillaumebriday** [comment]
Is this still an issue?

Feel free to reopen if needed
