### ISSUE TITLE
Error: Cannot find module '@rails/webpacker'

### ISSUE THREAD

**Issue by anon987654321** [rails/webpacker#2572]
Maybe someone here can help?
```
% node -v
v12.16.1
% npm -v
6.13.4
% yarn -v
1.22.4
% rails webpacker:compile
Compiling...
Compilation failed:
/home/dev/myapp/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: Cannot find module '@rails/webpacker'
Require stack:
- /home/dev/myapp/config/webpack/environment.js
- /home/dev/myapp/config/webpack/production.js
- /home/dev/myapp/node_modules/webpack-cli/bin/utils/convert-argv.js
- /home/dev/myapp/node_modules/webpack-cli/bin/cli.js
- /home/dev/myapp/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (/home/dev/myapp/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/dev/myapp/config/webpack/environment.js:1:87)
    at Module._compile (/home/dev/myapp/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (/home/dev/myapp/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/dev/myapp/config/webpack/production.js:3:21)
    at Module._compile (/home/dev/myapp/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (/home/dev/myapp/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/dev/myapp/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/home/dev/myapp/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /home/dev/myapp/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/dev/myapp/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /home/dev/myapp/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/dev/myapp/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/dev/myapp/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/dev/myapp/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/dev/myapp/config/webpack/environment.js',
    '/home/dev/myapp/config/webpack/production.js',
    '/home/dev/myapp/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/home/dev/myapp/node_modules/webpack-cli/bin/cli.js',
    '/home/dev/myapp/node_modules/webpack/bin/webpack.js'
  ]
}
```
- - -
```
% gem list | grep webpack
webpacker (5.1.1)
% yarn list | grep webpack
├─ terser-webpack-plugin@1.4.3
│  ├─ webpack-sources@^1.4.0
├─ webpack-cli@3.3.11
├─ webpack-dev-middleware@3.7.2
│  └─ webpack-log@^2.0.0
├─ webpack-dev-server@3.10.3
│  ├─ webpack-dev-middleware@^3.7.2
│  ├─ webpack-log@^2.0.0
├─ webpack-log@2.0.0
├─ webpack-sources@1.4.3
├─ webpack@4.43.0
│  ├─ terser-webpack-plugin@^1.4.3
│  └─ webpack-sources@^1.4.1
```

**Comment by smondal** [comment]
Can you please run `yarn install`

**Comment by guillaumebriday** [comment]
Did you run `yarn add @rails/webpacker` ? 

Feel free to close the issue if it's ok for you @anon987654321
