### ISSUE TITLE
webpack-dev-server freezes after failed compilation

### ISSUE THREAD

**Issue by bsboris** [rails/webpacker#2617]
I"m trying to replace Sprockets with Webpacker in new Rails app using this new [multi-file pack feature](https://github.com/rails/webpacker/blob/master/docs/css.md#importing-css-as-a-multi-file-pack-webpacker-v5). It works just fine when compiling on demand, but I encounter a strange bug with `webpack-dev-server`: it just stops working after failed compilation and stays frozen until restart.

Sample project can be found [here](https://github.com/bsboris/webpacker_bug.). And here are the steps to reproduce this bug from scratch:

1. Init new Rails app:
```
rails new webpacker_bug --skip-sprockets
cd webpacker_bug
```

2. Upgrade to Webpacker 5
```
gem 'webpacker', '~> 5.0'

bundle update webpacker
rails webpacker:binstubs
yarn upgrade @rails/webpacker --latest
yarn upgrade webpack-dev-server --latest
```

3. Add simple `packs/application.scss` file:
```
$red: #f00;
h1 {
  color: $red;
}
``` 

4. Add `stylesheet_pack_tag` to application layout:
```
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
```

5. Enable `extract_css` in config/webpacker.yml:
```
extract_css: true
```

6. Add basic controller, view and route for testing:
```
root to: "welcome#index"

class WelcomeController < ApplicationController
  def index; end
end

<h1>Hello, Webpack!</h1>
```

After this start rails app with `rails s`, start `webpacker-dev-server`. Both packs compiled successfully:
```
                                     Asset       Size       Chunks                         Chunk Names
              css/application-2df6622e.css   75 bytes  application  [emitted] [immutable]  application
          css/application-2df6622e.css.map  219 bytes  application  [emitted] [dev]        application
    js/application-c00dfc528478a4dcb648.js    507 KiB  application  [emitted] [immutable]  application
js/application-c00dfc528478a4dcb648.js.map    571 KiB  application  [emitted] [dev]        application
                             manifest.json  640 bytes               [emitted]
ℹ ｢wdm｣: Compiled successfully.
```

And here comes the bug. If i now introduce any error in application.scss (say, replace `$red` with `$$red`) it will fail to compile, as expected:
```
                                     Asset       Size       Chunks                         Chunk Names
    js/application-ad2260cc0f21568788f3.js    509 KiB  application  [emitted] [immutable]  application
js/application-ad2260cc0f21568788f3.js.map    571 KiB  application  [emitted] [dev]        application
                             manifest.json  492 bytes               [emitted]

ERROR in ./app/javascript/packs/application.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "  color:": expected expression (e.g. 1px, bold), was "$$red;"
        on line 4 of ~/Sites/webpacker_bug/app/javascript/packs/application.scss
>>   color: $$red;

   ---------^

    at ~/Sites/webpacker_bug/node_modules/webpack/lib/NormalModule.js:316:20
    at ~/Sites/webpacker_bug/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at ~/Sites/webpacker_bug/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (~/Sites/webpacker_bug/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (~/Sites/webpacker_bug/node_modules/sass-loader/dist/index.js:73:7)
    at Object.done [as callback] (~/Sites/webpacker_bug/node_modules/neo-async/async.js:8067:18)
    at options.error (~/Sites/webpacker_bug/node_modules/node-sass/lib/index.js:294:32)
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/src/index.js??ref--7-2!node_modules/sass-loader/dist/cjs.js??ref--7-3!app/javascript/packs/application.scss:

    ERROR in ./app/javascript/packs/application.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/packs/application.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: Invalid CSS after "  color:": expected expression (e.g. 1px, bold), was "$$red;"
            on line 4 of ~/Sites/webpacker_bug/app/javascript/packs/application.scss
    >>   color: $$red;

       ---------^

    SassError: SassError: Invalid CSS after "  color:": expected expression (e.g. 1px, bold), was "$$red;"
            on line 4 of ~/Sites/webpacker_bug/app/javascript/packs/application.scss
    >>   color: $$red;

       ---------^

        at Object.callback (~/Sites/webpacker_bug/node_modules/sass-loader/dist/index.js:73:16)
        at Object.done [as callback] (~/Sites/webpacker_bug/node_modules/neo-async/async.js:8067:18)
        at options.error (~/Sites/webpacker_bug/node_modules/node-sass/lib/index.js:294:32)
ℹ ｢wdm｣: Failed to compile.
```

But, it stays in this state forever. It won't compile after I fix this error. All I can do is ctrl-c out of it.

I don't know how to debug this further and I'm really confused.

**Comment by justin808** [comment]
Please try again with v6.
