### ISSUE TITLE
Outdated docs - CommonsChunkPlugin has been removed in favor of optimization.splitChunks

### ISSUE THREAD

**Issue by lucascaton** [rails/webpacker#2679]
Hi there.

I've just noticed that the `Plugins` section of [docs/webpack.md](https://github.com/rails/webpacker/blob/master/docs/webpack.md#plugins) doc suggests adding the following code to the `config/webpack/environment.js` file:

```js
new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor', // Vendor code
    minChunks: (module) => module.context && module.context.indexOf('node_modules') !== -1
  })
```

However, according to the [docs/v4-upgrade.md#splitchunks-configuration](https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md#splitchunks-configuration) doc:

> In Webpack v4, the CommonsChunkPlugin was removed in favor of optimization.splitChunks.

---

It'd be nice to update the first document as it's causing the following error:

`$ ./bin/webpack-dev-server`

```
./node_modules/webpack/lib/webpack.js:189
			throw new RemovedPluginError(errorMessage);
			^

RemovedPluginError: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
    at Object.get [as CommonsChunkPlugin] (./node_modules/webpack/lib/webpack.js:189:10)
    at Object.<anonymous> (./config/webpack/environment.js:26:24)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (./config/webpack/development.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30) {
  details: undefined,
  missing: undefined,
  origin: undefined,
  dependencies: undefined,
  module: undefined
}
```

**Comment by rossta** [comment]
@lucascaton Would you like to open a PR?
