### ISSUE TITLE
bin/webpack-dev-server 'Error: Cannot find module 'webpack/bin/config-yargs'

### ISSUE THREAD

**Issue by erikjenks** [rails/webpacker#268]
Any help on these issues would be gladly welcome! 

I started a new Rails app to test out webpacker and when running `./bin/webpack-dev-server` I receive an error:
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'webpack/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jenks/Desktop/Projects/webpacker-tester-app/node_modules/webpack-dev-server/bin/webpack-dev-server.js:46:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
I am using:
- Rails 5.1.0.rc1
- Ruby 2.4.0
- Node v7.7.3
- Yarn 0.16.1
- NPM 4.1.2

I tried creating multiple applications, using the `--webpack` flag, and the command `rails webpacker:install` and `rails webpacker:install:react`. 

When using the command line installer, I get `Webpacker successfully installed `. But, I do notice these warnings and errors:

```
error postcss-smart-import@0.6.11: The engine "yarn" is incompatible with this module. Expected version ">=0.17.0".
error Found incompatible module
warning Unmet peer dependency "webpack@^2.2.0".
warning Unmet peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
```

**Comment by gauravtiwari** [comment]
@erikjenks Can't reproduce this issue locally. Perhaps, this is related to yarn version you are using. Could you please try upgrading yarn and then try again?

```bash
gem install rails --pre
rails new webpacker-app --database postgresql --webpack -J -T
```

```bash
 ./bin/webpack-dev-server
```

**Comment by erikjenks** [comment]
That did it. Thanks. I didn't realize Yarn wasn't up to date. Closing this issue.
