### ISSUE TITLE
Webpacker v6.0.0.beta.1 - Error: Cannot find module 'sass'

### ISSUE THREAD

**Issue by holidayworking** [rails/webpacker#2829]
I'm trying Webpacker v6.0.0.beta.1 and I'm getting the following error:

```bash
$ ./bin/webpack
[webpack-cli] Error: Cannot find module 'sass'
Require stack:
- /app/node_modules/@rails/webpacker/package/rules/sass.js
- /app/node_modules/@rails/webpacker/package/rules/index.js
- /app/node_modules/@rails/webpacker/package/environments/base.js
- /app/node_modules/@rails/webpacker/package/index.js
- /app/config/webpack/base.js
- /app/config/webpack/development.js
- /app/node_modules/webpack-cli/lib/groups/resolveConfig.js
- /app/node_modules/webpack-cli/lib/webpack-cli.js
- /app/node_modules/webpack-cli/lib/bootstrap.js
- /app/node_modules/webpack-cli/bin/cli.js
- /app/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at /app/node_modules/@rails/webpacker/package/rules/sass.js:13:25
    at canProcess (/app/node_modules/@rails/webpacker/package/utils/helpers.js:34:12)
    at Object.<anonymous> (/app/node_modules/@rails/webpacker/package/rules/sass.js:7:18)
    at Module._compile (/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@rails/webpacker/package/rules/sass.js',
    '/app/node_modules/@rails/webpacker/package/rules/index.js',
    '/app/node_modules/@rails/webpacker/package/environments/base.js',
    '/app/node_modules/@rails/webpacker/package/index.js',
    '/app/config/webpack/base.js',
    '/app/config/webpack/development.js',
    '/app/node_modules/webpack-cli/lib/groups/resolveConfig.js',
    '/app/node_modules/webpack-cli/lib/webpack-cli.js',
    '/app/node_modules/webpack-cli/lib/bootstrap.js',
    '/app/node_modules/webpack-cli/bin/cli.js',
    '/app/node_modules/webpack/bin/webpack.js'
  ]
}
```

I'm adding sass and sass-lodaer to package.json. So I don't know why this error occurs.

**Comment by holidayworking** [comment]
When I ran yarn again, it was resolved,
