### ISSUE TITLE
Webpacker 6 and Yarn2

### ISSUE THREAD

**Issue by n-rodriguez** [rails/webpacker#2864]
## The problem

With :

* Yarn2 and [zero install](https://yarnpkg.com/features/zero-installs)
* webpacker 6
* webpack 5.11

when `webpack-assets-manifest` is enabled, it fails with error :

```sh
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ bin/webpack
(node:182479) UnhandledPromiseRejectionWarning: TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-3fcd8c6a0a/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/NormalModule.js:171:10)
    at WebpackAssetsManifest.handleCompilation (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-assets-manifest-virtual-a945d650af/0/cache/webpack-assets-manifest-npm-5.0.0-fe18b6af02-c93c6719e2.zip/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:729:18)
    at Hook.eval [as call] (eval at create (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:104:1)
    at Hook.CALL_DELEGATE [as _call] (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-5206174737/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/Compiler.js:988:26)
    at /home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-5206174737/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/Compiler.js:1029:29
    at Hook.eval [as callAsync] (eval at create (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/cache/tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-5206174737/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/Compiler.js:1024:28)
    at /home/nicolas/PROJECTS/CONCERTO/concerto/.yarn/$$virtual/webpack-virtual-5206174737/0/cache/webpack-npm-5.11.1-039bea8222-c3130daeaa.zip/node_modules/webpack/lib/Compiler.js:471:12
(Use `node --trace-warnings ...` to show where the warning was created)
(node:182479) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:182479) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

See also : https://github.com/webdeveric/webpack-assets-manifest/issues/122

The previous configuration was working :

* Yarn2 and [zero install](https://yarnpkg.com/features/zero-installs)
* webpacker 5.x (master branch)
* webpack 4.x

**Comment by n-rodriguez** [comment]
It works with :

```js
webpackConfig.plugins[3]['options']['enabled'] = false
```

but of course it doesn't generate `manifest.json`...

**Comment by n-rodriguez** [comment]
It works with Yarn 1.22 :

* delete `.yarnrc.yml`
* run `yarn install`
* run `bin/webpack`

```sh
icolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ yarn 
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > webpack-modernizr-loader@5.0.0" has incorrect peer dependency "webpack@^4.0.0".
warning "eslint-plugin-coffee > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
[4/4] Building fresh packages...
Done in 6.32s.
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ bin/webpack
assets by status 7.6 KiB [cached] 1 asset
assets by path media/ 8.14 MiB 98 assets
assets by status 23.7 MiB [emitted]
  assets by path js/ 23.1 MiB 13 assets
  asset css/concerto_back_office/application.css 631 KiB [emitted] (name: concerto_back_office/application) 1 related asset
  asset manifest.json 20.6 KiB [emitted]
assets by path css/emails/ 53.8 KiB
  assets by path css/emails/transactional/*.css 37.4 KiB 3 assets
  asset css/emails/newsletters/v2.css 12.1 KiB [compared for emit] (name: emails/newsletters/v2) 1 related asset
  asset css/emails/default.css 4.27 KiB [compared for emit] (name: emails/default) 1 related asset
assets by path css/concerto_france/*.css 701 KiB
  asset css/concerto_france/application.css 412 KiB [compared for emit] (name: concerto_france/application) 1 related asset
  asset css/concerto_france/jalis.css 290 KiB [compared for emit] (name: concerto_france/jalis) 1 related asset
asset css/concerto_back_office/devise.css 412 KiB [compared for emit] (name: concerto_back_office/devise) 1 related asset
asset css/concerto_espagne/application.css 338 KiB [compared for emit] (name: concerto_espagne/application) 1 related asset
orphan modules 177 KiB [orphan] 161 modules
runtime modules 20.8 KiB 48 modules
modules by path ./node_modules/ 13.2 MiB 538 modules
modules by path ./app/frontend/ 224 KiB (javascript) 2.09 MiB (css/mini-extract)
  cacheable modules 224 KiB 107 modules
  css modules 2.09 MiB
    modules by path ./app/frontend/styles/emails/ 53.6 KiB 5 modules
    modules by path ./app/frontend/styles/concerto_back_office/ 1.02 MiB 4 modules
    modules by path ./app/frontend/styles/concerto_france/ 701 KiB 3 modules
    modules by path ./app/frontend/styles/concerto_espagne/ 338 KiB 2 modules
./.modernizrrc.js 44.2 KiB [built] [code generated]
fs (ignored) 15 bytes [built] [code generated]
crypto (ignored) 15 bytes [optional] [built] [code generated]
stream (ignored) 15 bytes [built] [code generated]
webpack 5.11.1 compiled successfully in 22218 ms
```

**Comment by artempartos** [comment]
as a workaround - I did next thing:
- removed plugin:
`webpackConfig.plugins.splice(2, 1)` where 2 - is an index of your WebpackAssetsManifest plugin
- then added plugin manually
```
const customConfig = {
  plugins: [
    new WebpackAssetsManifest({
      enabled: true,
      entrypoints: true,
      writeToDisk: true,
      output: 'manifest.json',
      entrypointsUseAssets: true,
      space: 2,
      publicPath: true
    }),
  ],
}

const finalConfig = merge(webpackConfig, customConfig);
```
working for me

**Comment by n-rodriguez** [comment]
@artempartos awesome! thank you!

**Comment by mikecmpbll** [comment]
for what it's worth, i'm having the same problem. presumably this is still an issue, but do we know if it's a webpacker, webpack-assets-manifest, or yarn issue?

**Comment by ariel-codes** [comment]
@mikecmpbll the `TypeError: The 'compilation' argument must be an instance of Compilation` issue seems to only crop up when your project's version of Webpack differs from the one used by  @rails/webpacker in your dependencies.

Tip: You can check this with `yarn why webpack`
