### ISSUE TITLE
Webpacker 6 - react refresh webpack plugin

### ISSUE THREAD

**Issue by storm2513** [rails/webpacker#2865]
How to correctly add react refresh plugin in webpacker 6?

 I've tried to add it multiple ways:

1:
```
// common.js
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');

module.exports = {
  resolve: {
    alias: {
      jquery: 'jquery/src/jquery',
    },
    extensions: ['.css', '.jsx'],
  },
  plugins: [
    process.env.WEBPACK_DEV_SERVER && (
      new ReactRefreshWebpackPlugin({
        overlay: {
          sockPort: 3035,
        },
      })
    ),
  ].filter,
};
```

2: 
```
// development.js
process.env.NODE_ENV = process.env.NODE_ENV || 'development';

const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
const { devServer } = require('@rails/webpacker');

const webpackConfig = require('./base');

const isWebpackDevServer = process.env.WEBPACK_DEV_SERVER;

if (isWebpackDevServer) {
  webpackConfig.plugins.push(
    new ReactRefreshWebpackPlugin({
      overlay: {
        sockPort: devServer.port,
      },
    }),
  );
}

module.exports = webpackConfig;

```

but in both cases it leads to same error:

```
ℹ ｢wds｣: Project is running at http://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from my_app/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
internal/crypto/hash.js:82
    throw new ERR_INVALID_ARG_TYPE('data',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:82:11)
    at BulkUpdateDecorator.update (my_app/node_modules/webpack/lib/util/createHash.js:49:14)
    at NormalModule.updateHash (my_app/node_modules/webpack/lib/NormalModule.js:1062:8)
    at Compilation.createModuleHashes (my_app/node_modules/webpack/lib/Compilation.js:2769:12)
    at my_app/node_modules/webpack/lib/Compilation.js:2107:11
    at Hook.eval [as callAsync] (eval at create (my_app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (my_app/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at my_app/node_modules/webpack/lib/Compilation.js:2067:36
    at Hook.eval [as callAsync] (eval at create (my_app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (my_app/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by justin808** [comment]
See https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh

and https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh/pull/9

Note, there seems to be an issue with v6.

**Comment by rfc2616** [comment]
With the new, more straightforward webpack config `merge` function documented [here](https://github.com/rails/webpacker#webpack-configuration), I put this in my `custom.js` and seem to have things working as on webpacker 5/webpack 4:

```
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
const webpack = require('webpack');

const isDevelopment = process.env.NODE_ENV !== 'production';

module.exports = {
  module: {
    rules: [
      {
        test: /\.[jt]sx?$/,
        exclude: /node_modules/,
        use: [
          {
            loader: require.resolve('babel-loader'),
            options: {
              plugins: [
                isDevelopment && require.resolve('react-refresh/babel'),
              ].filter(Boolean),
            },
          },
        ],
      },
    ],
  },
  plugins: [
    isDevelopment && new webpack.HotModuleReplacementPlugin(),
    isDevelopment && new ReactRefreshWebpackPlugin({
      overlay: {
        sockPort: 3035,
      },
    }),
  ].filter(Boolean),
};
```

**Comment by justin808** [comment]
I just merged to master all the changes for rails/webpacker v6:

https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh

![image](https://user-images.githubusercontent.com/1118459/117909286-ab500d00-b275-11eb-8f00-032295c5dac1.png)
