### ISSUE TITLE
Rails 6.1, webpacker 6.x beta 5, cant import stylesheets in javascript file

### ISSUE THREAD

**Issue by rafath** [rails/webpacker#2916]
I've issue with fresh rails installment:
Rails 6.1.1
Webpacker: 6.0.0.beta.5

in `app/packs/javascript` Im trying to `import` / `require` stylesheet file. With fresh installments (without any loaders), or with them (`sass-loader`, `postcss-loader`, and so on (check  `config/webpack/custom.js`) I cant start application, Im getting errors: 

```
➜ bin/webpack-dev-server
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app
✖ ｢wdm｣: assets by chunk 1.09 MiB (id hint: vendors)
  asset js/vendors-node_modules_prop-types_index_js-node_modules_react-dom_index_js-d5e874c4665c5eb76275.js 1020 KiB [emitted] [immutable] (id hint: vendors) 1 related asset
  asset js/vendors-node_modules_rails_activestorage_app_assets_javascripts_activestorage_js-node_modules-8bd44b-598a4646829239d7a73a.js 99.8 KiB [emitted] [immutable] (id hint: vendors) 1 related asset
asset js/runtime-fae6434d5e2ffa36e145.js 6.84 KiB [emitted] [immutable] (name: runtime) 1 related asset
asset js/application-a921c7d22caedd011a79.js 4.83 KiB [emitted] [immutable] (name: application) 1 related asset
asset js/hello_react-6ba903827eec837f807f.js 2.34 KiB [emitted] [immutable] (name: hello_react) 1 related asset
asset manifest.json 2.11 KiB [emitted]
Entrypoint application 111 KiB (116 KiB) = js/runtime-fae6434d5e2ffa36e145.js 6.84 KiB js/vendors-node_modules_rails_activestorage_app_assets_javascripts_activestorage_js-node_modules-8bd44b-598a4646829239d7a73a.js 99.8 KiB js/application-a921c7d22caedd011a79.js 4.83 KiB 3 auxiliary assets
Entrypoint hello_react 1 MiB (1.17 MiB) = js/runtime-fae6434d5e2ffa36e145.js 6.84 KiB js/vendors-node_modules_prop-types_index_js-node_modules_react-dom_index_js-d5e874c4665c5eb76275.js 1020 KiB js/hello_react-6ba903827eec837f807f.js 2.34 KiB 3 auxiliary assets
runtime modules 3.55 KiB 5 modules
modules by path ./node_modules/ 1.08 MiB
  modules by path ./node_modules/prop-types/ 25.8 KiB 4 modules
  modules by path ./node_modules/scheduler/ 31.8 KiB 4 modules
  modules by path ./node_modules/@rails/ 60.2 KiB 2 modules
  modules by path ./node_modules/react/ 70.6 KiB 2 modules
  modules by path ./node_modules/react-dom/ 875 KiB 2 modules
  modules by path ./node_modules/react-is/ 7.01 KiB 2 modules
  ./node_modules/turbolinks/dist/turbolinks.js 37.6 KiB [built] [code generated]
  ./node_modules/object-assign/index.js 2.06 KiB [built] [code generated]
modules by path ./app/javascript/ 1.75 KiB
  ./app/javascript/packs/application.js 617 bytes [built] [code generated]
  ./app/javascript/packs/hello_react.jsx 1.11 KiB [built] [code generated]
  ./app/javascript/stylesheets/application.scss 39 bytes [built] [code generated] [1 error]

ERROR in ./app/javascript/stylesheets/application.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
2 │ import ___CSS_LOADER_API_SOURCEMAP_IMPORT___ from "../../../node_modules/css-loader/dist/runtime/cssWithMappingToString.js";
  │                                                                                                                            ^
  ╵
  app/javascript/stylesheets/application.scss 2:124  root stylesheet
    at processResult (/Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/webpack/lib/NormalModule.js:598:19)
    at /Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/webpack/lib/NormalModule.js:692:5
    at /Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/sass/sass.dart.js:91135:16)
    at _render_closure1.call$2 (/Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/sass/sass.dart.js:80011:12)
    at _RootZone.runBinary$3$3 (/Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/sass/sass.dart.js:27197:18)
    at _FutureListener.handleError$1 (/Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/sass/sass.dart.js:25725:19)
 @ ./app/javascript/packs/application.js 11:0-41

1 ERROR in child compilations
webpack 5.20.2 compiled with 2 errors in 1808 ms
ℹ ｢wdm｣: Failed to compile.
```

when I change to `import '../stylesheets/application.css';` the n Im getting: 
```ℹ ｢wdm｣: Failed to compile.
ℹ ｢wdm｣: Compiling...
✖ ｢wdm｣: assets by status 1.1 MiB [cached] 4 assets
assets by path . 6.6 KiB
  asset js/application-a03de208fe59d7f39c8d.js 4.49 KiB [emitted] [immutable] (name: application) 1 related asset
  asset manifest.json 2.11 KiB [emitted]
Entrypoint application 111 KiB (116 KiB) = js/runtime-fae6434d5e2ffa36e145.js 6.84 KiB js/vendors-node_modules_rails_activestorage_app_assets_javascripts_activestorage_js-node_modules-8bd44b-598a4646829239d7a73a.js 99.8 KiB js/application-a03de208fe59d7f39c8d.js 4.49 KiB 3 auxiliary assets
Entrypoint hello_react 1 MiB (1.17 MiB) = js/runtime-fae6434d5e2ffa36e145.js 6.84 KiB js/vendors-node_modules_prop-types_index_js-node_modules_react-dom_index_js-d5e874c4665c5eb76275.js 1020 KiB js/hello_react-6ba903827eec837f807f.js 2.34 KiB 3 auxiliary assets
cached modules 1.09 MiB (javascript) 3.55 KiB (runtime) [cached] 24 modules
cacheable modules 655 bytes
  ./app/javascript/packs/application.js 616 bytes [code generated]
  ./app/javascript/stylesheets/application.css 39 bytes [built] [code generated] [1 error]

ERROR in ./app/javascript/stylesheets/application.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) /Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/app/javascript/stylesheets/application.css Unknown word

> 1 | import api from "!../../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    | ^
  2 |             import content from "!!../../../node_modules/css-loader/dist/cjs.js!./application.css";
  3 | 

    at processResult (/Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/webpack/lib/NormalModule.js:598:19)
    at /Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/webpack/lib/NormalModule.js:692:5
    at /Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Volumes/Accounts/rafath/projects/nawidelcu.fit/new_apps/gastro-2021/gastro_app/node_modules/postcss-loader/dist/index.js:94:7)
 @ ./app/javascript/packs/application.js 11:0-40

1 ERROR in child compilations
webpack 5.20.2 compiled with 2 errors in 97 ms
ℹ ｢wdm｣: Failed to compile.

```
source code is available here: https://github.com/rafath/rails-6-webpacker

I want to be able import stylesheets in js and get them availbale for `stylesheet_pack_tag`. Some how rials / webpacker does not generate css from scss, even If I generate css file, them Im getting error above. 

I tried to downgrade to webpacker 5.2.x, but Im getting an error `Error: Cannot find module ‘webpack-cli/bin/config-yargs’`

Can anyone help me solve this problem? pls ;)

**Comment by rafath** [comment]
I've solved the issue with downgrading webpacker, postcss, postcss-loader you cant check it here what I've changed
https://github.com/rafath/rails-6-webpacker/pull/1/files

**Comment by kurt-mueller-osumc** [comment]
@rafath I've run into this problem as well. I'm currently banging my head :).

**Comment by rafath** [comment]
You can fetch my working repo https://github.com/rafath/rails-6-webpacker - if you have any questions let me know, maybe I can help you

**Comment by rossta** [comment]
@rafath I was able to reproduce with your demo app, thank you for posting that.

I was then able to get CSS/SCSS stylesheets imports from JS working with Webpacker 6 with a simple fix in https://github.com/rafath/rails-6-webpacker/pull/2. 

The custom config for CSS loaders was not setup properly; Webpacker 6 will provide the CSS loader rules for you when it detects that you've installed css-loader/postcss-loader/mini-css-extract-plugin etc.

@kurt-mueller-osumc Are you also using custom CSS config? If so, try without.

**Comment by rafath** [comment]
@rosta thanks for checking it out. It worked, but there are new issues :(. bin/webpack-dev-servers uses port 8080 (instead 3035) and despite of compliation - js file not executes any functions (i.e alert - it does not show). Also hot reloading doest work (on both files js and css) - have to manually refres the page to see changed colors.  Also I hoped that with updated libs (from webpack 4.x) compilation time of css will decrease - there is a problem with tailwindcss/utilities which takes abt 12secs to re-compile every time when you do any changes in css (but ofcource maybe its not the issue of webpack only amount of tailwing code?). Here are my changes: https://github.com/rafath/rails-6-webpacker/pull/4/files

**Comment by wes-r** [comment]
Just ran into what @rafath said about `bin/webpack-dev-server` running on `8080` this really threw me for a loop wondering why my pack files were not getting loaded.

**Comment by rossta** [comment]
@rafath See https://github.com/rafath/rails-6-webpacker/pull/5

@wes-r Check out https://github.com/rafath/rails-6-webpacker/pull/5 to see if the same issues apply to you.
