### ISSUE TITLE
can't find gem bundler (= 2.2.14) with executable bundle (Gem::GemNotFoundException)

### ISSUE THREAD

**Issue by LimeBlast** [rails/webpacker#2958]
I have a strange issue which I'm hoping someone can help me with.

I've inherited a Rails 4.2 app which uses the webpacker gem (was `4.2.2`, but I've updated this to `4.3.0` in the hope it would solve this issue, it didn't).

I'm trying to get `./bin/webpack-dev-server` running inside a docker container (for development purposes), but as soon as I run it, I get the following error:

```
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems.rb:281:in `find_spec_for_exe': can't find gem bundler (= 2.2.14) with executable bundle (Gem::GemNotFoundException)
	from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems.rb:258:in `bin_path'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/rubygems_integration.rb:209:in `bin_path'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:22:in `setup'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:148:in `setup'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `block in <top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/ui/shell.rb:136:in `with_level'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/ui/shell.rb:88:in `silence'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from ./bin/webpack-dev-server:10:in `<main>'
```

I'm able to run `bundle exec rails s` without issue, although I get a similar issue is try running `rails s` without the `bundle exec`.

I'm also not running bundler `2.2.14`, it's `1.17.3`. I've tried using `2.2.14` instead, but I just get the same error.

Any ideas?

**Comment by guillaumebriday** [comment]
Did you install the gem `bundler` and run `bundle install`?
