### ISSUE TITLE
TypeError: webpackConfig.plugins.append is not a function (6.0.0.beta.6)

### ISSUE THREAD

**Issue by cloud69420** [rails/webpacker#2980]
Howdy,

Attempting to add jQuery to a fresh Rails 6.1.3.1 app with Webpacker 6.0.0.beta.6 but get:
```
% rails assets:precompile
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.78s.
Compiling...
Compilation failed:
[webpack-cli] Failed to load '/home/apps/__TMP/webpacker6/config/webpack/production.js' config
[webpack-cli] TypeError: webpackConfig.plugins.append is not a function
    at Object.<anonymous> (/home/apps/__TMP/webpacker6/config/webpack/base.js:4:23)
    at Module._compile (/home/apps/__TMP/webpacker6/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (/home/apps/__TMP/webpacker6/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/apps/__TMP/webpacker6/config/webpack/production.js:3:23)
    at Module._compile (/home/apps/__TMP/webpacker6/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```
```
% cat config/webpack/base.js
const { webpackConfig } = require("@rails/webpacker")
const webpack = require("webpack")

webpackConfig.plugins.append("Provide",
  new webpack.ProvidePlugin({
    $: "jquery",
    jQuery: "jquery"
  })
)

module.exports = webpackConfig
```
Hope I haven't missed something obvious. Here's the reduced testcase: https://github.com/cloud69420/webpacker6

Cheers!

**Comment by mcmire** [comment]
I believe that the layer that Webpacker placed on top of the Webpack config was removed. Now you can simply `merge` what you want into the config (using the Webpack documentation as a reference, e.g. [this section for plugins](https://webpack.js.org/configuration/plugins/)). So something like this should work:

``` javascript
const { webpackConfig, merge } = require("@rails/webpacker")
const webpack = require("webpack")

module.exports = merge(
  webpackConfig,
  {
    plugins: [
      new webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery"
      })
    ]
  }
)
```

**Comment by cloud69420** [comment]
@mcmire thank you so much!
