### ISSUE TITLE
Question: @rails/webpacker merge is not a function

### ISSUE THREAD

**Issue by khangpn** [rails/webpacker#2984]
Hello,

First thing first
Rails 6.1.3.1
webpacker 5.2.1
@rails/webpacker@5.2.1

I would like to add a custom webpack config, and I followed the [guide](https://github.com/rails/webpacker) 

```javascript
const { webpackConfig, merge  } = require('@rails/webpacker')
process.env.NODE_ENV = process.env.NODE_ENV || 'production'

const environment = require('./environment')
const customConfig = {
  output: {
    publicPath: '/subdirectory/packs/'
  }
}

module.exports = merge(environment.toWebpackConfig(), customConfig)
```

And I got this error:
`TypeError: merge is not a function`

I looked into your change log and i found [this](https://github.com/rails/webpacker/blob/master/CHANGELOG.md#400rc8---2019-03-03). So I updated my code to

```javascript
process.env.NODE_ENV = process.env.NODE_ENV || 'production'

const environment = require('./environment')
environment.config.merge({
  output: {
    publicPath: '/subdirectory/packs/'
  }
})

module.exports = environment.toWebpackConfig()
```
and it works!

The thing is I cannot find any places in your changelog about the `merge` function, or the API of the `environment` object.
Any suggestions where I can find useful information?

Thank you.

**Comment by guillaumebriday** [comment]
`merge` will come in Webpacker 6 which is the current version on master. You're using the Webpacker 5 version.

The documentation is living on this branch https://github.com/rails/webpacker/tree/5-x-stable

**Comment by arg** [comment]
> merge will come in Webpacker 6 which is the current version on master. You're using the Webpacker 5 version.

This issue is also reproducible on Webpacker 6.0.0-beta.7, Rails 6.1.3

```js
// config/webpack/base.js
const { webpackConfig, merge } = require('@rails/webpacker')

const customConfig = {
  resolve: {
    extensions: ['.css']
  }
}

module.exports = merge(webpackConfig, customConfig)
```

```js
// config/webpack/production.js

process.env.NODE_ENV = process.env.NODE_ENV || 'production'

const webpackConfig = require('./base')

module.exports = webpackConfig
```

```json
// package.json
{
  "name": "demo",
  "private": true,
  "version": "1.0.0",
  "dependencies": {
    "@rails/activestorage": "^6.1.3",
    "@rails/ujs": "^6.1.3"
 },
  "devDependencies": {
    "@rails/webpacker": "^6.0.0-beta.7",
    "postcss": "^8.2.12",
    "tailwindcss": "^2.1.2",
    "autoprefixer": "^10.2.5"
  },
  "babel": {
    "presets": [
      "./node_modules/@rails/webpacker/package/babel/preset.js"
    ]
  },
  "browserslist": [
    "defaults"
  ]
}
```

```sh
$ rails assets:precompile

yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.32s.
Compiling...
Compilation failed:
[webpack-cli] Failed to load '/app/config/webpack/production.js' config
[webpack-cli] TypeError: merge is not a function
    at Object.<anonymous> (/app/config/webpack/base.js:10:18)
    at Module._compile (/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/app/config/webpack/production.js:3:23)
    at Module._compile (/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

**Comment by cseelus** [comment]
@arg Did you find a workaround for this bug?

**Comment by arg** [comment]
No unfortunately, after this and other issues discovered, we decided to stay with v5.3.0

**Comment by inopinatus** [comment]
encountered the same with 6.0.0-beta.7, went back to 6.0.0-beta.6.

**Comment by sergiopantoja** [comment]
Just hit this with 6.0.0-beta.7 and Rails 6.3.1.2.

@cseelus I found a workaround.  You can require `merge` separately.

```js
const { webpackConfig } = require('@rails/webpacker')
const { merge } = require('webpack-merge')

const customConfig = {
  resolve: {
    extensions: ['.css']
  }
}

module.exports = merge(webpackConfig, customConfig)
```

**Comment by charithhewage** [comment]
@sergiopantoja This patch fixed the `merge is not a function` issue. But, I get `TypeError: Merging undefined is not supported` now with webpacker-6.0.0.pre.2. Thanks

**Comment by dolsem** [comment]
This should be reopened, now that the issue is present again. I checked the `package/index.js` file and `merge` is not getting exported.
