### ISSUE TITLE
Webpacker 6.0.0-beta.7 fails to compile

### ISSUE THREAD

**Issue by joshleblanc** [rails/webpacker#3044]
Node version: v14.17.0

Dependencies:

```
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "^6.0.0-beta.7",
    "jquery": "^3.6.0",
    "moment": "^2.29.1",
    "pikaday": "^1.8.2",
    "stimulus": "^2.0.0",
    "turbolinks": "^5.2.0",
    "webpack": "5.11.0",
    "webpack-cli": "4.2.0"
```

Output:

```
[webpack-cli] TypeError: Cannot read property 'get' of undefined
    at exports.provide (C:\Users\josh.OMICS1\RubymineProjects\rails-rx-support\node_modules\@rails\webpacker\node_modules\webpack\lib\util\MapHelpers.js:17:20)
    at C:\Users\josh.OMICS1\RubymineProjects\rails-rx-support\node_modules\@rails\webpacker\node_modules\webpack\lib\DefinePlugin.js:290:6
    at Hook.eval [as call] (eval at create (C:\Users\josh.OMICS1\RubymineProjects\rails-rx-support\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:147:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Users\josh.OMICS1\RubymineProjects\rails-rx-support\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Users\josh.OMICS1\RubymineProjects\rails-rx-support\node_modules\webpack\lib\Compiler.js:988:26)
    at C:\Users\josh.OMICS1\RubymineProjects\rails-rx-support\node_modules\webpack\lib\Compiler.js:1029:29
    at Hook.eval [as callAsync] (eval at create (C:\Users\josh.OMICS1\RubymineProjects\rails-rx-support\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\josh.OMICS1\RubymineProjects\rails-rx-support\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (C:\Users\josh.OMICS1\RubymineProjects\rails-rx-support\node_modules\webpack\lib\Compiler.js:1024:28)
    at C:\Users\josh.OMICS1\RubymineProjects\rails-rx-support\node_modules\webpack\lib\Compiler.js:471:12
```

I'm not sure it's even getting to the compilation step, as I went through all the entry points and just straight up deleted the contents, and webpack still threw. 

Let me know if you need any more information.

**Comment by mcmire** [comment]
A few questions come to mind:

* What command are you using to compile?
* What steps did you perform to upgrade to Webpacker 6?
* Do you have any custom Webpacker configuration?
* Are you using Yarn or NPM?
* What happens if you blow away `node_modules` and re-install everything?

**Comment by joshleblanc** [comment]
* `bin/rails rails webpacker:compile`, as well as the automatic compilation from loading a page, as well as `bin/rails webpack`.
* I followed the upgrade guide
* No, nothing custom
* Yarn
* Nuking node modules and reinstalling produces the same error

**Comment by joshleblanc** [comment]
I've created a reproduction of the issue here: https://github.com/joshleblanc/webpacker-6-mvce

**Comment by joshleblanc** [comment]
Looks like the issue is that `webpacker:install` pins `webpack` at 5.11.0 and `webpack-cli` at `4.2.0`. 

Upgrading `webpack` to `5.38.1` and `webpack-cli` to `4.7.2` seems to have resolved the issue.

**Comment by kohheepeace** [comment]
I got the same issue. And @joshleblanc suggestion to upgrade `webpack` and `webpack-cli` solved the problem.
