### ISSUE TITLE
TypeError: Cannot read property 'insertAfter' of undefined 

### ISSUE THREAD

**Issue by dave105010** [rails/webpacker#3063]
Hi, I keep getting this error.
I did "yarn cache clean"
Reinstalled everything and still cannot figure out why this is failing.
I'm using Rails 6 + Webpacker 5.4.0

If I just run "webpack-dev-server", it compiles,the page reloads, and everything just works.
If I do "rails assets:precompile" compilation fails.

```
Done in 38.91s.
Compiling...
Compilation failed:
warning package.json: No license field
TypeError: Cannot read property 'insertAfter' of undefined
    at node_modules/optimize-css-assets-webpack-plugin/node_modules/css-declaration-sorter/src/main.cjs:372:22
    at Array.forEach (<anonymous>)
    at processCss (node_modules/optimize-css-assets-webpack-plugin/node_modules/css-declaration-sorter/src/main.cjs:369:12)
    at node_modules/optimize-css-assets-webpack-plugin/node_modules/css-declaration-sorter/src/main.cjs:304:21
    at async LazyResult.runAsync (node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/lazy-result.js:431:15)
    at async Promise.all (index 0)
```

**Comment by guillaumebriday** [comment]
What are the versions of your npm packages?
