### ISSUE TITLE
Cannot find module 'webpack'

### ISSUE THREAD

**Issue by cmdrkeene** [rails/webpacker#308]
Fresh install with the following configuration:

* Ubuntu 16.04
* Ruby 2.4.0p0
* Rails 5.1
* NodeJS 6.10.2
* Yarn 0.23.3

Set up a fresh Rails app using: `rails new . -d mysql --webpack=react`

package.json:

```json
{
  "name": "vagrant",
  "private": true,
  "dependencies": {
    "babel-preset-react": "^6.24.1",
    "prop-types": "^15.5.8",
    "react": "^15.5.4",
    "react-dom": "^15.5.4"
  },
  "devDependencies": {
    "webpack-dev-server": "^2.4.5"
  }
}
```

Failure:

```bash
ubuntu@ubuntu-xenial:/vagrant$ ./bin/webpack-dev-server 
module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/vagrant/node_modules/webpack-dev-server/lib/Server.js:15:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
It seems the generator (or something in this massive jumble of dependencies) is failing to add `webpack` and many more dependencies to the package.json (or something)

Am I meant to chase down these dependencies myself?

Am I executing something incorrectly?

Please help.

**Comment by gauravtiwari** [comment]
Could you  please paste log for rails new? Are all js deps correctly installed?

**Comment by cmdrkeene** [comment]
So the script attempts to install required dependencies:

```ruby
puts "Installing all JavaScript dependencies"
run "./bin/yarn add webpack webpack-merge js-yaml path-complete-extname " \
"webpack-manifest-plugin babel-loader@7.x coffee-loader coffee-script " \
"babel-core babel-preset-env compression-webpack-plugin rails-erb-loader glob " \
"extract-text-webpack-plugin node-sass file-loader sass-loader css-loader style-loader " \
"postcss-loader autoprefixer postcss-smart-import precss"
```

Though this does not seem to add them all to my `package.json` file (in either dependencies or devDependencies)

If I run that same command with `--dev`, it seems to add them and everything works.

Perhaps I'm misunderstanding `yarn` or have misconfigured/misinstalled something? 

I will re-run and attach logs.

**Comment by gauravtiwari** [comment]
@cmdrkeene So seems like it's failing for some reason. Yeah, if you could please retry again and paste full logs here 👍  that would be helpful in understanding the issue

**Comment by Davidzhu001** [comment]
@cmdrkeene 
http://weblog.rubyonrails.org/2017/3/20/Rails-5-1-rc1/

How does ruby 2.4 runs with rails 5 for you?

It requires RubyGems 2.6.11 or later from release note.

**Comment by gauravtiwari** [comment]
Closing this due to inactivity and doesn't seem like an issue in Webpacker. Feel free to reopen 👍
