### ISSUE TITLE
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):

### ISSUE THREAD

**Issue by wh1le** [rails/webpacker#3097]
Hello and thank you for this awesome library. I'm trying to integrate post-css and it can't handle import statements that are being injected in the beginning of css file. Could you help me to resolve this?

Versions: `rails 5.2.6` with `Webpacker 6.0.0.pre.2`.

**Error:**
```
webpack 5.46.0 compiled with 2 errors in 58 ms
ℹ ｢wdm｣: Failed to compile.ℹ ｢wdm｣: Compiling...✖ ｢wdm｣: assets by status 399 KiB [cached] 4 assetsasset manifest.json 1.33 KiB [emitted]

ERROR in ./app/javascript/stylesheets/admin.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(2:7) /Users/nikitamiloserdov/code/project/app/javascript/stylesheets/admin.css Unknown word
  1 | > 2 |       import API from "!../../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    |       ^
  3 |       import domAPI from "!../../../node_modules/style-loader/dist/runtime/styleDomAPI.js";
  4 |       import insertFn from "!../../../node_modules/style-loader/dist/runtime/insertBySelector.js";

    at processResult (/Users/nikitamiloserdov/code/project/node_modules/webpack/lib/NormalModule.js:703:19)
    at runLoaders (/Users/nikitamiloserdov/code/project/node_modules/webpack/lib/NormalModule.js:809:5)
    at /Users/nikitamiloserdov/code/project/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/nikitamiloserdov/code/project/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/nikitamiloserdov/code/project/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/nikitamiloserdov/code/project/node_modules/postcss-loader/dist/index.js:140:7)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.46.0 compiled with 2 errors in 77 ms
ℹ ｢wdm｣: Failed to compile.
```

```json
# package.json

{
  "dependencies": {
    "@rails/webpacker": "^6.0.0-beta.7",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "tailwindcss": "^2.2.7",
    "webpack": "^5.46.0",
    "webpack-cli": "^4.7.2"
  },
  "devDependencies": {
    "@babel/core": "^7.14.8",
    "@babel/preset-env": "^7.14.8",
    "@babel/preset-react": "^7.14.5",
    "@webpack-cli/serve": "^1.5.1",
    "autoprefixer": "^10.3.1",
    "babel-loader": "^8.2.2",
    "css-loader": "^6.2.0",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.3.2",
    "mini-css-extract-plugin": "^2.1.0",
    "node-sass": "^6.0.1",
    "postcss": "^8.3.6",
    "postcss-import": "^14.0.2",
    "postcss-loader": "^6.1.1",
    "postcss-preset-env": "^6.7.0",
    "sass": "^1.35.2",
    "sass-loader": "^12.1.0",
    "style-loader": "^3.2.1",
    "webpack-dev-server": "^3.11.2"
  },
  "babel": {
    "presets": [
      "./node_modules/@rails/webpacker/package/babel/preset.js",
       "@babel/preset-env",
       "@babel/preset-react"
    ]
  },
  "browserslist": [
    "defaults"
  ]
}
```

```js
// config/webpack/base.js

const { webpackConfig, merge } = require('@rails/webpacker')
const customConfig = {
  resolve: {
    extensions: ['.css']
  },
  plugins: [
    require('postcss-preset-env')({
      browsers: 'last 2 versions',
    }),
  ],
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader', 'postcss-loader', 'sass-loader'],
      },
      {
        test: /\.(js|jsx)$/,
        exclude: /nodeModules/,
        use: {
          loader: 'babel-loader'
        }
      },
    ],
  }
}
module.exports = merge(webpackConfig, customConfig)
```

**Comment by wh1le** [comment]
I downgraded to `gem "webpacker", "~> 5.0"` and it works now

**Comment by ptushantk-houzz** [comment]
I am also facing similar issue. In my case, I have installed webpacker 5.0 as `gem 'webpacker', '~> 5.0'`. I get issue while importing third party library css(`import 'croppie/croppie.css'`). This is how I have configured webpack 

```js
const { environment } = require('@rails/webpacker');
const vue = require('./loaders/vue');
const webpack = require('webpack');
const VueLoaderPlugin = require('vue-loader/lib/plugin');
const TerserPlugin = require('terser-webpack-plugin');
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

const isEnvProduction = environment.config.mode === 'production';
const isEnvDevelopment = environment.config.mode === 'development';
const cssRegex = /\.css$/;
const cssModuleRegex = /\.module\.css$/;

const customConfig = {
  resolve: {
    fallback: {
      dgram: false,
      fs: false,
      net: false,
      tls: false,
      child_process: false,
    },
  },
  entry: {
    vendor: ['babel-polyfill', 'vue', 'moment', 'axios'],
  },
};

const getStyleLoaders = (cssOptions) => {
  const loaders = [
    isEnvDevelopment && require.resolve('style-loader'),
    {
      loader: require.resolve('css-loader'),
      options: cssOptions,
    },
  ].filter(Boolean);
  return loaders;
};

environment.splitChunks((config) => {
  return {
    ...config,
    ...{
      optimization: {
        splitChunks: { chunks: 'all', name: '~' },
        runtimeChunk: true,
      },
    },
  };
});

environment.config.delete('node.dgram');
environment.config.delete('node.fs');
environment.config.delete('node.net');
environment.config.delete('node.tls');
environment.config.delete('node.child_process');

environment.config.merge(customConfig);

environment.plugins.append('VueLoaderPlugin', new VueLoaderPlugin());
environment.loaders.append('vue', {
  test: /\.vue$/,
  loader: 'vue-loader',
});

// Comment this if you need case-sensitive-paths-plugin in local development.
if (process.env.RAILS_ENV === 'development') {
  environment.plugins.delete('CaseSensitivePaths');
}

environment.plugins.prepend('Environment', new webpack.EnvironmentPlugin(JSON.parse(JSON.stringify(process.env))));
environment.plugins.prepend(
  'Provide',
  new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    jquery: 'jquery',
  })
);

const config = environment.toWebpackConfig();

config.resolve.alias = {
  jquery: 'jquery/src/jquery',
};

let sassLoader = environment.loaders.get('sass').use.find((item) => item.loader === 'sass-loader');
sassLoader = {
  ...sassLoader,
  options: {
    ...sassLoader.options,
    sassOptions: {
      ...sassLoader.options.sassOptions,
      includePaths: ['./node_modules'],
    },
  },
};



// let miniCssExtractPlugin = environment.plugins.get('MiniCssExtract');
// console.log('miniCssExtractPlugin', miniCssExtractPlugin)

environment.loaders.append('vue', vue);

environment.config.merge({
  optimization: {
    minimize: false, // should be isProduction
    minimizer: [
      new TerserPlugin({
        test: /\.js(\?.*)?$/i,
      }),
    ],
  },
  resolve: {
    alias: {
      app: path.resolve(__dirname, '../../app/'),
    },
  },
  module: {
    rules: [
      {
        oneOf: [
          {
            test: cssRegex,
            exclude: cssModuleRegex,
            use: getStyleLoaders({
              importLoaders: 1,
              sourceMap: false,
              modules: {
                mode: 'icss',
              },
            }),
            sideEffects: true,
          },
        ],
      },
    ].filter(Boolean),
  },
});

module.exports = environment;

```

I am getting 

> ERROR in ./node_modules/croppie/croppie.css
> Module build failed (from ./node_modules/@rails/webpacker/node_modules/mini-css-extract-plugin/dist/loader.js):
> TypeError: Cannot read properties of undefined (reading 'tap')
