### ISSUE TITLE
Regression in 6.0.0.rc.1: TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by jaredbeck** [rails/webpacker#3117]
This is a regression from 6.0.0.beta.7 to 6.0.0.rc.1.

## 6.0.0.rc.1

```plain
bin/webpack
[webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/redacted/node_modules/@rails/webpacker/node_modules/webpack/lib/NormalModule.js:195:10)
    at WebpackAssetsManifest.handleCompilation (/redacted/node_modules/@rails/webpacker/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:778:18)
    at Hook.eval [as call] (eval at create (/redacted/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/redacted/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/redacted/node_modules/webpack/lib/Compiler.js:1044:26)
    at /redacted/node_modules/webpack/lib/Compiler.js:1088:29
    at Hook.eval [as callAsync] (eval at create (/redacted/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/redacted/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/redacted/node_modules/webpack/lib/Compiler.js:1083:28)
    at /redacted/node_modules/webpack/lib/Compiler.js:508:12

```

## 6.0.0.beta.7 

```plain
bin/webpack
webpack 5.46.0 compiled successfully in 5986 ms
```

**Comment by mattiagiuffrida-st** [comment]
I'm investigating this as it might be related to my recent PR: https://github.com/rails/webpacker/pull/3111
Though according to the documentation it should be fine, but there might be some other incompatibility

**Comment by mattiagiuffrida-st** [comment]
This is a common issue with JS dependencies, it happens when there's duplication of libraries. You probably have an explicit dependency to `webpack` in your `package.json`. If you remove it from there, `webpack` will be added as a dependency from `@rails/webpacker` and you won't have duplication anymore.

**Comment by mattiagiuffrida-st** [comment]
@jaredbeck did the above help?

**Comment by jaredbeck** [comment]
> .. in your package.json. If you remove .. webpack ..

Yes this worked. Thanks, Mattia :heart:
