### ISSUE TITLE
webpacker 6.0.0-rc.5 (javascript) bundles/vendors webpack causing errors

### ISSUE THREAD

**Issue by mildred** [rails/webpacker#3177]
When webpacker call webpack code, it uses a bundled version of webpack instead of using the project's version. This can cause errors such as type mismatch.

```
d$ WEBPACK_DEV_SERVER=1 ./bin/webpack-dev-server
path/to/project/root/node_modules/@rails/webpacker/node_modules/webpack/lib/NormalModule.js:203
			throw new TypeError(
			^

TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (path/to/project/root/node_modules/@rails/webpacker/node_modules/webpack/lib/NormalModule.js:203:10)
    at WebpackAssetsManifest.handleCompilation (path/to/project/root/node_modules/@rails/webpacker/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:778:18)
    at Hook.eval [as call] (eval at create (path/to/project/root/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:102:1)
    at Hook.CALL_DELEGATE [as _call] (path/to/project/root/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (path/to/project/root/node_modules/webpack/lib/Compiler.js:1052:26)
    at path/to/project/root/node_modules/webpack/lib/Compiler.js:1096:29
    at Hook.eval [as callAsync] (eval at create (path/to/project/root/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (path/to/project/root/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (path/to/project/root/node_modules/webpack/lib/Compiler.js:1091:28)
    at path/to/project/root/node_modules/webpack/lib/Watching.js:200:19
```

Please note in the stack trace that webpack `node_modules/webpack/lib/Compiler.js` is calling to webpacker bundled version of webpack `node_modules/@rails/webpacker/node_modules/webpack/lib/NormalModule.js` and fails to recognize a type passed as argument.

I believe webpacker should not bundle webpack like this.

**Comment by mildred** [comment]
I found a way to fix this: add webpack-assets-manifest to your node_modules (node will take it before using the vendored one)

```
yarn add --dev webpack-assets-manifest
```
