### ISSUE TITLE
class variable @@local_levels of ActiveSupport::Logger is overtaken by Logger

### ISSUE THREAD

**Issue by emiellohr** [rails/webpacker#3309]
Running the task webpacker:compile gives the error:

```
class variable @@local_levels of ActiveSupport::Logger is overtaken by Logger
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:13:in `local_levels'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:29:in `local_level'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:46:in `level'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:63:in `add'
/usr/local/lib/ruby/3.1.0/logger.rb:529:in `info'
/usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker/compiler.rb:75:in `run_webpack'
/usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker/compiler.rb:23:in `compile'
/usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker/commands.rb:52:in `compile'
/usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker.rb:35:in `compile'

```
Ruby version: 3.1.3
Rails version: 6.1.7.2
Webpacker version: 6.0.0.rc.6

I have no idea what causes this error message. Anyone else who can point me in the right direction?

**Comment by preet000190** [comment]
> After upgrading a Rails project from Ruby 2.7 to 3.1.3. Running the task webpacker:compile gives the error:
> 
> ```
> class variable @@local_levels of ActiveSupport::Logger is overtaken by Logger
> /usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:13:in `local_levels'
> /usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:29:in `local_level'
> /usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:46:in `level'
> /usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:63:in `add'
> /usr/local/lib/ruby/3.1.0/logger.rb:529:in `info'
> /usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker/compiler.rb:75:in `run_webpack'
> /usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker/compiler.rb:23:in `compile'
> /usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker/commands.rb:52:in `compile'
> /usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker.rb:35:in `compile'
> 
> ```
> Ruby version: 3.1.3
> Rails version: 6.1.7.2
> Webpacker version: 6.0.0.rc.6
> 
> I have no idea what causes this error message. Anyone else who can point me in the right direction?
>

**Comment by preet000190** [comment]
> After upgrading a Rails project from Ruby 2.7 to 3.1.3. Running the task webpacker:compile gives the error:
> 
> ```
> class variable @@local_levels of ActiveSupport::Logger is overtaken by Logger
> /usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:13:in `local_levels'
> /usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:29:in `local_level'
> /usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:46:in `level'
> /usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/logger_thread_safe_level.rb:63:in `add'
> /usr/local/lib/ruby/3.1.3/logger.rb:529:in `info'
> /usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker/compiler.rb:75:in `run_webpack'
> /usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker/compiler.rb:23:in `compile'
> /usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker/commands.rb:52:in `compile'
> /usr/local/bundle/gems/webpacker-6.0.0.rc.6/lib/webpacker.rb:35:in `compile'
> 
> ```
> Ruby version: 3.1.3
> Rails version: 6.1.7.2
> Webpacker version: 6.0.0.rc.6
> 
> I have no idea what causes this error message. Anyone else who can point me in the right direction?
>
