### ISSUE TITLE
adding .erb will block bin/webpack-dev-server 

### ISSUE THREAD

**Issue by github0013** [rails/webpacker#338]
## env
```bash
$ uname -a
Darwin mbp 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]
```
## reproduction repo
https://github.com/github0013/js_erb

## how it happens

I did a clean 5.1 install, and `bundle update` to be sure to have all fresh.
Right after I install it, running `bin/webpack-dev-server` works as expected.

but if I add `.erb` to `application.js`, running `bin/webpack-dev-server` will be blocked at `application.js.erb`

```bash
$ bin/webpack-dev-server
 10% building modules 2/2 modules 0 active
Project is running at http://localhost:8080/
webpack output is served from http://localhost:8080/packs/
Content not from webpack is served from /Users/ac/projects/24/js_erb/public/packs
404s will fallback to /index.html
 42% building modules 267/268 modules 1 active ...p/javascript/packs/application.js.erb
```

Strange thing is, even after killing it with Ctrl+C, ruby proesses are still there.
something like this
```bash
$ ps aux | grep ruby
ac                4075   0.0  0.0  2471272   3032   ??  S    10:56AM   0:00.01 /Users/ac/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-fsevent-0.9.8/bin/fsevent_watch --latency 0.1 /Users/ac/projects/24/js_erb/test/mailers
ac                4074   0.0  0.0  2471272   3036   ??  S    10:56AM   0:00.01 /Users/ac/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-fsevent-0.9.8/bin/fsevent_watch --latency 0.1 /Users/ac/projects/24/js_erb/app/models
...
...
```

and if I run `bin/webpack-dev-server` once again with the `rb-fsevents` running on the side, it now shows 

```bash
ERROR in ./app/javascript/packs/application.js.erb
Module build failed: Error: Command failed: bin/rails runner /Users/ac/projects/24/js_erb/node_modules/rails-erb-loader/erb_transformer.rb __RAILS_ERB_LOADER_DELIMETER__ erb
(erb):7:in `<main>': undefined method `javascript_pack_tag' for main:Object (NoMethodError)
	from /Users/ac/.rbenv/versions/2.4.0/lib/ruby/2.4.0/erb.rb:896:in `eval'
	from /Users/ac/.rbenv/versions/2.4.0/lib/ruby/2.4.0/erb.rb:896:in `result'
	from /Users/ac/projects/24/js_erb/node_modules/rails-erb-loader/erb_transformer.rb:19:in `<top (required)>'
	from /Users/ac/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.1.0/lib/rails/commands/runner/runner_command.rb:34:in `load'
```

## question

1. is this related to webpacker or rails-erb-loader, I am not sure.
2. should I not use `.erb` for application.js?

**Comment by github0013** [comment]
I think I found the problem.

## application.js

```js
...
...
// To reference this file, add <%= javascript_pack_tag 'application' %> to the appropriate
// layout file, like app/views/layouts/application.html.erb
...
...

```
has comment line like these.  In one of the lines, it actually has erb syntax.

`add <%= javascript_pack_tag 'application' %>` 

this is evaluated, and shows `undefined method` error.

# solution

removing the `<%= javascript_pack_tag 'application' %>` will do it.

**Comment by richpeck** [comment]
Thanks for this
