### ISSUE TITLE
third party tools blowing up trying to find package.json and node_modules

### ISSUE THREAD

**Issue by denniscollective** [rails/webpacker#41]
Howdy! Thanks for the tool! I'm not trying to reopen a bike-shed, but don't know how to deal with the issues that this is raising. I'm down for any solution that works :)

I'm trying to get eslint set up and it's blowing up, trying to find the package.json.

I got it set up another way, and then when it was linting, it was raising a bunch of "cant_resolve module" issues, which I'm assuming is because node_modules is buried in vendor, but I could be jumping to a conclusion.

My webpack knowledge is very limited (which is why I'm using this tool), is there some magic env variable I should be using to point the tooling at package.json in a certain way? Should I just be running this from within /vendor ?

If you can point me in the right direction if you already have a workaround, I could help document it better, otherwise, heads up, this is happening.

I'm super psyched on how all of this is evolving.

```
sparkly$ vendor/node_modules/.bin/eslint --init
? How would you like to configure ESLint? Answer questions about your style
? Are you using ECMAScript 6 features? Yes
? Are you using ES6 modules? Yes
? Where will your code run? Browser
? Do you use CommonJS? Yes
? Do you use JSX? Yes
? Do you use React? Yes
? What style of indentation do you use? Spaces
? What quotes do you use for strings? Single
? What line endings do you use? Unix
? Do you require semicolons? No
? What format do you want your config file to be in? JavaScript
Could not find a package.json file. Run 'npm init' to create one.
Error: Could not find a package.json file. Run 'npm init' to create one.
    at check (/Users/dennis/workspace/sparkly/vendor/node_modules/eslint/lib/util/npm-util.js:76:15)
    at Object.checkDevDeps (/Users/dennis/workspace/sparkly/vendor/node_modules/eslint/lib/util/npm-util.js:124:12)
    at installModules (/Users/dennis/workspace/sparkly/vendor/node_modules/eslint/lib/config/config-initializer.js:79:35)
    at processAnswers (/Users/dennis/workspace/sparkly/vendor/node_modules/eslint/lib/config/config-initializer.js:245:5)
    at null.completed (/Users/dennis/workspace/sparkly/vendor/node_modules/eslint/lib/config/config-initializer.js:468:30)
    at PromptUI.onCompletion (/Users/dennis/workspace/sparkly/vendor/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/Users/dennis/workspace/sparkly/vendor/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/dennis/workspace/sparkly/vendor/node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.Rx.Subject.addProperties.onCompleted (/Users/dennis/workspace/sparkly/vendor/node_modules/rx-lite/rx.lite.js:5871:19)
    at Subject.tryCatcher (/Users/dennis/workspace/sparkly/vendor/node_modules/rx-lite/rx.lite.js:63:31)
```

**Comment by AntiFish03** [comment]
https://github.com/rails/rails/pull/27245

**Comment by dhh** [comment]
Here's how I just did it:

```
./bin/yarn add eslint
cd vendor
./node_modules/.bin/eslint --init
cd ..
./vendor/node_modules/.bin/eslint --c vendor/.eslintrc.js app/javascript/
```

That works. You could now package the last call in a binstub, like we do with webpack itself, if you don't want to pass that configuration every time.

**Comment by dhh** [comment]
I could see a fair argument for wrapping this up in a task. Maybe just `webpacker:install:eslint` that goes through the config process and setups the binstub.

**Comment by denniscollective** [comment]
Thanks!
