### ISSUE TITLE
Issue with Elm compiler

### ISSUE THREAD

**Issue by ghivert** [rails/webpacker#420]
Hi !

I'm trying to deploy a Rails server to Heroku with Elm on frontend, but I'm encountering a bug. It seems that the Elm compiler is not found…

Here's the full log:

```
remote:        [Webpacker] Compilation Failed
remote:        yarn run v0.24.5
remote:        $ "/tmp/build_3da1d65b78c4b248a9c140d2599e5d28/node_modules/.bin/webpack" --config /tmp/build_3da1d65b78c4b248a9c140d2599e5d28/config/webpack/production.js
remote:        Hash: 789c03420c8028135ff2
remote:        Time: 1610ms
remote:        [0] ./app/frontend/javascript/image_uploader.js 452 bytes {0} [built]
remote:        [1] ./app/frontend/javascript/markdownify_elm.js 332 bytes {0} [built]
remote:        [2] ./app/frontend/elm/Event.elm 1.11 kB {0} [built] [failed] [1 error]
remote:        [3] ./app/frontend/elm/Footer.elm 1.11 kB {1} [built] [failed] [1 error]
remote:        [4] ./app/frontend/packs/event_elm.js 567 bytes {0} [built]
remote:        [5] ./app/frontend/packs/footer_elm.js 418 bytes {1} [built]
remote:        ERROR in ./app/frontend/elm/Event.elm
remote:        Module build failed: Error: Compiler process exited with error Compilation failed
remote:        events.js:163
remote:        throw er; // Unhandled 'error' event
remote:        ^
remote:        Error: spawn /tmp/build_3da1d65b78c4b248a9c140d2599e5d28/node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm-make ENOENT
remote:        at exports._errnoException (util.js:1050:11)
remote:        at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
remote:        at onErrorNT (internal/child_process.js:367:16)
remote:        at _combinedTickCallback (internal/process/next_tick.js:80:11)
remote:        at process._tickCallback (internal/process/next_tick.js:104:9)
remote:        at Module.runMain (module.js:607:11)
remote:        at run (bootstrap_node.js:427:7)
remote:        at startup (bootstrap_node.js:151:9)
remote:        at bootstrap_node.js:542:3
remote:        at ChildProcess.<anonymous> (/tmp/build_3da1d65b78c4b248a9c140d2599e5d28/node_modules/node-elm-compiler/index.js:141:27)
remote:        at emitTwo (events.js:106:13)
remote:        at ChildProcess.emit (events.js:194:7)
remote:        at maybeClose (internal/child_process.js:899:16)
remote:        at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
remote:        @ ./app/frontend/packs/event_elm.js 4:0-31
remote:        ERROR in ./app/frontend/elm/Footer.elm
remote:        Module build failed: Error: Compiler process exited with error Compilation failed
remote:        events.js:163
remote:        throw er; // Unhandled 'error' event
remote:        ^
remote:        Error: spawn /tmp/build_3da1d65b78c4b248a9c140d2599e5d28/node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm-make ENOENT
remote:        at exports._errnoException (util.js:1050:11)
remote:        at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
remote:        at onErrorNT (internal/child_process.js:367:16)
remote:        at _combinedTickCallback (internal/process/next_tick.js:80:11)
remote:        at process._tickCallback (internal/process/next_tick.js:104:9)
remote:        at Module.runMain (module.js:607:11)
remote:        at run (bootstrap_node.js:427:7)
remote:        at startup (bootstrap_node.js:151:9)
remote:        at bootstrap_node.js:542:3
remote:        at ChildProcess.<anonymous> (/tmp/build_3da1d65b78c4b248a9c140d2599e5d28/node_modules/node-elm-compiler/index.js:141:27)
remote:        at emitTwo (events.js:106:13)
remote:        at ChildProcess.emit (events.js:194:7)
remote:        at maybeClose (internal/child_process.js:899:16)
remote:        at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
remote:        @ ./app/frontend/packs/footer_elm.js 4:0-32
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote:        
remote:        error Command failed with exit code 2.
remote:        
```

I tried to reinstall webpack with `rails webpack:install` and `rails webpack:install:elm`, but I can't get it to work, even with the default configuration.

Any idea?

**Comment by gauravtiwari** [comment]
@ghivert Seems like it can't fine `elm-make` inside `node_modules` - also I guess it's looking at wrong place due to `process.cwd()`

**Comment by ghivert** [comment]
Is there an easy way to indicate where to find `elm-make`?

**Comment by gauravtiwari** [comment]
Could you try this please `resolve`: 

```js
const { resolve) = require('path')
const { env } = require('../configuration.js')

const elmSource = resolve(process.cwd())
const elmMake = resolve('node_modules/.bin/elm-make')
```

Try it locally first - haven't tested it

**Comment by gauravtiwari** [comment]
Ignore that - I think it's something to do with binaries not installed correctly on Heroku

**Comment by ghivert** [comment]
I tried, I still have same error (i.e. `Error: spawn /tmp/build_6a260800d4f68c41c5b2d6fa939e68a7/node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm-make ENOENT`).

Is there anything I can do?

**Comment by gauravtiwari** [comment]
Alright got it. Please try this - `npm rebuild elm` in your package.json

```json
  "scripts": {
    "postinstall": "npm rebuild node-sass && npm rebuild elm"
  }
```

Seems like yarn can't install those in first run or something like node-sass

![screen shot 2017-05-25 at 10 05 03](https://cloud.githubusercontent.com/assets/771039/26443785/b4e3ac82-4131-11e7-989d-e18291736b46.png)

**Comment by ghivert** [comment]
I just tried and it's working! Thanks for your help!

**Comment by gauravtiwari** [comment]
We should add this to troubleshooting section in README
