### ISSUE TITLE
Webpacker doesn't support procs for asset_hosts

### ISSUE THREAD

**Issue by fabn** [rails/webpacker#463]
I just tried to deploy my first app upgraded to use webpacker gem and I got this error on assets compilation:

```
yarn install v0.24.5
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
       info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       Done in 5.93s.
       Webpacker is installed 🎉 🍰
       Using /tmp/build_8cb320e52ea424a022afd666511e207a/config/webpack/paths.yml file for setting up webpack paths
       Compiling webpacker assets 🎉
       sh: 1: cannot open Proc:0x007ff3b9c6e530@/tmp/build_8cb320e52ea424a022afd666511e207a/config/environments/production.rb:80: No such file
       rake aborted!
       JSON::ParserError: A JSON text must at least contain two octets!
       /tmp/build_8cb320e52ea424a022afd666511e207a/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:155:in `initialize'
       /tmp/build_8cb320e52ea424a022afd666511e207a/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:155:in `new'
       /tmp/build_8cb320e52ea424a022afd666511e207a/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
       /tmp/build_8cb320e52ea424a022afd666511e207a/vendor/bundle/ruby/2.3.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:13:in `block (2 levels) in <top (required)>'
       /tmp/build_8cb320e52ea424a022afd666511e207a/vendor/bundle/ruby/2.3.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:40:in `block in <top (required)>'
       /tmp/build_8cb320e52ea424a022afd666511e207a/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
       Tasks: TOP => webpacker:compile
       (See full trace by running task with --trace)
```

I was using a Proc for asset_host as outlined [here](http://api.rubyonrails.org/classes/ActionView/Helpers/AssetUrlHelper.html), but obviously it's not working in js context.

I don't know if there is any workaround for that, in any case this should be outlined in webpacker Readme.

After I changed that value with a string everything worked.

**Comment by gauravtiwari** [comment]
@fabn Thanks for filing this. I thought we fixed this problem - https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker/compile.rake#L10

You are using latest webpacker right? From logs it seems you are still using 1.2.

**Comment by fabn** [comment]
I tried it locally and it seems to work with webpacker 2.0, thanks.
