### ISSUE TITLE
compiling assets with rbenv ruby fails

### ISSUE THREAD

**Issue by doits** [rails/webpacker#499]
With webpack 2.0.0 (earlier versions not tested):

I've rbenv installed and set it globally (`rbenv global`) and locally (with `.ruby-version`) to version "2.4.1". When trying to run `./bin/webpack` with a `.js.erb` file it fails with the following message:

```
$ RAILS_ENV=production ./bin/webpack
ERROR in ./app/javascript/packs/vue_global_components.js.erb
Module build failed: Error: Command failed: bin/rails runner /path/shared/node_modules/rails-erb-loader/erb_transformer.rb __RAILS_ERB_LOADER_DELIMETER__ erb
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /path/releases/20170613205524/bin/spring:8:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
```

There's ruby "2.3.0" in the backtrace - so it looks like it is ignoring the rbenv ruby and therefore cannot find the correct gems of course (because they are installed with "2.4.1").

But manually I can run `bin rails runner` and it is respecting my rbenv config:

```
$ RAILS_ENV=production bin/rails runner 'puts RUBY_VERSION'
2.4.1
```

How can I make it respect my rbenv environment when running `webpack`?

**Comment by doits** [comment]
I just verified it is using the wrong ruby version by putting a `raise RUBY_VERSION` at the beginning of `bin/rails` and indeed, it raises ruby version `2.3.1` when running `./bin/webpack`.

**Comment by doits** [comment]
I added a PR (#500) to include this change by default.

**Comment by doits** [comment]
Deleted my last comment, wrong thread ...

**Comment by doits** [comment]
I traced it down to the `PATH`: When `bin/rails` is run through `webpack`, it gets changed so it includes `/usr/bin` in front of the original `PATH`.

```
$ echo $PATH
/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

$ head bin/rails -n2
#!/usr/bin/env ruby
raise ENV['PATH'].inspect

$ RAILS_ENV=production ./bin/webpack
[...]
ERROR in ./app/javascript/packs/vue_global_components.js.erb
Module build failed: Error: Command failed: bin/rails runner /path/shared/node_modules/rails-erb-loader/erb_transformer.rb __RAILS_ERB_LOADER_DELIMETER__ erb
bin/rails:2:in `<main>': "/path/releases/20170613205524/node_modules/.bin:/path/.config/yarn/link/node_modules/.bin:/path/releases/20170613205524/node_modules/.bin:/path/.config/yarn/link/node_modules/.bin:/usr/bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/rbenv/versions/2.4.1/bin:/usr/local/rbenv/libexec:/usr/local/rbenv/plugins/ruby-build/bin:/usr/local/rbenv/plugins/rbenv-vars/bin:/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games" (RuntimeError)
```

There's clearly a `/usr/bin` in front of the `libexec` from rbenv, so I think this is the culprit why local installed ruby got executed instead of the one installed by rbenv ... questions is, why and where is that PATH manipulated this way?

**Comment by doits** [comment]
Looks like `yarn run` is doing some things with the `PATH` which breaks `rbenv` by always prepending `/usr/bin` to the existing `PATH`. I opened a bug report there ...

**Comment by doits** [comment]
This was actually a yarn issue and is fixed with https://github.com/yarnpkg/yarn/pull/3637
