### ISSUE TITLE
Error: stdout maxBuffer exceeded on template with more than 204.739 characters

### ISSUE THREAD

**Issue by mdesantis** [rails/webpacker#554]
Hello,

if you create an `app.vue.erb` with this inside:

```
<%= 'a'*204_739 %>
```

You dont'get a `stdout maxBuffer excedeed` error, otherwise wih this:

```
<%= 'a'*204_740 %>
```

You get this error:

```
15:55:15.889 Error: Module build failed: Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:257:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20) 1 hello_vue.js%20line%201054%20%3E%20eval:1:7
  <anonimo> http://0.0.0.0:8080/packs/hello_vue.js%20line%201054%20%3E%20eval:1:7
  <anonimo> http://0.0.0.0:8080/packs/hello_vue.js:1054:1
  __webpack_require__ http://0.0.0.0:8080/packs/hello_vue.js:20:12
  <anonimo> http://0.0.0.0:8080/packs/hello_vue.js%20line%201086%20%3E%20eval:3:84
  <anonimo> http://0.0.0.0:8080/packs/hello_vue.js:1086:1
  __webpack_require__ http://0.0.0.0:8080/packs/hello_vue.js:20:12
  <anonimo> http://0.0.0.0:8080/packs/hello_vue.js:1100:18
  __webpack_require__ http://0.0.0.0:8080/packs/hello_vue.js:20:12
  <anonimo> http://0.0.0.0:8080/packs/hello_vue.js:66:18
  <anonimo> http://0.0.0.0:8080/packs/hello_vue.js:1:11

```

**Comment by akaspick** [comment]
Same issue.  I have some templates using ```render``` to output some large amounts of markup and I'm getting this error.  I'd ideally like webpacker not to output the results of the compilation to stdout at all since the amount of data is so large.

**Comment by janklimo** [comment]
Does splitting your code into smaller modules and importing them help?

**Comment by gauravtiwari** [comment]
Please open this issue on `rails-erb-loader` repo: https://github.com/usabilityhub/rails-erb-loader
