### ISSUE TITLE
rails new --webpack fails with "Don't know how to build task 'webpacker:install'"

### ISSUE THREAD

**Issue by sebroeder** [rails/webpacker#61]
OK, maybe I am just holding it wrong, but I could not set up a new Rails project from rails master with `rails new --webpack`.

```sh
# from inside the rails repo, master branch
bundle exec railties/exe/rails new ../rails-5.1-webpack --webpack --dev
# more output from rails new omitted...
Bundle complete! 14 Gemfile dependencies, 60 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
       rails  webpacker:install
rails aborted!
Don't know how to build task 'webpacker:install' (see --tasks)
/Users/sebroeder/Developer/ruby/rails-master/railties/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/sebroeder/Developer/ruby/rails-master/railties/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/sebroeder/Developer/ruby/rails-master/railties/lib/rails/command.rb:36:in `invoke'
/Users/sebroeder/Developer/ruby/rails-master/railties/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

Running `rails webpacker:install` from inside the new project after the failed `rails new` installs successfully, however:

```
cd ../rails-5.1-webpack/
bundle exec rails webpacker:install
      create  app/javascript
      create  app/javascript/packs/application.js
       exist  bin
      create  bin/webpack-dev-server
      create  bin/webpack-watcher
      create  bin/webpack
   identical  bin/yarn
      create  config/webpack
      create  config/webpack/development.js
      create  config/webpack/production.js
      create  config/webpack/shared.js
      append  .gitignore
         run  ./bin/yarn add --dev webpack@beta webpack-merge webpack-dev-server@beta path-complete-extname babel-loader babel-core babel-preset-latest coffee-loader coffee-script rails-erb-loader from "."
yarn add v0.18.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "babel-core@^6.0.0".
warning Unmet peer dependency "coffee-script@1.x".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 441 new dependencies.
```

Is this just user error or a bug in `rails new --webpack`?

**Comment by dhh** [comment]
I can't replicate this. `rails/railties/exe/rails new funk --webpack --dev` is what I just used from rails/master, and it worked as intended. Maybe there's an issue with your use of bundle exec? In any case, do open a PR if you find something!

**Comment by sebroeder** [comment]
Running the command without `bundle exec` worked, thanks David.
