### ISSUE TITLE
Heroku fails during precompiling without verbose error output

### ISSUE THREAD

**Issue by Ephs05msm** [rails/webpacker#697]
Running into issues deploying to Heroku all of a sudden.

Project uses elm with Rails 5.1.3, ruby 2.4.1p111, node 8.2.1. Using the `postinstall: npm rebuild elm` script as suggested. Note the `npm: not found` error on Heroku; however, the deploy has worked despite this until today.

Log looks like:

```
remote:        Running: rake assets:precompile
remote:        yarn install v0.22.0
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning "coffee-loader@0.8.0" has unmet peer dependency "coffeescript@>= 1.8.x".
remote:        [4/4] Building fresh packages...
remote:        $ npm rebuild elm
remote:        sh: 1: npm: not found
remote:        error Command failed with exit code 127.
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
remote:        I, [2017-08-25T00:11:59.150004 #454]  INFO -- : Writing /tmp/build_71990bb87727c35fe9c14324f9f77078/public/assets/application-f3dbd6eb5363
822716e503df8c00de2fa8b894c30c8e3cd77ab44de142ada5fd.css
remote:        I, [2017-08-25T00:11:59.151278 #454]  INFO -- : Writing /tmp/build_71990bb87727c35fe9c14324f9f77078/public/assets/application-f3dbd6eb5363
822716e503df8c00de2fa8b894c30c8e3cd77ab44de142ada5fd.css.gz
remote:        Webpacker is installed 🎉 🍰
remote:        Using /tmp/build_71990bb87727c35fe9c14324f9f77078/config/webpacker.yml file for setting up webpack paths
remote:        [Webpacker] Compiling assets 🎉
remote:        error Command failed with exit code 2.
remote:
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
```

`NODE_ENV=production RAILS_ENV=production assets:precompile --trace` is successful locally.
Uglify warnings are `true` in production.js. No more error output than the above.

Thanks in advance for the help.

**Comment by Ephs05msm** [comment]
In production.js, revised `stats: 'normal'` to `stats: 'verbose'` and am now getting the details:

```
remote:        ERROR in ./app/javascript/packs/InputBar.elm
remote:        Module build failed: Error: Compiler process exited with error Compilation failed
remote:        Error: The following HTTP request failed.
remote:        <http://package.elm-lang.org/all-packages?elm-package-version=0.18>
remote:        FailedConnectionException2 "package.elm-lang.org" 80 False getAddrInfo: does not exist (Temporary failure in name resolution)
remote:        at ChildProcess.<anonymous> (/tmp/build_54ea733941c2bc9a43803e5df71a67d8/node_modules/node-elm-compiler/index.js:141:27)
remote:        at emitTwo (events.js:106:13)
remote:        at ChildProcess.emit (events.js:191:7)
remote:        at maybeClose (internal/child_process.js:891:16)
remote:        at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
remote:        ERROR in ./app/javascript/packs/Keys.elm
remote:        Module build failed: Error: Compiler process exited with error Compilation failed
remote:        Error: The following HTTP request failed.
remote:        <http://package.elm-lang.org/all-packages?elm-package-version=0.18>
remote:        FailedConnectionException2 "package.elm-lang.org" 80 False getAddrInfo: does not exist (Temporary failure in name resolution)
remote:        at ChildProcess.<anonymous> (/tmp/build_54ea733941c2bc9a43803e5df71a67d8/node_modules/node-elm-compiler/index.js:141:27)
remote:        at emitTwo (events.js:106:13)
remote:        at ChildProcess.emit (events.js:191:7)
remote:        at maybeClose (internal/child_process.js:891:16)
remote:        at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
remote:        ERROR in ./app/javascript/packs/ComponentHandler.elm
remote:        Module build failed: Error: Compiler process exited with error Compilation failed
remote:        Error: The following HTTP request failed.
remote:        <http://package.elm-lang.org/all-packages?elm-package-version=0.18>
remote:        FailedConnectionException2 "package.elm-lang.org" 80 False getAddrInfo: does not exist (Temporary failure in name resolution)
remote:        at ChildProcess.<anonymous> (/tmp/build_54ea733941c2bc9a43803e5df71a67d8/node_modules/node-elm-compiler/index.js:141:27)
remote:        at emitTwo (events.js:106:13)
remote:        at ChildProcess.emit (events.js:191:7)
remote:        at maybeClose (internal/child_process.js:891:16)
remote:        at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
remote:        ERROR in ./app/javascript/packs/Main.elm
remote:        Module build failed: Error: Compiler process exited with error Compilation failed
remote:        Error: The following HTTP request failed.
remote:        <http://package.elm-lang.org/all-packages?elm-package-version=0.18>
remote:        FailedConnectionException2 "package.elm-lang.org" 80 False getAddrInfo: does not exist (Temporary failure in name resolution)
remote:        at ChildProcess.<anonymous> (/tmp/build_54ea733941c2bc9a43803e5df71a67d8/node_modules/node-elm-compiler/index.js:141:27)
remote:        at emitTwo (events.js:106:13)
remote:        at ChildProcess.emit (events.js:191:7)
remote:        at maybeClose (internal/child_process.js:891:16)
remote:        at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
remote:        ERROR in ./app/javascript/packs/ReservedWords.elm
remote:        Module build failed: Error: Compiler process exited with error Compilation failed
remote:        Error: The following HTTP request failed.
remote:        <http://package.elm-lang.org/all-packages?elm-package-version=0.18>
remote:        FailedConnectionException2 "package.elm-lang.org" 80 False getAddrInfo: does not exist (Temporary failure in name resolution)
remote:        at ChildProcess.<anonymous> (/tmp/build_54ea733941c2bc9a43803e5df71a67d8/node_modules/node-elm-compiler/index.js:141:27)
remote:        at emitTwo (events.js:106:13)
remote:        at ChildProcess.emit (events.js:191:7)
remote:        at maybeClose (internal/child_process.js:891:16)
remote:        at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote:        error Command failed with exit code 2.
```

Seems to be an issue connecting to `package.elm-lang.org`; thoughts?

Thanks again.

**Comment by gauravtiwari** [comment]
@Ephs05msm Just try rebuilding again - may be `http://package.elm-lang.org/all-packages?elm-package-version=0.18` was down

**Comment by Ephs05msm** [comment]
Will do. Elm slack users reporting the same issue for more than 24 hours now. Appears to be on the AWS end, affecting Heroku downstream. Thanks for the help.
