### ISSUE TITLE
Hot module reloading crashes: Cannot use [chunkhash] for chunk in '[name]-[chunkhash].js' (use [hash] instead)

### ISSUE THREAD

**Issue by jemminger** [rails/webpacker#763]
Using v3.0.1

When running `./bin/webpack-dev-server --hot true` or `./bin/webpack-dev-server --hot true --inline true`, compilation fails with the error: 

```
ERROR in chunk application [entry]
[name]-[chunkhash].js
Cannot use [chunkhash] for chunk in '[name]-[chunkhash].js' (use [hash] instead)
Error: Cannot use [chunkhash] for chunk in '[name]-[chunkhash].js' (use [hash] instead)
    at MainTemplate.replacePathVariables (/Users/jemminger/Rails/new_tsig/node_modules/webpack/lib/TemplatedPathPlugin.js:64:9)
    at MainTemplate.applyPluginsWaterfall (/Users/jemminger/Rails/new_tsig/node_modules/tapable/lib/Tapable.js:92:24)
    at Compilation.getPath (/Users/jemminger/Rails/new_tsig/node_modules/webpack/lib/Compilation.js:1317:28)
    at Compilation.createChunkAssets (/Users/jemminger/Rails/new_tsig/node_modules/webpack/lib/Compilation.js:1299:17)
    at sealPart2 (/Users/jemminger/Rails/new_tsig/node_modules/webpack/lib/Compilation.js:646:10)
    at next (/Users/jemminger/Rails/new_tsig/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/Users/jemminger/Rails/new_tsig/node_modules/webpack/lib/ProgressPlugin.js:111:6)
    at next (/Users/jemminger/Rails/new_tsig/node_modules/tapable/lib/Tapable.js:204:14)
    at /Users/jemminger/Rails/new_tsig/node_modules/extract-text-webpack-plugin/dist/index.js:241:13
    at /Users/jemminger/Rails/new_tsig/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/jemminger/Rails/new_tsig/node_modules/async/dist/async.js:998:13)
    at /Users/jemminger/Rails/new_tsig/node_modules/async/dist/async.js:906:16
    at /Users/jemminger/Rails/new_tsig/node_modules/extract-text-webpack-plugin/dist/index.js:224:15
    at /Users/jemminger/Rails/new_tsig/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/jemminger/Rails/new_tsig/node_modules/async/dist/async.js:998:13)
    at /Users/jemminger/Rails/new_tsig/node_modules/async/dist/async.js:906:16


```
Is this the correct way to run with HMR?  If I just run `./bin/webpack-dev-server`, every time I save a change I get a full page refresh.

**Comment by caseyprovost** [comment]
@jemminger I got a very similar error earlier today going that route as well. I ended up abandoning HMR.

**Comment by javan** [comment]
You'll want to set `hmr: true` in your `webpacker.yml` `dev_server` config instead of passing it as a CLI arg. That setting is used to name the output file correctly:

https://github.com/rails/webpacker/blob/72b71a2727f8efc4c56f1a73cfd83f0fb821004f/package/environments/development.js#L18-L20

**Comment by jemminger** [comment]
@javan Thanks!  I missed that in the readme.

**Comment by caseyprovost** [comment]
Although when you turn hmr on certain pack tags in your erb file stop working :(
