### ISSUE TITLE
DISABLE_SPRING=1 breaking spring items

### ISSUE THREAD

**Issue by joerodrig** [rails/webpacker#77]
Currently building out a Rails app with Webpacker that has gems that rely on spring in multiple areas. One gem were using is `dotenv`. Dotenv relies on spring to work properly([dotenv](https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/rails.rb#L20)), and when the rails-erb-loader is run, this causes errors to be thrown like below:

```shell
ERROR in ../app/javascript/packs/demo-client/lib/digestImgPath.js.erb
Module build failed: Error: Command failed: DISABLE_SPRING=1 ../bin/rails runner /Users/Joe/Documents/demo/vendor/node_modules/rails-erb-loader/erb_transformer.rb __RAILS_ERB_LOADER_DELIMETER__ erubis
/Users/Joe/.gem/ruby/2.3.3/gems/spring-2.0.1/lib/spring/configuration.rb:31:in `application_root_path': Spring was unable to find your config/application.rb file. Your project root was detected at /Users/Joe/Documents/demo/vendor, so spring looked for /Users/Joe/Documents/demo/vendor/config/application.rb but it doesn't exist. You can configure the root of your application by setting Spring.application_root in config/spring.rb. (Spring::MissingApplication)
	from /Users/Joe/.gem/ruby/2.3.3/gems/spring-2.0.1/lib/spring/watcher.rb:24:in `watcher'
	from /Users/Joe/.gem/ruby/2.3.3/gems/spring-2.0.1/lib/spring/watcher.rb:28:in `watch'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-rails-2.1.2/lib/dotenv/rails.rb:10:in `block in <top (required)>'
	from /Users/Joe/.gem/ruby/2.3.3/gems/activesupport-5.0.1/lib/active_support/notifications/fanout.rb:127:in `finish'
	from /Users/Joe/.gem/ruby/2.3.3/gems/activesupport-5.0.1/lib/active_support/notifications/fanout.rb:46:in `block in finish'
	from /Users/Joe/.gem/ruby/2.3.3/gems/activesupport-5.0.1/lib/active_support/notifications/fanout.rb:46:in `each'
	from /Users/Joe/.gem/ruby/2.3.3/gems/activesupport-5.0.1/lib/active_support/notifications/fanout.rb:46:in `finish'
	from /Users/Joe/.gem/ruby/2.3.3/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:42:in `finish_with_state'
	from /Users/Joe/.gem/ruby/2.3.3/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:27:in `instrument'
	from /Users/Joe/.gem/ruby/2.3.3/gems/activesupport-5.0.1/lib/active_support/notifications.rb:164:in `instrument'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-2.1.2/lib/dotenv.rb:52:in `instrument'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-2.1.2/lib/dotenv.rb:16:in `block (2 levels) in load'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-2.1.2/lib/dotenv.rb:59:in `ignoring_nonexistent_files'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-2.1.2/lib/dotenv.rb:14:in `block in load'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-2.1.2/lib/dotenv.rb:46:in `block in with'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-2.1.2/lib/dotenv.rb:45:in `each'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-2.1.2/lib/dotenv.rb:45:in `reduce'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-2.1.2/lib/dotenv.rb:45:in `with'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-2.1.2/lib/dotenv.rb:13:in `load'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-rails-2.1.2/lib/dotenv/rails.rb:25:in `load'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-rails-2.1.2/lib/dotenv/rails.rb:42:in `load'
	from /Users/Joe/.gem/ruby/2.3.3/gems/dotenv-rails-2.1.2/lib/dotenv/rails.rb:45:in `block in <class:Railtie>'
	from /Users/Joe/.gem/ruby/2.3.3/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:41:in `execute_hook'
	from /Users/Joe/.gem/ruby/2.3.3/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
	from /Users/Joe/.gem/ruby/2.3.3/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:49:in `each'
	from /Users/Joe/.gem/ruby/2.3.3/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
	from /Users/Joe/.gem/ruby/2.3.3/gems/railties-5.0.1/lib/rails/application.rb:90:in `inherited'
	from /Users/Joe/Documents/demo/config/application.rb:10:in `<module:demo>'
	from /Users/Joe/Documents/demo/config/application.rb:9:in `<top (required)>'
	from /Users/Joe/.gem/ruby/2.3.3/gems/railties-5.0.1/lib/rails/commands/runner.rb:51:in `require'
	from /Users/Joe/.gem/ruby/2.3.3/gems/railties-5.0.1/lib/rails/commands/runner.rb:51:in `<top (required)>'
	from /Users/Joe/.gem/ruby/2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:138:in `require'
	from /Users/Joe/.gem/ruby/2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
	from /Users/Joe/.gem/ruby/2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:104:in `runner'
	from /Users/Joe/.gem/ruby/2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/Joe/.gem/ruby/2.3.3/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from ../bin/rails:9:in `require'
	from ../bin/rails:9:in `<main>'

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
 @ ../app/javascript/packs/demo-client/components/contacts/filters/shared/FilterTitle.jsx 15:23-70
 @ ../app/javascript/packs/demo-client/components/contacts/filters/location/LocationFilterTitle.jsx
 @ ../app/javascript/packs/demo-client/components/contacts/filters/location/LocationFilter.jsx
 @ ../app/javascript/packs/demo-client/containers/contacts/sub_containers/FiltersContainer.jsx
 @ ../app/javascript/packs/demo-client/containers/contacts/ContactsContainer.jsx
 @ ../app/javascript/packs/demo-client/containers/ErbWrapper.jsx
 @ ../app/javascript/packs/demo-client/components.js
 @ ../app/javascript/packs/demo-client.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ../app/javascript/packs/demo-client.js
```

This error doesn't come up when I don't have a .env file, but is there some way to get around this issue?

Webpacker commit: https://github.com/rails/webpacker/commit/ef24b74b5e41c1c93ac75f658f5aa205df2347d8

**Comment by joerodrig3** [comment]
I was able to get Webpacker working with the dotenv gem by patching dotenv with [this commit](https://github.com/joerodrig3/dotenv/blob/master/lib/dotenv/rails.rb).

It'd be nice to know whether the `DISABLE_SPRING` command is going to be a long-term solution and/or if there are any better workarounds  to help prevent this command from causing more spring issues from popping up down the line.

**Comment by thewoolleyman** [comment]
+1 - DISABLE_SPRING should work.

**Comment by gauravtiwari** [comment]
Does this works now @joerodrig ? That commit you mentioned is merged. Please could you consider closing this issue if it works :)

**Comment by gauravtiwari** [comment]
I assume this no longer is an issue. I tried this and it works so, we can close this one 👍
