### ISSUE TITLE
Compile fails during webpack:compile

### ISSUE THREAD

**Issue by jvkiran** [rails/webpacker#796]
```
deploy:assets:webpack
      01 cd /home/cardeploy/app/cardlove-api2/releases/20170913123646 && NODE_ENV=staging bundle exec rails webpacker:compile
      01 /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find rake-12.1.0 in any of the sources (Bundler::G…
      01 	from /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
      01 	from /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
      01 	from /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
      01 	from /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
      01 	from /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
      01 	from /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
      01 	from /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
      01 	from /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
      01 	from /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
      01 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      01 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

```

**Comment by javan** [comment]
Is `rake` in your `Gemfile`?

**Comment by jvkiran** [comment]
Yes it's there

**Comment by gauravtiwari** [comment]
@jvkiran This is not related to webpacker but anyway are you able to compile locally? `NODE_ENV=staging bundle exec rails webpacker:compile` using this command

**Comment by jvkiran** [comment]
Yeah i can able to compile locally, but error appears during deployment to the server using capistrano.

**Comment by gauravtiwari** [comment]
Right, then it's certainly not related to webpacker. Are you sure `rake` is in your Gemfile and not scoped to particular group i.e. rake is available in staging env as well?

**Comment by aponcz** [comment]
I just experienced this and spring was in a weird state.  I stopped spring and it fixed the issue:

```
./bin/spring stop
