### ISSUE TITLE
Installing Webpacker crashes app

### ISSUE THREAD

**Issue by JarLowrey** [rails/webpacker#883]
Have existing 5.1.4 Rails app.

Add `gem 'webpacker', '~> 3.0'` to Gemfile, `bundle`. `rails s` works. Run `bundle exec rails  
webpacker:install`, no errors. Run `rails s` and the following error occurs after loading ~63 seconds in `app/views/layouts/application.html.erb`. 

```
ActionView::Template::Error (uninitialized constant ERB::Runner):
```

Has this been seen before?

Originally thought it was an issue with react-on-rails  https://github.com/shakacode/react_on_rails/issues/943#issuecomment-333346940 but reverted to a previous commit, freshly installed webpacker and it still occurs.

**Comment by rossta** [comment]
Would you mind providing the full backtrace?

**Comment by JarLowrey** [comment]
It looks like the issue was this line `Rails.application.config.assets.precompile +=  ['*.js', '*.erb']` in `config/initializers/assets.rb`. I originally had it in so that I could individually include JS files instead of sending one large appplication.js. Thought that might be faster in HTTP2. Though obviously including a wild card could create errors like this one. To fix I commented out the line, or could individually include JS files/folders, just so long as not all ERB and JS files are included. 

FYI the original backtrace was: 

```
node_modules/rails-erb-loader/test/erb/runner.js.erb:1:in `_evaluate_template'
sprockets (3.7.1) lib/sprockets/erb_processor.rb:26:in `call'
sprockets (3.7.1) lib/sprockets/erb_processor.rb:13:in `call'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.7.1) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.7.1) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.7.1) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.7.1) lib/sprockets/loader.rb:44:in `load'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.7.1) lib/sprockets/bundle.rb:23:in `block in call'
sprockets (3.7.1) lib/sprockets/utils.rb:200:in `dfs'
sprockets (3.7.1) lib/sprockets/bundle.rb:24:in `call'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.7.1) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.7.1) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.7.1) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.7.1) lib/sprockets/loader.rb:44:in `load'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.7.1) lib/sprockets/base.rb:66:in `find_asset'
sprockets (3.7.1) lib/sprockets/base.rb:73:in `find_all_linked_assets'
sprockets (3.7.1) lib/sprockets/manifest.rb:142:in `block in find'
sprockets (3.7.1) lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
sprockets (3.7.1) lib/sprockets/path_utils.rb:228:in `block in stat_tree'
sprockets (3.7.1) lib/sprockets/path_utils.rb:212:in `block in stat_directory'
sprockets (3.7.1) lib/sprockets/path_utils.rb:209:in `each'
sprockets (3.7.1) lib/sprockets/path_utils.rb:209:in `stat_directory'
sprockets (3.7.1) lib/sprockets/path_utils.rb:227:in `stat_tree'
sprockets (3.7.1) lib/sprockets/path_utils.rb:231:in `block in stat_tree'
sprockets (3.7.1) lib/sprockets/path_utils.rb:212:in `block in stat_directory'
sprockets (3.7.1) lib/sprockets/path_utils.rb:209:in `each'
sprockets (3.7.1) lib/sprockets/path_utils.rb:209:in `stat_directory'
sprockets (3.7.1) lib/sprockets/path_utils.rb:227:in `stat_tree'
sprockets (3.7.1) lib/sprockets/path_utils.rb:231:in `block in stat_tree'
sprockets (3.7.1) lib/sprockets/path_utils.rb:212:in `block in stat_directory'
sprockets (3.7.1) lib/sprockets/path_utils.rb:209:in `each'
sprockets (3.7.1) lib/sprockets/path_utils.rb:209:in `stat_directory'
sprockets (3.7.1) lib/sprockets/path_utils.rb:227:in `stat_tree'
sprockets (3.7.1) lib/sprockets/path_utils.rb:231:in `block in stat_tree'
sprockets (3.7.1) lib/sprockets/path_utils.rb:212:in `block in stat_directory'
sprockets (3.7.1) lib/sprockets/path_utils.rb:209:in `each'
sprockets (3.7.1) lib/sprockets/path_utils.rb:209:in `stat_directory'
sprockets (3.7.1) lib/sprockets/path_utils.rb:227:in `stat_tree'
sprockets (3.7.1) lib/sprockets/legacy.rb:105:in `each'
sprockets (3.7.1) lib/sprockets/legacy.rb:105:in `block in logical_paths'
sprockets (3.7.1) lib/sprockets/legacy.rb:104:in `each'
sprockets (3.7.1) lib/sprockets/legacy.rb:104:in `logical_paths'
sprockets (3.7.1) lib/sprockets/manifest.rb:140:in `find'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in `each'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in `map'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in `precompiled_assets'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:35:in `asset_precompiled?'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:251:in `block (3 levels) in <class:Railtie>'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:359:in `precompiled?'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:363:in `raise_unless_precompiled_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:348:in `find_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:229:in `block in lookup_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `each'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `detect'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `resolve_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:228:in `lookup_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:170:in `block in stylesheet_link_tag'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:169:in `map'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:169:in `stylesheet_link_tag'
app/views/layouts/application.html.erb:23:in `_app_views_layouts_application_html_erb__1916138153888142661_47095280'
actionview (5.1.2) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.2) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.2) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.2) lib/action_view/template.rb:155:in `render'
rack-mini-profiler (0.10.5) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:64:in `render_with_layout'
actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.1.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.1.2) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.1.2) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.1.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.1.2) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.1.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.1.2) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (5.1.2) lib/abstract_controller/rendering.rb:24:in `render'
actionpack (5.1.2) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.1.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/james/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
activesupport (5.1.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.1.2) lib/action_controller/metal/implicit_render.rb:33:in `default_render'
actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
rack-mini-profiler (0.10.5) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.2) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
rack-mini-profiler (0.10.5) lib/mini_profiler/profiler.rb:282:in `call'
webpacker (3.0.1) lib/webpacker/dev_server_proxy.rb:17:in `perform_request'
rack-proxy (0.6.2) lib/rack/proxy.rb:57:in `call'
railties (5.1.2) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```
