### ISSUE TITLE
Cannot find module 'extract-text-webpack-plugin' while deploy to Heroku

### ISSUE THREAD

**Issue by serv** [rails/webpacker#907]
While deploy to Heroku, during Webpacker compiling assets, I get this error message

```
remote:        [Webpacker] Compiling assets 🎉
remote:        warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
remote:        module.js:529
remote:        throw err;
remote:        ^
remote:        Error: Cannot find module 'extract-text-webpack-plugin'
remote:        at Function.Module._resolveFilename (module.js:527:15)
remote:        at Function.Module._load (module.js:476:23)
remote:        at Module.require (module.js:568:17)
remote:        at require (internal/module.js:11:18)
remote:        at Object.<anonymous> (/tmp/build_e272416c75b9c08ce0264f98848eb4df/config/webpack/shared.js:9:27)
remote:        at Module._compile (module.js:624:30)
remote:        at Object.Module._extensions..js (module.js:635:10)
remote:        at Module.load (module.js:545:32)
remote:        at tryModuleLoad (module.js:508:12)
remote:        at Function.Module._load (module.js:500:3)
remote:        error Command failed with exit code 1.
remote:        
remote:  !
remote:  !     Precompiling assets failed.
```

Some info about my environment.

Yarn version: 1.0.1
Rails 5.1.2
Webpacker 2.0

**Comment by serv** [comment]
BTW this worke fine locally. The problem happens only when I try to deploy to heroku

`NODE_ENV=production RAILS_ENV=production rails assets:precompile --trace`

**Comment by gauravtiwari** [comment]
That's strange! I see you are using 2.0, is `extract-text-plugin` under devDependencies inside package.json?

**Comment by serv** [comment]
@gauravtiwari Gonna close this one. 
Please see this issue instead.
https://github.com/rails/webpacker/issues/915
