### ISSUE TITLE
Yarn error for Elm install: Errno::ENOENT: No such file or directory @ rb_sysopen - /path/to/app/elm-package.json

### ISSUE THREAD

**Issue by AdamT** [rails/webpacker#911]
Hi there 👋 ,

Rails 5.1.4
Yarn 1.1.0
Webpacker 3.0

I'm getting an error when I run `rails webpacker:install:elm`
```
...
...
success Saved 1 new dependency.
└─ elm-hot-loader@0.5.4
warning No license field
✨  Done in 2.97s.
         run  yarn run elm package install -- --yes from "."
yarn run v1.1.0
warning package.json: No license field
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ "/Users/me/node_modules/.bin/elm" "package" "install" "--yes"
Packages configured successfully!
✨  Done in 0.88s.
Updating Webpack paths to include Elm file extension
      insert  config/webpacker.yml
Updating Elm source location
        gsub  elm-package.json
rails aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /path/to/my_app/elm-package.json
/Users/me/.rvm/gems/ruby-2.4.1@gemset/gems/thor-0.20.0/lib/thor/actions/file_manipulation.rb:263:in `binread'
/Users/me/.rvm/gems/ruby-2.4.1@gemset/gems/thor-0.20.0/lib/thor/actions/file_manipulation.rb:263:in `gsub_file'
/Users/me/.rvm/gems/ruby-2.4.1@gemset/gems/webpacker-3.0.2/lib/install/elm.rb:20:in `apply'
/Users/me/.rvm/gems/ruby-2.4.1@gemset/gems/thor-0.20.0/lib/thor/actions.rb:225:in `instance_eval'
/Users/me/.rvm/gems/ruby-2.4.1@gemset/gems/thor-0.20.0/lib/thor/actions.rb:225:in `apply'
/Users/me/.rvm/gems/ruby-2.4.1@gemset/gems/railties-5.1.4/lib/rails/tasks/framework.rake:13:in `block (2 levels) in <top (required)>'
/Users/me/.rvm/gems/ruby-2.4.1@gemset/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/me/.rvm/gems/ruby-2.4.1@gemset/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/me/.rvm/gems/ruby-2.4.1@gemset/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/me/.rvm/gems/ruby-2.4.1@gemset/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
./bin/rails:4:in `require'
./bin/rails:4:in `<main>'
```
Looking at the error message, I downgraded to yarn v0.27.5:
```
...
...
warning No license field
Done in 3.98s.
         run  yarn run elm package install -- --yes from "."
yarn run v0.27.5
warning package.json: No license field
warning ../../../package.json: No license field
$ "/Users/me/my_app/node_modules/.bin/elm" "package" "install" "--yes"
Starting downloads...

  ● elm-lang/html 2.0.0
  ● elm-lang/virtual-dom 2.0.4
  ● elm-lang/core 5.1.1

Packages configured successfully!
Done in 4.39s.
Updating Webpack paths to include Elm file extension
      insert  config/webpacker.yml
Updating Elm source location
        gsub  elm-package.json
Updating .gitignore to include elm-stuff folder
      insert  .gitignore
Webpacker now supports Elm 🎉
```

Update:
Having downgraded yarn, I upgraded back to latest with `npm install -g yarn` and was then able to run `rails webpacker:install:elm`.
I suspect this issue is specific to my machine.
Should I leave this open for a bit to see if anyone else has come across this sort of issue? Otherwise let's close.

**Comment by thopham** [comment]
Is your yarn latest version 1.2.0? I've got the same issue with yarn 1.2.0. I'm trying to resolve myself now.

**Comment by gauravtiwari** [comment]
Worth filing an issue on yarn repo 👍

**Comment by AdamT** [comment]
@thopham I tested with yarn 0.27.5 and 1.1.

I'm not sure what the difference is between installing with `brew` vs `npm` but can you try it with:
`npm install -g yarn`?

**Comment by thopham** [comment]
yes, I installed yarn globally as above. Just an update, I downgraded yarn to 0.27.5 but no luck.

**Comment by AdamT** [comment]
@thopham what happens when you:
```
$ rails webpacker:check_yarn
$ rails webpacker:verify_install
```
?

**Comment by thopham** [comment]
Here it is
> Webpacker is installed 🎉 🍰
Using /app/config/webpacker.yml file for setting up webpack paths

**Comment by gauravtiwari** [comment]
@AdamT Seems to be working fine with yarn 1.2.1

![screen shot 2017-10-14 at 22 13 08](https://user-images.githubusercontent.com/771039/31579372-e27880bc-b12c-11e7-8afe-85243a5a8741.png)
