### ISSUE TITLE
rake webpacker:check_node errors out if no node installed

### ISSUE THREAD

**Issue by tdegrunt** [rails/webpacker#954]
Version: webpacker 3.0.2
Ruby: 2.4.2

```
rake webpacker:check_node --trace                                                                                                     ⏎
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
/Users/tdegrunt/.rbenv/versions/2.4.2/bin/rake: No such file or directory - node
rake aborted!
NoMethodError: undefined method `strip' for nil:NilClass
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/webpacker-3.0.2/lib/tasks/webpacker/check_node.rake:16:in `block (2 levels) in <top (required)>'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:81:in `block in run'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
/Users/tdegrunt/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/Users/tdegrunt/.rbenv/versions/2.4.2/bin/rake:23:in `load'
/Users/tdegrunt/.rbenv/versions/2.4.2/bin/rake:23:in `<main>'
Tasks: TOP => webpacker:check_node
```

If this code in check_node.rake is changed:
```ruby
      begin
        node_version = `node -v`
      rescue Errno::ENOENT
        node_version = `nodejs -v`
        raise Errno::ENOENT if node_version.blank?
      end
```
to:
```ruby
      begin
        node_version = `node -v`
      rescue Errno::ENOENT
        node_version = `nodejs -v`
      end
      raise Errno::ENOENT if node_version.blank?
```

it seems to behave and report:

```
rake webpacker:check_node --trace                                                                                                     ⏎
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
/Users/tdegrunt/.rbenv/versions/2.4.2/bin/rake: No such file or directory - node
Node.js not installed. Please download and install Node.js https://nodejs.org/en/download/
```

I thought one could re-raise in rescue blocks?

**Comment by sergeyvdovareize** [comment]
I have a related question. Why doesn't the check_node task see node? node is installed using nvm. *node -v* returns the version. but the task says *No such file or directory - node*. But the check_yarn task sees the yarn version.

**Comment by mxmzb** [comment]
I have the same issue when I try to deploy my app with Docker. It fails the deployment with the output above at the precompiling process...

**Comment by brasic** [comment]
I can also confirm this is happening when node is not installed.  The reason is that when activesupport is loaded [this monkeypatch](https://github.com/rails/rails/blob/7d75599c875b081f63fc292e454b25e8e42eb60e/activesupport/lib/active_support/core_ext/kernel/agnostics.rb) suppresses `Errno::ENOENT`.  Simple reproduction script:

```
require 'active_support/core_ext/kernel/agnostics'

begin
  node_version = `node -v`
rescue Errno::ENOENT
  node_version = `nodejs -v`
  raise Errno::ENOENT if node_version.blank?
end

puts "node_version is '#{node_version}'" # without AS monkeypatch, we would never reach this line
```

The fallback for legacy versions of node introduced in #798 doesn't actually work because of this. Since webpacker is always used alongside rails, this task should not assume that backticks behave as they do in vanilla ruby.
